### ISSUE TITLE
Ability to watch a post in the mod queue

### ISSUE THREAD

**Issue by ToksT** [danbooru/danbooru#1213]
> Log said:
> 
> Alright, I have a request for the mod queue.
> 
> The ability to "watch" a post. Have it stick in your mod queue with it's current status displayed until you actually manually click "unwatch" (or stick/unstick.) Sometimes I just can't decide on a post and would like to think on it for a couple days, if someone else approves it in that time I'd like to at least know so I know I wasn't alone in finding the post interesting. Yes, I can sort of do this manually by clicking the hide link a lot and just leaving the post at the top of my queue but generally I'll forget I had a post I was questioning myself about in the first place and only find it months later if ever.

**Comment by r888888888** [comment]
I feel like this could be implemented with a disapproval + timed delayed job to revert the disapproval. I'd think of it more as a snooze button to reconsider a post after some time.

**Comment by Type-kun** [comment]
> I feel like this could be implemented with a disapproval + timed delayed job to revert the disapproval. 

Perhaps, but at what interval would that job work? What if post falls off the queue during that interval?

It looks like a special case of "favorite groups" indeed, and perhaps the existing structure should be used? Add "snooze button" to queue which would push a post to some predefined favgroup named "watchlist" and hide it, or something like that. Though, it think there should be a simple mechanism to remove posts from watchlist for it to actually be useful.

**Comment by r888888888** [comment]
No need for an interval. You can schedule a job to run at X so what would happen in this case is when the job finally runs (say, one day ahead), the disapproval is removed and the post appears back in the queue for the user. I don't really see the need for a favgroup in this case unless the user really wants to see all the posts they've snoozed.

**Comment by Type-kun** [comment]
> You can schedule a job to run at X so what would happen in this case is when the job finally runs (say, one day ahead), the disapproval is removed and the post appears back in the queue for the user. 

But what if the post was on its 3rd day in the queue and will already be deleted by the time delayed job runs? Also, original request by log asks them to be visible even if approved. There's room for discussion if that's necessary, though. Will bring it up again on the forums.

**Comment by r888888888** [comment]
Snooze would have to be disabled in cases like that. I don't think it makes any sense to hold up the 3 day window just because one mod wasn't sure.
