### ISSUE TITLE
Dtext: Text near a list will be joined into the last bullet point

### ISSUE THREAD

**Issue by ToksT** [danbooru/danbooru#1964]
For example, this dtext:

```
List A:
* Bullet 1
* Bullet 2
Normal text
List B:
* Bullet 1
More normal text
```

Would actually render like this:

List A:
- Bullet 1
- Bullet 2Normal textList B:
- Bullet 1More normal text

**Comment by evazion** [comment]
Another problem here is that it can break quotes:

```
[quote]
Person A said:

Lorem ipsum dolor sit amet:

[quote]
Person B said:

* Consectetur adipiscing elit, sed do eiusmod.
[/quote]

Ut enim ad minim veniam, quis nostrud exercitation.
[/quote]
```

The `[/quote]` tag following the list gets swallowed up and the inner quote block isn't closed.

**Comment by evazion** [comment]
The example from the OP:

```
List A:
* Bullet 1
* Bullet 2
Normal text
List B:
* Bullet 1
More normal text
```

Will now be treated as if you had written this:

```
List A:

* Bullet 1
* Bullet 2

Normal text
List B:

* Bullet 1

More normal text
```

Note that before there were cases where someone wrote

```
* Bullet 1
Continuation of bullet 1
* Bullet 2
```

and they really did intend for the second line to be part of the first bullet. This is no longer possible. Now it will be the same as writing this:

```
* Bullet 1

Continuation of bullet 1

* Bullet 2
```
