### ISSUE TITLE
dmail: Turn nested quote block into expand block

### ISSUE THREAD

**Issue by RaisingK** [danbooru/danbooru#2018]
Viewing/previewing dmail only:

Since the Respond link wraps the old message in a quote block, a Respond to that Respond wraps _that_ in a quote block, etc...; you end up with deeply-nested quote blocks taking up a lot of space.

Second level quote blocks should be displayed as expand blocks with the first line in the block as the label, e.g. `[expand=RaisingK said:]`.  The block remains `[quote]` in the raw text.

`QuoteA --> QuoteB --> QuoteC` displays as `QuoteA --> ExpandB --> QuoteC`.  When the user responds to that, the message displays as `QuoteX --> ExpandA --> QuoteB --> QuoteC`.

**Comment by BrokenEagle** [comment]
Closing this per the discussion on Discord in #technical. I.e. quoted portions in Dmails will be removed when doing a reply.
