### ISSUE TITLE
hidden tags (loli, shota) and banned_artist posts accessible via api even for basic and anonymous users

### ISSUE THREAD

**Issue by ghostrigger** [danbooru/danbooru#2096]
this makes the web interface for privilege accounts useless for people that can write aggregators or download apps offering such feature to bypass restrictions.

example:
https://danbooru.donmai.us/posts.xml?page=1&tags=banned_artist+loli&limit=40

i think meta information itself is harmless, like the source url in pixiv if known. third-party programs can be written to go there instead. but i think md5 hash (for filename) and data (full size) directory should be protected based on user levels.

edit:
related: issue #1081

**Comment by shubert214** [comment]
Can someone explain to me a rather technologically ungifted man how I'm supposed to do it to view the hidden tag posts??
