### ISSUE TITLE
Option to disable responsive/mobile view

### ISSUE THREAD

**Issue by ToksT** [danbooru/danbooru#2549]

**Comment by mseymour** [comment]
I guess that would make sense to have a way to enable/disable the `viewport` meta tag, although now that I did look at the responsiveness of the site as it was, it needs some work first before implementing a switch to allow users to have a full-featured mobile view.

**Comment by Type-kun** [comment]
Would SCSS allow to wrap the entire responsive CSS code into a block to work only if some class is present in `<body>` element? Then disabling it is as simple as removing the class. It's possible to just prefix every entry with class name and space, but it's tedious and prone to mistakes.

**Comment by ToksT** [comment]
> Would SCSS allow to wrap the entire responsive CSS code into a block to work only if some class is present in <body> element?

yes

**Comment by r888888888** [comment]
These guards were added to the CSS so I don't think they're an issue anymore? I readded the viewport and have deployed to Testbooru. Seems to work for me.

**Comment by evazion** [comment]
It still forces the mobile layout, which still has a lot of usability problems.

**Comment by evazion** [comment]
Current the desktop version link redirects to `/posts`. It should keep you on the same page instead.

Also there's not a way to delete the desktop mode cookie if you want to switch back to mobile mode.

**Comment by evazion** [comment]
This was fixed in a95af95eaeaaa82cebed7acc236d5a7f34b6e580.
