### ISSUE TITLE
Comment undeletion not possible via web interface

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#2728]
From #2704:

> The ability to undelete comments was introduced in a444051.
> 
> > Is there any way to access this functionality through HTML? It seems that Danbooru automatically hides the comments and their functions, even when you're specifically searching for deleted comments or go to the deleted comment directly, therefore it seems like there's no way for regular users to undelete comments (haven't tried it through the API yet).
> > 
> > Just tested it through the API and it does work. Still, is there a way to access this functionality from the web interface?
> > 
> > > I think there are still some CurrentUser.is_moderator? checks around deleted posts in the view templates.

**Comment by evazion** [comment]
76edfd9 is an attempt at this. However I realized that this would allow people to undelete comments that were deleted by mods. Not sure how this should be handled, there's no way to tell if a comment was deleted by a mod or by the owner.

**Comment by BrokenEagle** [comment]
There's the field updater_id.  Could that be checked, and if the level of the ID is Moderator+, then the user wouldn't be allowed to undelete it...?

**Comment by evazion** [comment]
Good idea, that should work. Although you would also have to be locked from editing your comment if a mod has updated it, otherwise you could edit your comment, make the updater_id revert back to you, then undelete it.

**Comment by BrokenEagle** [comment]
One consequence to that is that if a moderator ever edits a comment, for whatever reason, even if it's active, it would lock that user from ever editing that comment again.  Maybe that is the desired behavior...? If not, an alternative would be to disallow edits if a note is deleted and has been modified by Moderator+.
