### ISSUE TITLE
DoS with adding metatags during tag editing

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#2732]
Adding the tags `child:1 child:2 child:3 ... child:10000` to a post lets you update the parents of thousands of posts in a single edit. Likewise with `pool:` and `newpool:` you can add a post to thousands of pools at once, or create thousands of pools in one go.

There should be a limit on the number of `newpool:` / `pool:` /`child:` metatags you can add in a single edit. How about one for `newpool:`, five for `pool:`, ten for `child:`?

**Comment by BrokenEagle** [comment]
Hmm, the following are my thoughts on it... 
1. Why does the newpool: metatag even exist? Creating a pool should be a deliberate action, and not something that might get done accidentally.  What are we even saving here...? It takes me at most one minute to create a new pool.  Are people that hard-pressed for time...? It's not like a lot of new pools are being created either. I just checked my report, and only around 30 new pools were created last month.
2. Didn't even know that functionality existed for the child metatag. It seems the opposite of easy creating the parent-child relationship that way. I usually use the parent metatag and sometimes the tag script function during my gardening. I've seen parents with more than 10 children, but I still don't believe that a user would manually look up and apply the child numbers individually all to a single post in such numbers just to be able to do everything with a single edit.  For scripts that might use this function, is anything really saved by adding multiple relationships with a single edit.  Scripts are fast and the savings would be negligible.  Therefore, why not one?
3. The pool metatag usage I was aware of, but I can't think of any usecase for adding more than a few pools to a post in one edit. I'd say 5 is a high cap, as I rarely find a post in more than 3 pools. Just make the users commit 2 or more edits if necessary, although I can't imagine if that would ever come into play.

**Comment by evazion** [comment]
ba243c1916bfed403697223465b3f71656c9298c is a fix but it depends on PR #2733 so I'll wait on that being merged.

newpool: was added in #1377 so that pool creation would be a deliberate action. I think the use case is to make pooling posts as easy as parenting them. People often parent things when pooling would be more appropriate because it's easier (see `comic pool:none parent:any`).

child: is from #2048, it was to make parenting easier during upload. Limiting it to one seems reasonable for that use case.

I'm not sure how most people use the pool: tag - I only ever add one pool at a time with it. Probably few people add more than one pool at once, so a limit of three sounds fair.

**Comment by BrokenEagle** [comment]
This already seems to have been fixed.
