### ISSUE TITLE
Add commentary_request to upload tagbox if commentary is included

### ISSUE THREAD

**Issue by RaisingK** [danbooru/danbooru#2794]
Under the assumption that original commentary usually requires translation:

On the upload page, when the "Include Commentary" box checked, automatically add `commentary_request` to the tag box.  If it is later unchecked, remove `commentary` and `commentary_request` from the tag box.

**Comment by Type-kun** [comment]
I think it's better to make a button to add commentary request in a single click. It's relatively rare, but commentary can be already in English.
