### ISSUE TITLE
Cannot exclude more than one favgroup from a search

### ISSUE THREAD

**Issue by kittey** [danbooru/danbooru#2861]
Including `-favgroup:foo -favgroup:bar` in a search will deterministically exclude posts from either the foo or bar group but not both.

This works fine for pools: Including `-pool:1 -pool:2` in a search will exclude posts from both pools.

It would be nice if it was possible to exclude more than favgroup, just like it is possible with pools.

**Comment by Type-kun** [comment]
Also fixed `favgroup:foo favgroup:bar`, which bugged the same way. Technically speaking, it's also possible to implement `~favgroup:foo ~favgroup:bar` as well, to allow returning the union of favgroups instead of intersection like a normal search does. Should it be done, or would it violate overall logic since it would work separately from the rest of `~`'d tags?

**Comment by evazion** [comment]
Rails 5 finally added [OR support](http://blog.bigbinary.com/2016/05/30/rails-5-adds-or-support-in-active-record.html). I think ultimately it would be best to upgrade so we can use that, since that way it would be possible to do things like `~foo ~pool:bar ~favgroup:baz`.

**Comment by BrokenEagle** [comment]
This seems to have already been fixed.

https://github.com/danbooru/danbooru/blob/aff3d3b18fb6a297a19e77a2a2b9974f313d0746/app/logical/post_query_builder.rb#L453-L461

Although OR grouping was mentioned above, I think it falls outside the scope of this issue.

**Comment by kittey** [comment]
> This seems to have already been fixed.

Indeed. `-favgroup:1 -favgroup:2` works, though `-favgroup:1,2` does not.

Maybe OR grouping could be added with `favgroup:1,2` rather than `~`.

**Comment by BrokenEagle** [comment]
Both of those things you mentioned fall outside the scope of **THIS** issue. The point still stands that this particular issue has been fixed.  If ID and OR grouping are desired, then they should both be filed under new issues.

**Comment by evazion** [comment]
Commas won't work for other metatags (including usernames and pool names), and I don't want to have inconsistencies in which metatags support commas.

The best way to fix this is to make the OR operator support metatags. This is doable but it's going to require rewriting most of the tag search code.
