### ISSUE TITLE
Add Tumblr integration

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#3184]
Todo list for Tumblr support:

- [x] Rewrite samples to full size.
- [x] Fix source to html page after uploading.
- [x] Fetch tags.
- [x] Fetch commentary.
- [x] Convert commentary to DText.
- [x] Support uploading from html page.
- [x] Support batch bookmarklet.
- [x] Ensure artist finder works.
- [ ] Support custom domains.

**Comment by evazion** [comment]
Some test cases:

Photo post with multiple images plus inline images:
https://noizave.tumblr.com/post/162094447052/foo-bar-baz

Photo post with one image plus HTML commentary:
https://noizave.tumblr.com/post/162206271767/header-plain-bold-italics-strike-more

Text post with multiple inline images:
https://noizave.tumblr.com/post/162221502947/test-post

Link post with inline image:
https://noizave.tumblr.com/post/162222579987/test-title

Video post with inline image:
https://noizave.tumblr.com/post/162222617101/description

Reblogged photo post with inline image:
https://noizave.tumblr.com/post/162245231582/taryndraws-wheeeeeeee-another-hogwartsona-tried

**Comment by evazion** [comment]
References:

* https://www.tumblr.com/docs/en/api/v2
* https://www.tumblr.com/oauth/apps
* http://c1qfxugcgy0.tumblr.com/post/58645866465/unindex-replied-to-your-post-it-probably
* https://github.com/r888888888/danbooru/issues/1866#issuecomment-44097934
* https://tumblr.zendesk.com/hc/en-us/articles/231256548-Custom-domains
* https://tumblr.zendesk.com/hc/en-us/articles/231709127-Lesser-known-features
* https://tumblr.zendesk.com/hc/en-us/articles/231455628-Video-posts
* https://tumblr.zendesk.com/hc/en-us/articles/231534508-Post-formatting
* https://tumblr.zendesk.com/hc/en-us/articles/231537848-Image-troubleshooting
* https://tumblr.zendesk.com/hc/en-us/articles/231885248-Sensitive-content

**Comment by BrokenEagle** [comment]
Here's some more test cases for you...

Must be logged on to Tumblr to view (redirects to `http://www.tumblr.com/login_required`)
http://herokick.tumblr.com/image/149371967912

Must be authorized w/password to view (redirects to `http://www.tumblr.com/blog_auth`)
http://hno3syo.tumblr.com/post/145702426430

I don't know about V2 of the Tumblr API, but V1 will redirect you as well for both link types.

**Comment by evazion** [comment]
Hmm. The v2 API returns `403 Forbidden` for the posts and `404 Not Found` for the blog info:

https://api.tumblr.com/v2/blog/herokick.tumblr.com/posts?id=149371967912&api_key=fuiKNFp9vQFvjLNvx4sUwti4Yb5yGutBN4Xh10LXZhhRKjWlV4
https://api.tumblr.com/v2/blog/hno3syo.tumblr.com/posts?id=145702426430&api_key=fuiKNFp9vQFvjLNvx4sUwti4Yb5yGutBN4Xh10LXZhhRKjWlV4

https://api.tumblr.com/v2/blog/herokick.tumblr.com/info&api_key=fuiKNFp9vQFvjLNvx4sUwti4Yb5yGutBN4Xh10LXZhhRKjWlV4
https://api.tumblr.com/v2/blog/hno3syo.tumblr.com/info&api_key=fuiKNFp9vQFvjLNvx4sUwti4Yb5yGutBN4Xh10LXZhhRKjWlV4

**Comment by evazion** [comment]
Fixed except for custom domains, which is being tracked in #4380 now.
