### ISSUE TITLE
Missing "Nobody here but us chickens" message for empty search results

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#3230]
https://danbooru.donmai.us/posts?tags=ricegnat+patreon_reward

If all the posts on a page are not visible, either because they're all deleted or banned/censored, then the "Nobody here but us chickens" message isn't shown. This is confusing.

**Comment by BrokenEagle** [comment]
Really...? I'm getting the chicken message with the above link.

**Comment by evazion** [comment]
I think you have the "Deleted post filter" account setting turned on. Try turning it off.

**Comment by BrokenEagle** [comment]
Yeah, that was it.
