### ISSUE TITLE
Missing post version in BigQuery dataset

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#3345]
https://danbooru.donmai.us/post_versions?page=a19672147&limit=1
https://bigquery.cloud.google.com/savedquery/679754072390:dbf29e5e9b2d4f6181c3f8efd65a5814

The above post version (#19672148) is not present in the post_versions table in the BigQuery dataset (see query above). The immediately surrounding IDs are present, however. There seems to be at least some data missing from the BigQuery dataset, but I'm not sure how much.

**Comment by r888888888** [comment]
I think I will run a cronjob to backfill these missing ones until I get a better understanding of what's happening.

**Comment by evazion** [comment]
https://bigquery.cloud.google.com/savedquery/679754072390:5fcf5474552f4934a9585cf3d3dc63e7

Here's a list of posts with missing versions. There are about 65,000 posts in the `danbooru-1343.danbooru_production.post_versions_flat_part` table that have fewer versions than what the `version` counter indicates they should have.

**Comment by r888888888** [comment]
Unfortunately BQ has a pretty big limitation with streaming data into partitioned tables in that I can only go back 30 days. The script backfilling that data is done now and I am running a nightly script to backfill also. Can you scope your query to that time frame? Still not sure why these are being missed.

**Comment by evazion** [comment]
It's not that big of a deal for me, just something I noticed. I am doing some historical queries going back more than 30 days (things like finding the top users of a given tag, or graphing tag growth over time;  see [here](https://github.com/evazion/fumimi-discord/blob/7545cab650088ee234f41c40f41d382122f691bb/lib/fumimi/bq.rb#L211-L311)), but mostly I'm doing aggregations that don't need 100% accuracy.

**Comment by nonamethanks** [comment]
Closing since there's no bigquery available anymore and a replacement has issue #4454 open.
