### ISSUE TITLE
Very high number of misses from IQDBS

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#3386]
This issue has been known for a while, but I'm reporting it now since it has been brought up in the forums as a debilitating issue for some users ([topic #9127/p210](http://danbooru.donmai.us/forum_topics/9127?page=210)).

> Benit149 said:
> 
> Something's been wrong when I use the Similar search to look up identical images uploaded by other users. If I search a Pixiv image source for an image I uploaded before, the function works. But when I tested doing similar image searches for others' uploads, the function doesn't work for me - it just says, "No matches found" even though I know there's a match. I wound up trying to upload some images that didn't return a similar image, yet was uploaded by someone else. This is rather frustrating because I use the button all the time, and I use as many tags as possible before processing the upload.
> 
> I have Greasemonkey active, but I only use it for mass tag updates. I was also forced to upgrade to Firefox Quantum earlier this week, so I don't know if that affects it in some way.

> nonamethanks said:
> 
> Yeah lately the embedded Similar search has been pretty unreliable for all of us. The best you can do is use saucenao or IQDB yourself to search for a picture before you upload it, or give a glance at the artist's tag on danbooru if it has few pictures.

> Benit149 said:
> 
> I looked at the artist's tag to find similar images yesterday. Hopefully this gets addressed soon since it's cumbersome to do it this way all the time.

Yesterday, I started collecting statistics for IQDBS, using the **post_id** parameter so that the thumbnail on Danbooru is used for the comparison.  I stopped once I had reached the one month point so that I could report what I found.

Period tested: id:2894181..2928663
Total posts: 27703
Total misses: 27548
Miss ratio: 99.5%

Although I started around post 2928663, it didn't become bad to where every post was a miss until post 2923906.  The following is text file listing all of the missing posts for the above period.

https://drive.google.com/open?id=1Mshi0gkLcnK_ch2EzRbm3tcCHSc0BEO-

I'll restart collecting data from where I left off and report back later.

**Comment by BrokenEagle** [comment]
Collected so more data, which covers back to 3 months ago.

Period tested: id:2831609..2894181
Total posts: 59109
Total misses: 42350
Miss ration: 71.6%

So the miss ratio wasn't as bad this period, but still not good.  Once again, the following file lists all of the post IDs with misses.

https://drive.google.com/open?id=1A55XrX27NtfcxkppDndKQr8EBsg6mtW1

Will continue to collect more data tomorrow.

**Comment by BrokenEagle** [comment]
Collected some more data, which goes back to 5 months ago. This time the numbers were significantly less, so much that I can just post the numbers here instead of adding a file link.

Period tested: id:2767060..2831609
Total posts: 61574
Total misses: 25
Miss ratio: 0.04%
### Posts:
[2767618, 2767621, 2767622, 2767624, 2767627, 2767629, 2767630, 2767635, 2767637, 2774172, 2800796, 2817055, 2798241, 2814242, 2783786, 2798255, 2830895, 2799281, 2795583, 2785620, 2810968, 2812511, 2767610, 2767614, 2767615]

At this point, I'm not sure there would be a lot of benefit going back any further.  It might catch the odd-one-out, but not enough to justify the resources that would consume.

**Comment by r888888888** [comment]
Updates have been queued.

**Comment by BrokenEagle** [comment]
Alright, when that gets done, I'll go back and recheck all of the above posts.

**Comment by BrokenEagle** [comment]
I rechecked this the other day starting at post 2928663, and found about 2044 misses.

https://drive.google.com/open?id=1NPti5-gm8k6TXT7IfeRf2EtL4GmN-HNu

I was going to stop there, but another user [mentioned this issue again on the forum](http://danbooru.donmai.us/forum_posts/140636):

> Benit149 said:
>
> Similar Search is on the fritz again, with the same issue I mentioned in forum #139464

So I'll keep going with the search for today, and maybe search before 2928663 tomorrow.

**Comment by r888888888** [comment]
Interestingly, these posts do show up in the logs for iqdbs as having been processed.

**Comment by r888888888** [comment]
I've expanded the logrotate to 30 days. @BrokenEagle can you run your check more frequently to catch misses?

**Comment by BrokenEagle** [comment]
Yeah, since I last posted I've only encountered about a dozen extra misses.  I'll check the most recent tomorrow like I said and report in the extra misses then.

It takes about a day to do 100K posts, so that should be around 500K a week.  To avoid posting too much, I think I'll leave it to weekends from now on.

After that, I can regularly scan the most recent uploads to catch any misses, which depending on their number could indicate a problem like what started this issue.

**Comment by BrokenEagle** [comment]
I've include the latest batch of post IDs below both from where I had finished off before at 2772595, but also where I had rescanned starting from the beginning to 2921204.

https://drive.google.com/open?id=13ks6O4ahgR0UR0G3F0Z6uEf6p0vSpwtI

I don't know why, but this time it picked up a lot more misses than the first time I scanned the 2928663..2921204.  Additionally, there were also a lot of misses before 2928663 which weren't there the last time I scanned that area a few weeks ago.

With the above, is it possible that something could have happened which caused it to discard the hits it had so that it now has misses instead?

**Comment by BrokenEagle** [comment]
Misses found yesterday.

Range: 2921204..2842882
Total: 10287

https://drive.google.com/open?id=19Q6nJ4GZj_c9vJhLWQLWVp0CSYcnXMuD

**Comment by r888888888** [comment]
Oh, here's a clue:

```
I, [2017-12-13T23:02:48.479345 #16014]  INFO -- : adding 2953932 http://danbooru.donmai.us/data/preview/71e44605ca0a33ba0bd4999c1336f7af.jpg
E, [2017-12-13T23:02:49.604840 #16014] ERROR -- : #<Net::HTTPServiceUnavailable:0x0055660a5d13b0>
```

I'll add a retry block for these.

**Comment by BrokenEagle** [comment]
Misses found yesterday.

Range: 2842882..2779955
Total: 5

[2839484, 2836342, 2836321, 2836320, 2830895]

**Comment by BrokenEagle** [comment]
This last week, I started from the beginning and scanned forwards.

IDs: 1..349139
Total missing: 1064
Missing list: https://drive.google.com/open?id=1jMT8WpPVpNViqzu4nMv2GpXVi6m65FKM

There were also three posts that 404'd...
``[9452, 164785, 263968]``
...with the following error message:
``{'success': False, 'message': 'That record was not found'}``

**Comment by r888888888** [comment]
Updates for the 7th doc have been queued.

**Comment by BrokenEagle** [comment]
IDs: 349140..821053
Total missing: 866
Missing list: https://drive.google.com/open?id=1ksejwLI30-pCpRXAtefu6muRCnXkv0le
Total errors: 9
Error list: ``[393572, 523232, 684960, 733324, 735236, 744389, 782697, 782698, 802709]``

**Comment by r888888888** [comment]
Updates for the 8th doc have been queued.

**Comment by r888888888** [comment]
Updates for the 9th doc have been queued.

**Comment by BrokenEagle** [comment]
IDs: 1298344..2015948
Total missing: 5944
Missing list: https://drive.google.com/open?id=1wEpwCrM6LSOXErmn23hhL89pJGCqBQgl
Total errors: 5
Error list: ``[1421835, 1848854, 1942942, 1954900, 2015948]``

Due to #3502 I had to stop scanning last night.

**Comment by r888888888** [comment]
Updates for the 10th doc have been queued.

**Comment by r888888888** [comment]
Updates for the 11th doc have been queued.

**Comment by BrokenEagle** [comment]
IDs: 2674073..3002508
Total missing: 83
Missing list: [checkalliqdb.12.txt](https://github.com/r888888888/danbooru/files/1675013/checkalliqdb.12.txt)
Total errors: 3
Error list: ``[2745207, 2745208, 2965453]``

Since I finished scanning all of them, I'll scan the latest uploads once every week.  Also, this weekend I'll go back and rescan all of the error posts to see how the updates to them did.

**Comment by r888888888** [comment]
Updates for the 12th doc have been queued.

**Comment by r888888888** [comment]
Queued.

**Comment by nonamethanks** [comment]
Recently it seems there's been problems again with indexing. I haven't run any automatic tool yet because some of the posts BrokenEagle reported are still missing, but it does feel like there's some problem behind the scenes again.

Some examples I just noticed from the first page of my pixiv feed alone:
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=68098897
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=68094107
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=68098901 (which was very recently uploaded at the time of this post so might not be affected)

**Comment by evazion** [comment]
Looks like [post #3076793](https://danbooru.donmai.us/posts/3076793) is where indexing stopped. Maybe it was the switch to https:// thumbnails? It was working before that. I don't see why iqdbs wouldn't be able to handle https:// urls though.

**Comment by r888888888** [comment]
It's a typo in IQDBS i think.

**Comment by BrokenEagle** [comment]
IDs: 3080789..3123831
Total missing: 7
Missing list: ``[3084883, 3096771, 3096773, 3102182, 3103827, 3104795, 3120321]``

These are all of the posts since last time.  There weren't a lot of missing this time, and no errors.

**Comment by r888888888** [comment]
Synced.

**Comment by BrokenEagle** [comment]
New IDs: 3123831..3214855
Total missing: 1765
Total errors: 6
JSON Data: [checkalliqdb.13.txt](https://github.com/r888888888/danbooru/files/2264899/checkalliqdb.13.txt)

In addition to the above ID range, I also went back and checked all of the IDs that had issue before, which is why the numbers are much higher.  The JSON data has two parts, the ones that were merely missing are under the key "nomatcheslist", while those that have errors are under the key "notfoundlist".

**Comment by r888888888** [comment]
I've queued updates.

Are you saying these posts have already been mentioned in this thread? Did the updates not work?

**Comment by BrokenEagle** [comment]
New IDs: 3214855..3260114
Total missing: 2339
Total errors: 10
JSON Data: [checkalliqdb.14.txt](https://github.com/r888888888/danbooru/files/2407080/checkalliqdb.14.txt)

Same as before, I went back and checked all of the previous misses.  The file is also structured the same as before as well.

**Comment by BrokenEagle** [comment]
New IDs: 3260114..3347658
Total missing: 2339
Total errors: 10
JSON Data: [checkalliqdb.15.txt](https://github.com/r888888888/danbooru/files/2683039/checkalliqdb.15.txt)

Did the same as last time, however it appears like all of the misses are exactly the same as the last time. I'm guessing that the previous entry was never queued for updates?

**Comment by BrokenEagle** [comment]
New IDs: 3347658..3563653
Total missing: 2556
Total errors: 11
JSON Data: [checkalliqdbjson.16.txt](https://github.com/r888888888/danbooru/files/3387767/checkalliqdbjson.16.txt)

@r888888888 I finished the comprehensive scan as mentioned in issue #4098.

**Comment by r888888888** [comment]
I've queued updates.

**Comment by BrokenEagle** [comment]
New IDs: 3563653..3618633
Total missing: 2364
Total errors: 11
JSON Data: [checkalliqdbjson.17.txt](https://github.com/r888888888/danbooru/files/3589172/checkalliqdbjson.17.txt)

**Comment by evazion** [comment]
Reindexed posts. Note that some of these are flash files that aren't expected to be in iqdb.

**Comment by BrokenEagle** [comment]
Yeah, I was thinking that might be the case for some of them. I'll revise my script to remove those and stop processing those in the future.

**Comment by BrokenEagle** [comment]
Since over a day ago (~1.5 days, somewhere between post IDs 3706963-3707203), posts have stopped being indexed by IQDB.

**Comment by evazion** [comment]
Fixed. The SQS processor (the background process that ingests new posts) died because of a read timeout while connecting to Amazon SQS. I've configured it to auto-restart in the future.

**Comment by BrokenEagle** [comment]
I've loaded up [favgroup #1465](https://danbooru.donmai.us/favorite_groups/1465) and [favgroup #2491](https://danbooru.donmai.us/favorite_groups/2491) with around 10k+ posts that are missing an IQDB match (searching by post ID does not produce a match. I did a quick cursory glance through some of the pages and tested a few posts manually just to make sure that they were all good. The following is the JSON for the results as well.

- JSON Data: [checkalliqdbjson.18.txt](https://github.com/danbooru/danbooru/files/4149002/checkalliqdbjson.18.txt)

That isn't all of the missing posts either. I stopped checking at some point due to the high number, but also to get something reported here. I'll start checking again once the above images get reindexed.

**Comment by BrokenEagle** [comment]
@evazion I did a fresh scan on all of the 4M+ posts. The data this time is just a list.

- Range: 4181638..4000000
- Total missing: 42779
- JSON Data: [missingiqdb.4000000.json](https://cdn.discordapp.com/attachments/618878216815247372/772731033619529758/missingiqdb.4000000.json)
    - Post 4045857 is also missing, but it was initially reported as an error so it didn't make it to the above list.

So roughly 25% of the posts in the 4M+ range are missing IQDB results right now.

**Comment by BrokenEagle** [comment]
@evazion I did a fresh scan of the 3-4M posts.

- Range: 3000000..4000000
- Total missing: 9811
- JSON Data: [missingiqdb.3000000-4000000.json](https://cdn.discordapp.com/attachments/618878216815247372/779466274966077440/missingiqdb.3000000-4000000.json)

So around 1% of the posts in 3-4M range are missing IQDB results right now.

**Comment by BrokenEagle** [comment]
@evazion I did a fresh scan of the 2-3M posts.

- Range: 2000000..3000000
- Total missing: 404
- JSON Data: [missingiqdb.2000000-3000000.json](https://cdn.discordapp.com/attachments/618878216815247372/785937833981640735/missingiqdb.2000000-3000000.json)

So around 0.04% of the posts in 2-3M range are missing IQDB results right now.

**Comment by nonamethanks** [comment]
Now that mods can resend posts to IQDB I think this can finally be closed.

I have set up a script to scan the entire site and requeue all missing matches, and once it's caught up I'll set it to monitor new posts every X minutes.
