### ISSUE TITLE
Smarter thumbnail generation for videos

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#3400]
Sometimes we generate empty thumbnails for gif/webm/ugoira uploads. This happens when the first frame is solid black or solid white. We should choose a better frame when the first frame is empty.

Examples:

* https://danbooru.donmai.us/posts?tags=id:2804509 (mp4)
* https://danbooru.donmai.us/posts?tags=id:2447538 (gif)
* https://danbooru.donmai.us/posts?tags=id:2324613 (ugoira)

**Comment by r888888888** [comment]
Maybe the easiest way to do this is to just jump to the 10% mark. There are some interesting plugins for intelligently capturing screenshots but I'm not sure if they're accessible from the Ruby client.

**Comment by BrokenEagle** [comment]
If there's a simple way to detect a mostly solid color image, then that might be a better way to do it.  If the program detects that condition, then jump ahead in set intervals until that condition no longer occurs.

**Comment by lllusion3469** [comment]
Without going into creating multiple thumbnails and selecting the most fitting one FFMPEG already seems to provide 2 methods to select thumbnails [covered here](https://superuser.com/questions/538112/meaningful-thumbnails-for-a-video-using-ffmpeg)

I tried these methods for the first two posts in OP
* `$ ffmpeg -i $i -vf thumbnail -frames:v 1 $out.jpg`
* `$ ffmpeg -i $i -vf "select=gt(scene\,0.4)" -frames:v 1 $out.jpg`

The results:
* post 2804509 method 1:  ![2804509_thumb](https://user-images.githubusercontent.com/31420484/82682003-d994a100-9c4e-11ea-956e-d8adde55a80e.jpg)
* post 2804509 method 2:  ![2804509_gt0 4](https://user-images.githubusercontent.com/31420484/82682025-e0bbaf00-9c4e-11ea-9d77-f3bb1ddc6a0f.jpg)
* post 2447538 method 1:  ![2447538_thumb](https://user-images.githubusercontent.com/31420484/82682092-fd57e700-9c4e-11ea-9634-6198adddf57c.gif)
* post 2447538 method 2: didn't work, "Output file is empty, nothing was encoded"

And while this is certainly not perfect (for post 2804509 it's not particularly representative of the video) imo it's still a huge improvement over a solid black/white frame.

I'm probably going try dogfooding `-vf thumbnail`.

**Comment by evazion** [comment]
I experimented with various techniques but couldn't find anything consistently better than `-vf thumbnail`.

There's a chance this could generate worse, or at least different, thumbnails for ordinary videos that don't have a blank intro. We'll see. This may also ruin `thumbnail_surprise` GIFs and APNGs that rely on the thumbnail being the first frame.

https://github.com/rails/rails/pull/39096#issuecomment-860167448
https://superuser.com/questions/538112/meaningful-thumbnails-for-a-video-using-ffmpeg
