### ISSUE TITLE
Allow approvers to change rejection reason or approve a rejected post from the top bar

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#3470]
Currently it's not possible to add a detailed rejection reason after you have rejected a post, or to change your rejection option at all.  
Furthermore, due to the fact that all the buttons get removed from the top notice after a choice has been made, it's also not possible to approve a post from its top notice once if you have rejected it.

I realize a post can be reapproved through the sidebar button, but that can take quite a lot of scrolling for images with long tag lists - a good example of a recently controversial pic with this problem would be http://danbooru.donmai.us/posts/728304

**Comment by r888888888** [comment]
I assume you mean leaving a detailed reason after using one of the canned responses. Those disapprovals trigger nightly dmails so at a minimum I think any edits would have to be time gated so that you couldn't modify it after an hour or so.

I think approving after disapproving is an edge case. Are you clicking on it accidentally?

**Comment by nonamethanks** [comment]
One of the user cases would be adding a detailed response after a template rejection, yes.
As for rejecting and approving, posts live in the queue for three days, so it's not far-fetched to have a change of mind on them, especially in busy days and for less popular tags/copyrights (that most approvers mark as not interested). 

As for the second part, mine was more of an observation on the inconvenient position of the approval (after the above case) & undelete button, but I realize it's a fairly irrelevant and secondary problem given how rarely undeletion happens and given that users can edit its position via CSS.

**Comment by nonamethanks** [comment]
Another thing I've observed is that the disappearance of the top bar menu makes the Shift-O keybind stop working on those posts, likely because it's bound to the top menu's approve button, even though there's another on the sidebar.
