### ISSUE TITLE
Opening a post in a new tab on a mobile mode does not display the image

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#3537]
From the [Danbooru forum](http://danbooru.donmai.us/forum_posts/142755):

> Laethiel said:
> 
> On mobile (Android Chrome) but not on desktop (Windows 7, Firefox or Chrome), I'm having two issues.
> 
> ......
> 
> 2. If I open a post's page in a new tab, the image doesn't load until I refresh the page. Thumbnails due to parent/child posts load fine, and thumbnails on a search page opened in a new tab load fine, but the main image on a post page doesn't load if it's in a new tab. Opening a post page in the current tab loads the image properly without needing to refresh.
> 
> I think both of these issues started in the past few weeks.

I can replicate the above, but I don't know what's causing it.

**Comment by evazion** [comment]
Can't reproduce, assuming this is no longer an issue.
