### ISSUE TITLE
Change how email notifications are handled

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#3574]
Related to #3339 and #2886.  Discussed on Discord with @evazion.

It seemed to me that hitting the database on each page load to check for new DMail was wasteful on resources and causes unnecessary burden on the database.  One solution that evazion proposed which I also like is to add a ``unread_dmail_count`` field to the user model and update it upon Dmails being created, being read, or all being marked as read.

**Comment by BrokenEagle** [comment]
@r888888888 The **mark_all_as_read** action in the DMails controller didn't get addressed by the above commit.

https://github.com/r888888888/danbooru/blob/master/app/controllers/dmails_controller.rb#L51-L57

It should have `CurrentUser.user.unread_dmail_count = 0` before the  `CurrentUser.user.save`.

**Comment by evazion** [comment]
[forum #146561](https://danbooru.donmai.us/forum_topics/9127?page=236#forum_post_146561):

> I got a DMail and read it, but the (1) by "My Account" and by "Messages" wouldn't go away until I clicked "Mark all as read." I tried checking my spam folder, but there was nothing there.

Reopening because a few people have reported this problem.

**Comment by evazion** [comment]
Above bug may still be valid, requires more investigation.

**Comment by evazion** [comment]
I think this is fixed.
