### ISSUE TITLE
Allow selective DMails to be marked as read or unread from the index page

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#3575]
Every other email application out there has this, and it really hamstrings it's use.  For myself, I don't want to actually have to open up a mention to read it.  I know where to go just from the topic.  Additionally, after I read an email, there are times I'd like to mark it as unread as a visual reminder that I need to come back to it later.

**Comment by evazion** [comment]
Fixed in 6468df6d4, although currently it's still only possible to mark dmails as unread one at a time.
