### ISSUE TITLE
Incorrect sample sizes for old images

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#3578]
The sample image for [post #60830](https://danbooru.donmai.us/posts/60830) is 404x850 when it should be 850x1785. This causes it to be upscaled in the browser and look really bad.

Presumably at some point samples were generated with a max height of 850. Any such samples need to be regenerated.

**Comment by nonamethanks** [comment]
Closing this now, since I regenerated all the wrong sizes a while ago.
