### ISSUE TITLE
Broken Image Reporting

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#3610]
I figured I'd open an issue to track this.

Range checked: 0..711145
Broken thumbnails: 30
Broken samples: 1
Broken originals: 1
Broken dictionary: [checkallimage1.txt](https://github.com/r888888888/danbooru/files/1886667/checkallimage1.txt)

The above JSON file has 3 keys, "previewsize" (thumbnail), "samplesize" (850px version), "fullsize" (original version).  The keys under each of those is the post # and their value indicates which HTTP error code was returned.

**Comment by r888888888** [comment]
The `base_dir` parameter for the SFTP storage managers wasn't configured so replacements on the archives servers wasn't working. That should be fixed now. I've manually synced the files in 1.txt.

**Comment by BrokenEagle** [comment]
Range checked: 711145..1027186
Broken thumbnails: 0
Broken samples: 11
Broken originals: 11
Broken dictionary: [checkallimage2.txt](https://github.com/r888888888/danbooru/files/1950071/checkallimage2.txt)

Same format as before.  The broken samples and originals happen to all be from the same posts.

**Comment by r888888888** [comment]
2 has been synced.

**Comment by BrokenEagle** [comment]
Range checked: 1027186..1465992
Broken thumbnails: 0
Broken samples: 61
Broken originals: 61
Broken dictionary: [checkallimage.3.txt](https://github.com/r888888888/danbooru/files/1999079/checkallimage.3.txt)


Same format as before.  Like last time, the broken samples and originals happen to all be from the same posts.

**Comment by r888888888** [comment]
3 has been synced.

**Comment by BrokenEagle** [comment]
Range checked: 1465992..2293992
Broken thumbnails: 0
Broken samples: 527
Broken originals: 526
Broken dictionary: [checkallimage.4.txt](https://github.com/r888888888/danbooru/files/2095551/checkallimage.4.txt)

Unlike the previous times, there is actually a slight difference between the broken samples and originals.  In this case, post 1486035 has a broken sample image, but not a broken full image.  Besides that, all other  broken samples and originals happen to all be from the same posts.

**Comment by r888888888** [comment]
4 has been synced.

**Comment by BrokenEagle** [comment]
Range checked: 2293992..3196042
Broken thumbnails: 7
Broken samples: 8
Broken originals: 8
Broken dictionary: [checkallimage.5.txt](https://github.com/r888888888/danbooru/files/2216481/checkallimage.5.txt)

So not as many as last time, however this time none of the image size sets match with each other, as there are 1 or 2 post differences.

**Comment by r888888888** [comment]
2737344, 2770039 can't be found. The others were fixed.

**Comment by BrokenEagle** [comment]
Range checked: 3196042...3260255
Broken thumbnails: 6
Broken samples: 7
Broken originals: 6
Broken dictionary: [CheckAllImagesourcefileAsync.txt](https://github.com/r888888888/danbooru/files/2424920/CheckAllImagesourcefileAsync.txt)

Most of the broken images are the same as before.

>2737344, 2770039 can't be found. The others were fixed.

- 2737344: https://files.catbox.moe/r710il.jpg
- 2770039: https://gelbooru.com/images/3d/20/3d201a1f8a29df85769ce54c2986b357.png

Many/most of the broken images can be found at the other boorus. For the above, I just used the md5 of the original image on Danbooru plus the md5 metatag to find the above image.

**Comment by BrokenEagle** [comment]
I did another recent scan and also did a visual confirmation of the missing images.
Broken thumbnails: 6 ([favgroup #2491](https://danbooru.donmai.us/favorite_groups/2491))
Broken samples: 231 ([favgroup #2573](https://danbooru.donmai.us/favorite_groups/2573))
Broken originals: 8 ([favgroup #1465](https://danbooru.donmai.us/favorite_groups/1465))

The ones that still have working originals should be easy to fix, but the others may require downloading if the file still exists. If not, then those posts should be permanently deleted.

**Comment by nonamethanks** [comment]
I did a scan a while ago and fixed all the fixable ones, and replaced corrupted ones with images from gelbooru when it was possible. Closing this.
