### ISSUE TITLE
Rotate pictures based on metadata

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#3692]
Quick example: https://danbooru.donmai.us/posts/3105959

When the full size is opened in a separate tab in any modern browser or in an external image viewer, this picture is automatically rotated 90 degrees clockwise. 

Danbooru should automatically perform the correct rotation for thumbnails and previews/inline expanding.

**Comment by evazion** [comment]
Not sure what would be the best thing to do here. We can rotate the preview/sample, but that leaves the original image unrotated. Aside from being confusing, it could cause problems with notes if the sample and the original are rotated differently.

As far as I can tell, there's no foolproof way to make browsers rotate the image correctly. There's an [image-orientation](https://caniuse.com/#feat=css-image-orientation) property, but it's Firefox only. We could rotate it ourselves with e.g. `transform: rotate(90deg)`, but then it'd get double-rotated on browsers that *do* rotate correctly (mobile Safari does, according to that link).

**Comment by r888888888** [comment]
Doesn't vips do this automatically?

**Comment by lllusion3469** [comment]
If you _were_ willing to modify (autorot) the original, you'd obviously only want to if it's necessary.

Without adding extra dependencies - only using `ruby-vips` or the `vips` cmdline (not even imagemagick or exiftool), the only way I could find was this:
* autorot the thumbnail (you'd be processing it anyways) using [`:angle`](https://www.rubydoc.info/gems/ruby-vips/Vips%2FImage:autorot)
* this returns the angle the thumbnail was rotated by
* if it's not [`:d0`](https://www.rubydoc.info/gems/ruby-vips/Vips/Angle), autorot the original

Example (cmdline):
```
$ vips autorot --angle 3c589afa6a0ca3bb54bd639dc6760a0e.jpg autorot.jpg
((VipsAngle) VIPS_ANGLE_D90)
```
but with `ruby-vips`, there'd be no need to parse anything

**Comment by lllusion3469** [comment]
Apparently chrome and firefox have support for `image-orientation: from-image` now (which is even the default it seems): https://caniuse.com/#feat=css-image-orientation

So now the above link shows correctly _as original_ but the resized sample is still rotated by 90 degrees since neither autorot is used nor the exif data is kept.

**Comment by evazion** [comment]
I think this will probably break as much as it fixes. It looks like a lot of older images weren't actually meant to be rotated, they just have the Exif rotation flag by mistake. A couple examples:

* post #2174880 (90 degree clockwise rotation makes it upside-down)
* post #75441 (270 degree  clockwise rotation makes it sideways)
