### ISSUE TITLE
Include epilepsy_warning tag in default blacklist

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#3745]
From the [Danbooru forum](https://danbooru.donmai.us/forum_topics/15345):

> chinatsu said:
> I suggest hiding by default posts tagged with epilepsy warning as a service to those who may be affected.

> BrokenEagle98 said:
> That'd be difficult without specifically coding just for that tag. As an alternative, the default user blacklist can be updated to include epilepsy warning.

> kikimaru said:
> +1 to this.

In addition to the above, maybe also run a script that will modify any user's blacklist that is using the current default blacklist, to using the new default blacklist.

**Comment by chinatsu-chan** [comment]
> In addition to the above, maybe also run a script that will modify any user's blacklist that is using the current default blacklist, to using the new default blacklist.

And maybe a dmail prompt to every user letting them know the option is available to add?

**Comment by evazion** [comment]
Wontfix. This tag is rare enough that I don't think it deserves to be in the default blacklist. I also think the tag is heavily overused and most posts tagged with it don't deserve the tag.
