### ISSUE TITLE
User search function returning inconsistent statistics.

### ISSUE THREAD

**Issue by Skye000** [danbooru/danbooru#3884]
The [user search function](https://danbooru.donmai.us/users/search) seems to give incorrect statistics for most users, but I've only found it to give incorrect stats for uploads and notes, and not deleted uploads and tag edits.
[Example 1: LaC's statistics listed in a search for his username](https://danbooru.donmai.us/users?commit=Search&search%5Bname_matches%5D=LaC&search%5Border%5D=date&utf8=%E2%9C%93) list 83 uploads and 10334 notes, while [his profile](https://danbooru.donmai.us/users/7624) lists 84 uploads and 10132 notes.
[Example 2: RaisingK's statistics listed in a search for his username](https://danbooru.donmai.us/users?commit=Search&search%5Bname_matches%5D=RaisingK&search%5Border%5D=date&utf8=%E2%9C%93) list 33939 uploads and 11959 notes, while [his profile](https://danbooru.donmai.us/users/13506) lists 33930 posts and 11972 notes.

**Comment by evazion** [comment]
Pretty much all of the user statistics need to be regenerated due to past bugs.

**Comment by evazion** [comment]
Fixed in c09cd9e9fd919403fd903c2d8bd9a32f884da6d0 and 04d3a048362ad425bab44d2f11b3f55abb124f2f. All the `*_count` fields in the `users` table were regenerated, except for the `post_update_count`, which is currently difficult because post versions live in a separate database.
