### ISSUE TITLE
Allow to translate commentary from the upload page

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#3893]
I'm not sure if there's already an issue open for this, because this has been brought up many times before, but I couldn't find anything.

Basically, it'd be nice to be able to translate the commentary from the upload page, because this would save extra steps that can be quite tedious. Basically a "Translated commentary" expandable box.

A point could also be made to allow notes as well, but those are probably much more difficult to implement.

**Comment by BrokenEagle** [comment]
Fixed with #4259.
