### ISSUE TITLE
Various exceptions for some artist URLs from different sites

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#3918]
Got the following when trying to edit an artist ([artist #72332](https://danbooru.donmai.us/artists/72332)):
```
OAuth2::Error exception raised
app/logical/pawoo_api_client.rb:108:in `get'
app/logical/sources/strategies/pawoo.rb:94:in `block in api_response'
app/logical/sources/strategies/pawoo.rb:93:in `each'
app/logical/sources/strategies/pawoo.rb:93:in `api_response'
app/logical/sources/strategies/pawoo.rb:53:in `profile_url'
app/logical/sources/strategies/pawoo.rb:77:in `normalize_for_artist_finder'
app/models/artist_url.rb:39:in `normalize'
app/models/artist_url.rb:118:in `normalize'
app/controllers/artists_controller.rb:64:in `update'
```

**Comment by BrokenEagle** [comment]
Found another exception for [artist #71472](https://danbooru.donmai.us/artists/71472):

```
ArgumentError exception raised
absolute URL needed (not nil)
app/logical/sources/strategies/nijie.rb:114:in `page'
app/logical/sources/strategies/nijie.rb:56:in `profile_url'
app/logical/sources/strategies/base.rb:147:in `normalize_for_artist_finder'
app/logical/sources/strategies/base.rb:141:in `normalizable_for_artist_finder?'
app/models/artist_url.rb:38:in `normalize'
app/models/artist_url.rb:118:in `normalize'
app/models/artist.rb:186:in `block (2 levels) in save_urls'
app/models/artist.rb:185:in `map'
app/models/artist.rb:185:in `block in save_urls'
app/models/artist.rb:183:in `save_urls'
app/controllers/artists_controller.rb:64:in `update'
```

The exception occurred when trying to send the following list of urls:

> http://seiga.nicovideo.jp/manga/list?user_id=12609685
> http://nijie.info/members.php?id
> https://twitter.com/intent/user?user_id=165840275 
> http://www.nicovideo.jp/user/12609685
> http://seiga.nicovideo.jp/user/illust/12609685
> https://twitter.com/Cyorisukenosuke
> https://www.pixiv.net/stacc/tyotyotyori
> https://www.pixiv.net/member.php?id=910858
> -http://twitpic.com/photos/cyorisukenosuke

It looks like my scraper didn't parse that Nijie URL correctly, but that still shouldn't cause an exception.  When I remove that from the list of sent URLs, the edit change was able to go through.

**Comment by BrokenEagle** [comment]
[Artist #71358](https://danbooru.donmai.us/artists/71358) also has the same issue as above, although in this case, the partial Nijie URL was already there.

``http://nijie.info/index.php``

**Comment by BrokenEagle** [comment]
Looks like the above issue prevents the editing of those artists whatsoever.  I tried editing [artist #1234](https://danbooru.donmai.us/artists/117969) to remove the bad Nijie URL, and it still won't let me save, giving the same **ArgumentError** exception as before.

**Comment by BrokenEagle** [comment]
Encountered another exception for [artist #66240](https://danbooru.donmai.us/artists/66240).

```
NoMethodError exception raised
undefined method `user_id' for nil:NilClass

app/logical/sources/strategies/pixiv.rb:103:in `profile_url'
app/logical/sources/strategies/base.rb:147:in `normalize_for_artist_finder'
app/models/artist_url.rb:39:in `normalize'
app/models/artist_url.rb:118:in `normalize'
app/controllers/artists_controller.rb:64:in `update'
```
I originally thought it might be because of the novel link in the URL list, but even when removing it, it still errors out.

https://www.pixiv.net/stacc/mirak
https://www.pixiv.net/member.php?id=198624
http://www.pixiv.net/novel/show.php?id=360841

Though it might be because the Pixiv account 198624 is suspended, or the fact that the stacc link returns a 404, or both.

**Comment by r888888888** [comment]
I think you get that error if the account is inaccessible for whatever reason. It works for me with other accounts.

**Comment by BrokenEagle** [comment]
Issue brought up on [forum #153049](https://danbooru.donmai.us/forum_posts/153049).

The issue is with [post #3191675](https://danbooru.donmai.us/posts/3191675). It's giving the following Javascript error.
```
undefined method `to_h' for # Did you mean? to_s c
```
Not sure why though. Both the toot and the user account are both still good.

**Comment by BrokenEagle** [comment]
Just wanted to bring up that inactive Pawoo accounts (HTTP 410 Gone) still cause exceptions when trying to edit an existing artist with such links or adding such links to an artist.

I'm talking about links of the following type (which happens to give the above HTTP error):

https://pawoo.net/web/accounts/207618

Since this is still an issue, I want to still preserve that information somehow, so for now I'm munging the URL a bit so that the faulty Pawoo API doesn't freak out anymore.

https://pawoo-net/web/accounts/207618

Hopefully the Pawoo URL processor will get fixed though, so that it will no longer be an issue.
