### ISSUE TITLE
Nijie issues

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#3919]
- [x] Don't crash on invalid urls (#3918).
- [x] Don't crash on deleted works ([bad_nijie_id](https://danbooru.donmai.us/posts?tags=bad_nijie_id)).
- [x] Get artist id from image url to support artist finder for deleted works.
- [x] Rewrite all types of thumbails to full size.
- [x] Support preview_urls.
- [ ] Support doujin uploads (http://nijie.info/dojin_all_view.php).
- [x] Cache http requests with `HttpartyCache`.

**Comment by BrokenEagle** [comment]
Related to issue #3918.
