### ISSUE TITLE
Parent/child posts are picked up by DanbooruBot as underused tags

### ISSUE THREAD

**Issue by AngryZapdos** [danbooru/danbooru#3966]
![screen shot 2018-11-01 at 9 45 52 pm](https://user-images.githubusercontent.com/44669781/47848836-aba8fb00-de23-11e8-821c-6332b862a6d4.png)

**Comment by evazion** [comment]
The underused tags notification was removed in https://github.com/evazion/reportbooru/commit/1be2cb24787a5826444e9586e44523637c066487.
