### ISSUE TITLE
Artist tag in upload page should account for aliases

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4017]
Example: [this upload page](https://danbooru.donmai.us/uploads/new?url=https%3A%2F%2Fpbs.twimg.com%2Fmedia%2FDqawN-uWsAACNDT.jpg%3Aorig&ref=https%3A%2F%2Ftwitter.com%2Fterupancake%2Fstatus%2F1055726113643790337) displays both https://danbooru.donmai.us/artists/119211 and https://danbooru.donmai.us/artists/178392 as artist tags.

**Comment by BrokenEagle** [comment]
Either that, or delete the artist. That's what I've usually done.

**Comment by nonamethanks** [comment]
Well, the problem with that is that it requires manual intervention every time there's a similar case.

Ideally we'd want aliased artist tags to have their artist entry automatically deleted.

**Comment by BrokenEagle** [comment]
Yeah, that's what I meant. Automatically delete the artist entries for aliased tags. If the consequent has an artist entry but the antecedent doesn't, then automatically rename it instead.

**Comment by nonamethanks** [comment]
Now that I think of it, there should also be an automatic merging of similar names and URLs by danboorubot, to make sure nothing gets lost.

**Comment by evazion** [comment]
Artist entries are already automatically renamed when the alias is approved, but here the user manually copy-and-pasted the artist entry before the alias was approved and didn't delete the old artist afterwards.

I'd say the alias should have failed when it couldn't move the old artist entry.

**Comment by evazion** [comment]
Resolution: make tag aliases fail instead of silently ignoring it when they can't move the artist entry.

**Comment by evazion** [comment]
Fixed by making it so aliased tags can't have artist entries.

This was addressed earlier by making it so aliases would move artist entries, but there were about 230 existing artist entries for aliased tags, of which ~50 were active. Added a fix script to move these artist entries.
