### ISSUE TITLE
Are ArtStation profile links normalized incorrectly?

### ISSUE THREAD

**Issue by 7nik** [danbooru/danbooru#4021]
I know that there are three schemes of ArtStation profile links:
```
https://<artist_name>.artstation.com/
https://www.artstation.com/<artist_name>
https://www.artstation.com/artist/<artist_name> (obsolete, redirects to previous one)
```

And recently I noticed that artist search by profile link doesn't work for all of them and for different artists I got different set of working schemes.

Artist | `<artist_name>.artstation.com/` | `www.artstation.com/<artist_name>`  | `www.artstation.com/artist/<artist_name>` 
--- | ----- | ---- | ---
[jasper_sandner](https://danbooru.donmai.us/artists/180196) | hasn't, fail | has, success | hasn't fail
[lukas_klaudat](https://danbooru.donmai.us/artists/180158) | has, success | has, success | hasn't, fail
[paul_kwon](https://danbooru.donmai.us/artists/20675) | hasn't, success | has, fail | hasn't, fail
[gyn_ryo](https://danbooru.donmai.us/artists/179923) | has, success | has, success | hasn't, fail
[tinadraw](https://danbooru.donmai.us/artists/179808) | hasn't, fail | has, success | hasn't, fail
[krit_parnsanay](https://danbooru.donmai.us/artists/179740) | hasn't, fail | has, success | hasn't, fail
[111](https://danbooru.donmai.us/artists/178721) | has, fail | hasn't, success | hasn't, fail
[regiana_(jubi)](https://danbooru.donmai.us/artists/152663) | has, success | hasn't, fail | has, success
[tim_loechner](https://danbooru.donmai.us/artists/4369) | has, fail | han't, success | has, fail
[dcwj](https://danbooru.donmai.us/artists/15620) | has, fail | hasn't, success | has, fail
[nax](https://danbooru.donmai.us/artists/44479) | hasn't, fail | hasn't, fail | has, success
[rotix](https://danbooru.donmai.us/artists/48752) | hasn't, fail | hasn't, success | has, fail

has/hasn't — does an artist profile include ArtStation link of such scheme;
fail/success — search result by ArtStation link of such scheme.

As you can see we can't use any of the schemes to check do we already have an artist.

**Comment by r888888888** [comment]
haha well i don't know if ca7c56f fixes this, but it shores up searches on non-project urls.

**Comment by 7nik** [comment]
Well, this fix did not solve the problem. Though, looks like it became a little better.
I checked all 1328 artist with ArtStation links and got the following results:
search by `https://www.artstation.com/artist/<artist_name>` always fails;
search by `https://www.artstation.com/<artist_name>` finds 94% of the artists;
`https://<artist_name>.artstation.com/` — 32%.
Also, 19 (1.43%) artists were not found by any of the URL schemas, 5 of them due to lack of `www` in the URLs.

**Comment by evazion** [comment]
As of 04c03fa4e614c157928765bed0c4460155f5542f and 10dac3ee51b7a3140b55dd24471a4eb8f779787f, ArtStation URLs are all normalized to `https://www.artstation.com/<artist_name>` form. Searching for any of these forms should work.
