### ISSUE TITLE
Mass updating is broken

### ISSUE THREAD

**Issue by Type-kun** [danbooru/danbooru#4025]
There's definitely more issues with mass updating the tags than I've noticed in issue #4024. See https://danbooru.donmai.us/bulk_update_requests?search%5Bid%5D=1847 - not only it didn't create any mod actions corresponding to the mass updates, it also didn't move wikis and failed the post updates midway, despite resetting the tag counts to 0 for antecedent tags. I'm not sure what happened since the errors, if any, don't seem to be logged anywhere.

**Comment by Type-kun** [comment]
I've run the batch updates again, so the posts are all moved, but the issue remains.

**Comment by Type-kun** [comment]
By the way, can we make bulk updates understand things like `pool:` metatag in consequent string? It seems to traverse the posts sequentially anyway, we might as well use the full potential offered by the model.

**Comment by evazion** [comment]
Haven't noticed any problems with mass updates lately.
