### ISSUE TITLE
Link in "Create a new tag with artist:<artist_name>. " alert now redirects to empty wiki page

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4029]
~That link in the notice which shows up when you upload a post without artist tags used to open a precompiled form for artist creation. Now it redirects to https://danbooru.donmai.us/wiki_pages/show_or_new?title=artist%3A%3Cartist_name%3E~

**Comment by evazion** [comment]
I've seen other people get confused by this. Updated the message to link to the create new artist form instead.
