### ISSUE TITLE
Animated_gif tag not added to preprocessed uploads

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#4041]
Animated gifs don't get the animated_gif tag added when they're uploaded via a preprocessed upload.

https://github.com/r888888888/danbooru/blob/844b1a81bae29a55cd312453b0288b143792d614/app/logical/upload_service/preprocessor.rb#L91-L103

Automatic tags are added to the tag_string inside `Utils.process_file`, but the tag_string gets clobbered right after that.

**Comment by nonamethanks** [comment]
To mitigate the issue I've set a bot to automatically monitor new gif posts and add animated_gif where necessary, since it was recently reported again on discord.
