### ISSUE TITLE
Address the abuse of the detailed rejection messages

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4045]
From Danbooru [topic #15897](https://danbooru.donmai.us/forum_topics/15897).

> I realise it's a mod-only action, but this "Someone has commented on your uploads" message is really open to abuse.
> 
> If you want to comment on someone's uploads, there's a comments section and direct mentions feature using @.
> 
> Using DanbooruBot to anonymously comment is gross abuse of power.

Seems like an unscrupulous user is using the detailed rejection messages to send nasty messages to the user, and since the source of those messages is anonymous (sent by DanbooruBot), they remove all attribution to themselves.

Additionally, there currently isn't any way for moderators to discover the attribution of those detailed messages, and thus there is no way for that system to be properly moderated against abuse.

At the very least, make those detailed rejection messages and their attribution available and visible to moderators, but only if that moderator was not the uploader.

**Comment by evazion** [comment]
I think users just don't understand that how detailed rejections work. Approvers don't realize that their rejection messages are dmailed to uploaders as feedback, and uploaders don't realize that these dmails are coming from rejection messages left by approvers.

**Comment by BrokenEagle** [comment]
Since disapproval messages are now viewable by all, and moderators can see the name for any post disapproval, this should no longer be an issue. I'm closing it for now.
