### ISSUE TITLE
Facilitate variable results returned for autocomplete

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4121]
I recently added a setting to my IndexedAutocomplete script which facilitates variable results being shown (5-20) in the autocomplete popup ([topic #14701](https://danbooru.donmai.us/forum_topics/14701)). This affects all of the endpoints except for the autocomplete endpoint since that doesn't have a limit option.

1. Would it be possible to add a limit?
2. Would it need to be restricted by member level?
3. Would it need to have it's own maximum, something like 20 - 30?
4. How would it be handled with Builder+ that has a set amount returned from each matching category (exact,prefix,alias,correction)?
5. Could the counts for those sources be settable as well?
6. Would each source need to have it's own maximum, depending on the computation cost?

The overly maximum would be partly to avoid overtaxing the system, but also because it would start overflowing beyond the borders of the screen. The following is what it looks like with the users input when 20 results are returned.

![image](https://user-images.githubusercontent.com/21149935/62485350-4fd41f80-b771-11e9-8016-da9c8adecb05.png)

**Comment by evazion** [comment]
This is doable but the autocomplete code will need some refactoring first.

**Comment by evazion** [comment]
Partly fixed in 378559ff47250fa44c1dbbc755d2dba550a63f2a. Depends on #4211 to make it configurable for tags.

**Comment by BrokenEagle** [comment]
Already fixed.
