### ISSUE TITLE
Eliminate pool_string field from posts

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#4160]
The `pool_string` field is used for a couple things:

* Performing `pool:<name>` searches.
* Getting the list of pools on the post show page.

Both of these things can be achieved in other ways. Keeping the `pool_string` on `posts` in sync with the `post_ids` on `pools` is complex and historically has been a source of bugs. Eliminating the pool string avoids these problems entirely.

This will be a breaking change to the API, since it means dropping the `pool_string` field from `/posts.json`. An alternative will have to be provided before this can be completely dropped.

This also means dropping the `data-pools` attribute from thumbnails, meaning `pool:<id>` blacklists will no longer be supported. Very few people ever used this, so keeping the pool_string around for this isn't worth it.

**Comment by BrokenEagle** [comment]
I don't use it myself except as part of my BetterSavedSearches script, but it might be better to migrate those to metatag type searches instead given that pools usually get added to posts after the first hour anyways.

**Comment by evazion** [comment]
This was finally finished in e8c52432a4bac02c68a553847f85311ef8b337d8.
