### ISSUE TITLE
Make search results return zero results for mutually exclusive metatag search terms

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4161]
Brought up by @bipface on Discord, but the current methodology of processing exclusive metatag search terms doesn't make sense. The current setup just returns the last metatag search term that was used, whereas it would make more sense to return zero results.

For example:

```
score:1 score:3
```

Those are mutually exclusive, and so should return zero results, but instead return ``score:3`` which confuses a lot of users. Also, as pointed out by bipface, the other boorus return zero results in that situation.

Accounting for these situations might actually lighten server load for these types of queries. Instead of actually querying the database, just use internal logic to identify when one of these occurs and then stop processing and do an early bail returning zero results. That way the database doesn't even have to be queried (any more).

**Comment by evazion** [comment]
Fixed in a number of commits in https://github.com/danbooru/danbooru/compare/production-2020.04.07-210132-utc...production-2020.04.28-064048-utc.
