### ISSUE TITLE
Checkboxes remaining checked after submit on Add Commentary

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4179]
Brought up by @Unbreaky on Discord. Basically, when pressing the submit button for the Add Commentary dialog, the page refreshes but the boxes remain checked. A hard page refresh (Ctrl + F5) was required to clear the checkboxes upon page refresh. From my own testing, this behavior only seems to happen on Firefox.

**Comment by evazion** [comment]
https://stackoverflow.com/questions/7377301/firefox-keeps-form-data-on-reload
https://stackoverflow.com/questions/2486474/preventing-firefox-from-remembering-the-input-value-on-refresh-with-meta-tag

This appears to be part of the same issue as #4162. Firefox apparently remembers form values by default unless you explicitly disable it with `autocomplete="off"`.
