### ISSUE TITLE
Add API data to HTML

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4182]
On many pages data has to be scraped from rendered IDs or classes in order to get information needed like in a userscript. This is very tenuous as any change to site HTML structure can break things.

This could be done simply by adding a hidden HTML structure that contains the JSON text. Then ensure that the ID is on the rendered HTML elements. For tables, this would probably be best on the `<tr>` elements with something like `data-id="INSTANCEID"`.

**Comment by BrokenEagle** [comment]
Just started to work on this. I'll be starting out by only adding the ID fields.

**Comment by evazion** [comment]
See commits 1ce9eff0f5bde8cabd698fc4c2f2a89e07ccf074, 5afac29693a25ec7b7fe5cf34859b2aa0eed43a5, and be5df3732836a5a9a68b1a0f7c0c36822dd182fd. I planned to handle this by converting tables to use `table_for` and having it generate ids for rows.
