### ISSUE TITLE
Source links for Hentai-Foundry directing to broken HTTPS

### ISSUE THREAD

**Issue by Kikimaru** [danbooru/danbooru#4191]
Hentai-Foundry's HTTPS seems to not work, causing source links from Danbooru to display a broken site.

**Comment by lllusion3469** [comment]
Their certificate expired on 2019-10-05 and they haven't installed their new one to `img.hentai-foundry.com` (which hosts their css and js) (among other subdomains) yet. From the few I've tested, only `www.hentai-foundry.com` has the new one (valid since 2019-09-05).

**Comment by evazion** [comment]
Looks to be working now. Anyway, if their https is broken then that's their problem to fix.
