### ISSUE TITLE
Invalid URL links allowed on artist pages

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4192]
Noticed this issue on the following artist:

https://danbooru.donmai.us/artists/188558

One of the URLs there is:

```
https://https://acrux808.tumblr.com/
```

I was able to perform a save on that artist without changing anything, which means that it still accepts that URL as valid

So URLs should probably be validated. For instance, in the hostname portion, nothing but word characters, periods or dashes should be allowed. I know that the port number can be specified with a colon, but none of the links we should be accepting should have them.

I'm not sure if there are any restrictions for the pathname portion, but if there are, then those should be checked as well.

**Comment by evazion** [comment]
Another case:

https://danbooru.donmai.us/artists/167295
https://twitter.com/intent/use​r?user_id=2685107059

Here the user somehow inserted a zero-width space character between the `e` and `r` in the first `user`.
