### ISSUE TITLE
Deleted results differ between API and HTML

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4195]
Brought up by @Nikey646 on Discord. Basically, results returned through the API differ from those returned in HTML. In the API, it correctly returns deleted results when the deleted posts filter is off. With HTML, it incorrectly doesn't show results even when the filter is off.

Compare:
- https://danbooru.donmai.us/posts?tags=jav
- https://danbooru.donmai.us/posts.json?tags=jav

**Comment by evazion** [comment]
I'd say the bug is that `hide_deleted_posts` applies to the API when it shouldn't. This option was originally intended for the HTML, not necessarily for the API.
