### ISSUE TITLE
Unify autocomplete for Builders and Members

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#4211]
Builders and Members currently have different autocomplete systems. They're different because a new autocomplete system was made some time ago and it was rolled out to Builders for testing, but the rollout was never finished.

A couple things need to be changed first before rolling it out to Members:

* Ranking needs to be changed so that autocorrect results don't rank above normal results.
* Shortcut abbreviations need be prefixed with `/`. Ex: type `/lav` for `looking_at_viewer`, not `lav`. This is to avoid the case where you type `lav` wanting `lavender_hair` but instead unexpectedly get `looking_at_viewer`.

The above features create too many situations where the top result is not what you expected. They need to be changed to avoid confusion when autocomplete is rolled out to all users.

**Comment by nonamethanks** [comment]
Closing this since it should have been fixed by the autocomplete rework of a while ago. I don't see any reference to user levels in the autocomplete service anymore either.
