### ISSUE TITLE
Uploading from Tumblr is broken

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4220]
### 1. Bookmarklet

First, when using the batch bookmarklet, only the first image gets shown no matter which thumbnail gets clicked.

- First image:
     - Image: https://66.media.tumblr.com/f58ab193a4667ac542fd2e2a12bb59ad/178f9d6ee3dd6317-11/s640x960/67a2db1c2c3052ecfe0b1f6835f8008a52b81b08.png
    - Upload: https://danbooru.donmai.us/uploads/new?ref=https%3A%2F%2Fmityubi.tumblr.com%2Fpost%2F188587206906%2Ferika-itsumi-girls-und-panzer&url=https%3A%2F%2F66.media.tumblr.com%2Ff58ab193a4667ac542fd2e2a12bb59ad%2F178f9d6ee3dd6317-11%2Fs640x960%2F67a2db1c2c3052ecfe0b1f6835f8008a52b81b08.png
- Second image:
    - Image: https://66.media.tumblr.com/29eade21bc572dd895dd5d1779ff8411/178f9d6ee3dd6317-1a/s1280x1920/9e8c6b5ed0ee0240436c22b59446f7514a225a1c.png
    - Upload: https://danbooru.donmai.us/uploads/new?ref=https%3A%2F%2Fmityubi.tumblr.com%2Fpost%2F188587206906%2Ferika-itsumi-girls-und-panzer&url=https%3A%2F%2F66.media.tumblr.com%2F29eade21bc572dd895dd5d1779ff8411%2F178f9d6ee3dd6317-1a%2Fs1280x1920%2F9e8c6b5ed0ee0240436c22b59446f7514a225a1c.png

When using the post bookmarklet from the image itself, no image gets shown.

- 1st Upload: https://danbooru.donmai.us/uploads/new?url=https%3A%2F%2F66.media.tumblr.com%2Ff58ab193a4667ac542fd2e2a12bb59ad%2F178f9d6ee3dd6317-11%2Fs640x960%2F67a2db1c2c3052ecfe0b1f6835f8008a52b81b08.png&ref=
- 2nd Upload: https://danbooru.donmai.us/uploads/new?url=https%3A%2F%2F66.media.tumblr.com%2F29eade21bc572dd895dd5d1779ff8411%2F178f9d6ee3dd6317-1a%2Fs1280x1920%2F9e8c6b5ed0ee0240436c22b59446f7514a225a1c.png&ref=

### 2. IQDB

IQDB gives an error when visiting that page.

- IQDB URL: https://danbooru.donmai.us/iqdb_queries.json?limit=5&search%5Burl%5D=https%3A%2F%2F66.media.tumblr.com%2F29eade21bc572dd895dd5d1779ff8411%2F178f9d6ee3dd6317-1a%2Fs1280x1920%2F9e8c6b5ed0ee0240436c22b59446f7514a225a1c.png&search%5Bsimilarity%5D=50&search%5Bhigh_similarity%5D=65
- Error:
```json
{
  "success": false,
  "message": "bad argument (expected URI object or URI string)",
  "backtrace": [
    "app/logical/downloads/file.rb:45:in `http_get_streaming'",
    "app/logical/downloads/file.rb:31:in `block in download!'",
    "app/logical/downloads/file.rb:30:in `download!'",
    "app/logical/iqdb_proxy.rb:10:in `download'",
    "app/logical/iqdb_proxy.rb:25:in `search'",
    "app/controllers/iqdb_queries_controller.rb:8:in `show'"
  ]
}
```

For now, I think I'll just play it safe and upload from disk, then set the source afterwards.

**Comment by evazion** [comment]
Looks like Tumblr is using new image urls for new posts:

```
New: 
https://emlan.tumblr.com/post/189469423572
https://66.media.tumblr.com/168dabd09d5ad69eb5fedcf94c45c31a/3dbfaec9b9e0c2e3-72/s640x960/bf33a1324f3f36d2dc64f011bfeab4867da62bc8.png
https://66.media.tumblr.com/5a2c3fe25c977e2281392752ab971c90/3dbfaec9b9e0c2e3-92/s500x750/4f92bbaaf95c0b4e7970e62b1d2e1415859dd659.png

Old:
https://marmaladica.tumblr.com/post/188237914346
https://66.media.tumblr.com/2c6f55531618b4335c67e29157f5c1fc/tumblr_pz4a44xdVj1ssucdno1_1280.png
https://66.media.tumblr.com/11700cab20d65d5a6acc470e284dbd3a/tumblr_pz4a44xdVj1ssucdno2_1280.png
```

I haven't experimented with whether it's possible to rewrite these URLs to get larger images.
