### ISSUE TITLE
Accounts with expired bans are still banned

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4221]
Noticed this with the autoban on spambots, but it probably applies to all bans as well.

Example:
- User: https://danbooru.donmai.us/users/716301
- Ban: https://danbooru.donmai.us/bans/5701

That's expired ban is the only one currently for that account.

https://danbooru.donmai.us/bans?search[user_id]=716301

**Comment by BrokenEagle** [comment]
This doesn't seem to be an issue anymore. Was this fixed, or is it still an issue?

**Comment by evazion** [comment]
This was fixed by c95108d37b4102a8b3d7d756f34628a137021ee4. One of the daily maintenance tasks was failing and it prevented the other tasks from running.
