### ISSUE TITLE
unrecognized configuration parameter "default_table_access_method"

### ISSUE THREAD

**Issue by thenamewastaken** [danbooru/danbooru#4222]
On a fresh install, cloned at commit cb45aa6, running `bundle exec rake db:setup` to create the database aborts with the error in the title.
The database is created, but anything else is never executed.
The system is Debian 10. I ran `apt update` and `apt dist-upgrade` before starting the installation process.
Full error message:
```
psql:/home/vanni/danbooru/danbooru/db/structure.sql:401: ERROR:  unrecognized configuration parameter "default_table_access_method"
rake aborted!
failed to execute:
psql -v ON_ERROR_STOP=1 -q -X -f /home/vanni/danbooru/danbooru/db/structure.sql danbooru2

Please check the output above for any errors and make sure that `psql` is installed in your PATH and has proper permissions.

/home/vanni/.rbenv/versions/2.6.3/bin/bundle:23:in `load'
/home/vanni/.rbenv/versions/2.6.3/bin/bundle:23:in `<main>'
Tasks: TOP => db:structure:load
(See full trace by running task with --trace)
```
(Don't mind the fact that the user running the commands is not "danbooru", it's a virtual machine and I'm using the user I created when installing the OS.)

**Comment by evazion** [comment]
This was a Postgres 12 option that accidentally slipped in. Note that `db:create db:migrate` is preferred over `db:setup` because it's less prone to issues like this.
