### ISSUE TITLE
testbooru is down

### ISSUE THREAD

**Issue by xeron** [danbooru/danbooru#4233]
`testbooru.donmai.us` doesn't work, doesn't even resolve.

**Comment by evazion** [comment]
It's back up. It was taken down as part of a server migration.

**Comment by xeron** [comment]
@evazion thanks! But testbooru returns `401 "Unauthorized"` now similar to main danbooru when trying to make API requests without authentication. It used to work so it was good for automated testing, but now it needs user credentials.
