### ISSUE TITLE
Embedded notes improvements

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4235]
There have been several discussions on Discord about how to improve embedded notes. That way the translator could decide how they want each item to look on the post

1. No resize icon unless hovering

    This can often get in the way of the text.

2. No borders

    Borders interfere with having a seamless integration of the note on the post. This can be currently hacked with CSS, although it would be preferable if this was just the default for embedded notes.

3. Full opacity

    Same as above.

4. Settable background color

    Same as above.

5. Alternate shapes

    Such as circles, ovals, trapezoids, and  parallelograms.
    https://www.w3schools.com/howto/howto_css_shapes.asp

6. Custom shapes

   I.e. drawn by the user. This one might be the hardest to do, so it would be more of a stretch goal.

1 above should always be on for embedded notes. 2 and 3 could be a note setting instead of always on, 4-6 would have to be a note setting.

**Comment by BrokenEagle** [comment]
Here's another consideration which would be more of a stretch goal.

7. Have the font-size scale with the image size

    Much like how the note boxes scale with the image size. The easiest way to accomplish this would be to normalize all usage of `font-size` to use percentages instead of `px`, `em`, or the deprecated `size=` attributes. Then, all of the text-sizes of each element in the note container could be simultaneously adjusted by changing the font size base of the outer container of each note box.

    Normalizing notes, both past and going forward, would be the most difficult aspect of this task item. If this sounds like something that might get done though, I could do the legwork of converting all past notes to using percentages, and then share the algorithm used to be added to the conversion of notes that get saved.

**Comment by BrokenEagle** [comment]
I'm working on a prototype userscript right now which will test out various ways to do the above. Once stable I'll port it over to the note Javascript module.

**Comment by evazion** [comment]
I just want to say, I want to be careful about introducing too much complexity here. The Javascript is already pretty complex, it has no test suite, and we've got 15 years of old notes to maintain compatibility with.

> Have the font-size scale with the image size

> Much like how the note boxes scale with the image size. The easiest way to accomplish this would be to normalize all usage of font-size to use percentages instead of px, em, or the deprecated size= attributes. 

I think the cleanest way to do this would be to normalize notes server-side by rewriting the CSS inside `NoteSanitizer`. We're already doing this to fix certain things in the HTML. The idea would be to use [sanitize](https://github.com/rgrove/sanitize) to parse the `style` and `size` attributes, then use [crass](https://github.com/rgrove/crass) to parse the CSS strings and rewrite the `font-size` attributes.

This may not necessarily be easy though. It's not just `font-size`, there are other related attributes like `line-height` and `text-shadow` (and probably more) that might also need to be changed if the base font size changes.

`> Then, all of the text-sizes of each element in the note container could be simultaneously adjusted by changing the font size base of the outer container of each note box.`

This could be done by just setting `font-size` on the `#note-container`. Then all the note boxes would inherit it at the same time. Doing this inside `Note.Box.scale_all()` when notes are rescaled would probably be the easiest way.

**Comment by BrokenEagle** [comment]
Wouldn't it be better to have the client machines do the processing to take the load off the server? Plus Ruby is slower than the browser's Javascript.

> Crass isn't terribly fast. I mean, it's Ruby, and it's not really slow by Ruby standards. But compared to the CSS parser in your average browser? Yeah, it's slow.
> https://github.com/rgrove/crass#problems

Also, the prototype I developed with a Gist ([EmbeddedNotesImprovements](https://gist.github.com/BrokenEagle/3b76e849ad50614ecbc917d2651bfe33)) is only around 300 lines long. However, much of that is just because it's acting outside the actual site Javascript, and much of that can be removed once things get incorporated into the site's code.

Additionally, doing it server side would require being able to interpret every single available unit (https://www.w3schools.com/cssref/css_units.asp), which is a difficult task at best, especially since some of the values are browser dependent. Then it would all have to be converted to a %, which would be very difficult since percentages can stack, so it would require keeping track of things going top to bottom. However, doing it with the browser, it only requires using the `window.getComputedStyle` function which already normalizes everything to the **px** unit.
