### ISSUE TITLE
`only=…` param malfunctioning on autocomplete API

### ISSUE THREAD

**Issue by bipface** [danbooru/danbooru#4240]
when the `only=…` parameter is used with the `/tags/autocomplete.json` API it seems to remove every field from the results; example:

[/tags/autocomplete.json?limit=1&search[name_matches]=toujou_&only=name](https://danbooru.donmai.us/tags/autocomplete.json?limit=1&search[name_matches]=toujou_&only=name)
```
→ [{}]
```

compare with the `/tags.json` API which has the same result structure:

[/tags.json?limit=1&search[name]=toujou_nozomi&only=name](https://danbooru.donmai.us/tags.json?limit=1&search[name]=toujou_nozomi&only=name)
```
→ [{"name":"toujou_nozomi"}]
```

**Comment by BrokenEagle** [comment]
I'm not sure if this is actually a bug or not, as the **only** parameter was intended to work on application record endpoints, i.e. the show and index actions.

**Comment by bipface** [comment]
i think i'd consider it a bug in any case — if it's not supported it should have no effect
rather than… an adverse effect
