### ISSUE TITLE
Approving a post then editing tags returns 404

### ISSUE THREAD

**Issue by OOZ662** [danbooru/danbooru#4241]
Any time I approve a post then edit the tags (generally by pressing Shift+E on the post), submitting them directs to a 404 page and no changes are made to the post past the approval. Passing the changed tag list to someone else, they can make the edit. Returning a few minutes later seems to allow edits to be made.

Only userscript in use is Danbooru - Miscellaneous Tweaks next to a single CSS block to change the tagging smileys to Google Blobs.

**Comment by Unbreaky** [comment]
Just wanna mention that this only happens if you approve the post on the post page and then tries to add tags without leaving the page, forcing a reload of the page with CTRL + F5 allows tags to be added but it's cumbersome to have to do every time.

**Comment by evazion** [comment]
I'm not able to reproduce this. Steps taken:

* Click 'approve' in the top menu.
* Press Shift+E.
* Add a tag.
* Press enter.

**Comment by Unbreaky** [comment]
Yeah, that's how it happens, it leads to a page saying 

> That page does not exist

> Return to index

I'm using Firefox 72.0 if it matters.
