### ISSUE TITLE
Exception when using Twitter video image links

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4262]
Brought up by @fredgido in Discord.

Image link: https://pbs.twimg.com/tweet_video_thumb/EOR1wusXUAExEMW.jpg:orig
Error: **NoMethodError - undefined method `hostname' for nil:NilClass**
> app/logical/downloads/file.rb:97:in `is_cloudflare?'
app/logical/downloads/file.rb:66:in `uncached_url'
app/logical/downloads/file.rb:31:in `download!'
app/logical/upload_service/utils.rb:187:in `get_file_for_upload'
app/logical/upload_service/preprocessor.rb:93:in `start!'
app/logical/upload_service/preprocessor.rb:63:in `block in delayed_start'
app/logical/current_user.rb:10:in `scoped'
app/logical/current_user.rb:24:in `as'
app/logical/upload_service/preprocessor.rb:62:in `delayed_start'
app/jobs/upload_preprocessor_delayed_start_job.rb:6:in `perform'

This also affects doing IQDB searches, such as what is done by [NTISAS](https://github.com/BrokenEagle/JavaScripts/blob/master/New_Twitter_Image_Searches_and_Stuff.user.js).

**Comment by fredgido** [comment]
https://danbooru.donmai.us/iqdb_queries?url=https://pbs.twimg.com/tweet_video_thumb/EOtRt-6U8AEW0gt.jpg:orig
nor fixed

**Comment by BrokenEagle** [comment]
I have also verified from the above that this is still an issue.

**Comment by BrokenEagle** [comment]
There are two more video thumbnail formats that aren't accounted for and currently generate exceptions.

- `^https://pbs\.twimg\.com/ext_tw_video_thumb/(\d+)/(\w+)/img/([^.?]+)`

Example: https://danbooru.donmai.us/iqdb_queries.json?url=https%3A%2F%2Fpbs.twimg.com%2Fext_tw_video_thumb%2F1243725361986375680%2Fpu%2Fimg%2FJDA7g7lcw7wK-PIv.jpg

- `^https://pbs\.twimg\.com/amplify_video_thumb/(\d+)/img/([^.?]+)`

I don't have an example of this one offhand, but I've encountered it before and added it to my NTISAS userscript's list of handled images.
