### ISSUE TITLE
Very long tags break forum post format

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4279]
https://danbooru.donmai.us/forum_topics/15484#forum_post_152334
![image](https://user-images.githubusercontent.com/12946050/73600944-71fbfe00-4558-11ea-97cc-55d1e22ad27e.png)

**Comment by msaba92** [comment]
Seems this is caused by long strings without white space in general. For example, on resolutions with small width it can be replicated with https://danbooru.donmai.us/posts/3770857#comment_1978874

**Comment by nonamethanks** [comment]
Seems this happens with long strings in general. It can be replicated with the following comment on a browser window with small width: https://danbooru.donmai.us/posts/3770857#comment_1978874
