### ISSUE TITLE
Sidebar taglist is shown for status:unmoderated even when empty

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4280]
As the title says. Also, the paginator is shown as "< 1 >" instead of "< >" unlike with other empty pages.
![image](https://user-images.githubusercontent.com/12946050/73601595-89d97f00-4564-11ea-83ee-be23f47e25f6.png)

**Comment by evazion** [comment]
This is a caching problem, we cache the page count and the sidebar for most searches, which is wrong for this search because it depends on the current user.
