### ISSUE TITLE
Related tag search no longer allows the JSON/XML formats

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4282]
As reported by @unbreaky on Discord. For example, the following URL:

https://danbooru.donmai.us/related_tag.json?query=kantai_collection&category=

produces the following output:

```
{
  "success": false,
  "message": "application/json is not a supported format for this page",
  "backtrace": []
}
```

Looks like it might have been broken by fcfdd94. Anyways, right now it's affecting my IndexedAutocomplete script ([topic #14701](https://danbooru.donmai.us/forum_topics/14701)).

**Comment by evazion** [comment]
This is known, I had to temp disable this because it was broken by c7185724d53a672d2fa3b48d888975355a52d432. That commit tries to add html data attributes for all show pages, but there were a couple of show pages that actually returned a collection of items instead of a single item.
