### ISSUE TITLE
"only=is_favorited" not work in /posts.json

### ISSUE THREAD

**Issue by onlymash** [danbooru/danbooru#4310]
example:
> https://danbooru.donmai.us/posts.json?limit=1&page=1&only=id,created_at,is_favorited&login=[username]&api_key=[api-key]

response:
```
[
  {
    "id": 3798021,
    "created_at": "2020-02-25T01:45:34.798+08:00"
  }
]
```
`is_favorited` field no longer supported?

**Comment by BrokenEagle** [comment]
Use the following:

`only=is_favorited?`
