### ISSUE TITLE
Editing an expired ban's feedback and changing the duration breaks feedbacks sitewide

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4319]
While testing bans on Testbooru I ended up breaking all feedbacks - it's now impossible, at least for me, to edit or delete any of them. The error is the following:

ArgumentError wrong number of arguments (given 0, expected 1) 
```
ArgumentError exception raised
app/models/user_feedback.rb:24:in `visible'
app/controllers/user_feedbacks_controller.rb:11:in `edit'
```

Not sure if this is a problem with Testbooru only or also applies to the main site. 

EDIT: seems it was fixed in afe4d48772376b1322adcd9aadb4a4f8f4341342 but Testbooru is behind on updates.

**Comment by evazion** [comment]
Updated Testbooru.
