### ISSUE TITLE
Add pool creator ID information

### ISSUE THREAD

**Issue by gastrodon** [danbooru/danbooru#4322]
I know that this was dropped in 2dab9aa for the reason of being unused, but this was something that saw a good bit of use in some of my projects. Are inconsistencies something that was common / is difficult to fix? I would appreciate considering re-adding this information to the api

**Comment by BrokenEagle** [comment]
You can use the `/pool_versions` endpoint to accomplish the same. Just add `search[is_new]=true` and it will only return the pool creation version, and the **updater_id** on that will be the same as the creator ID that you're looking for.

https://danbooru.donmai.us/pool_versions?search[is_new]=true

If needed, additional search parameters can always be added to that endpoint. The following is the current list of attributes and search parameters.

1.  **Integer**
    - `pool_id`
    - `updater_id`
    - `version`
    - `category`

    See [Help:Number syntax](https://danbooru.donmai.us/wiki_pages/help%3Anumber_syntax) for search format.

2. **Array**
    - `post_ids`
    - `added_post_ids`
    - `removed_post_ids`

    See [Help:Array syntax](https://danbooru.donmai.us/wiki_pages/help:array_syntax) for search format.

3. **Text**
    - `name`
    - `description`

4. **Boolean**
    - `description_changed`
    - `name_changed`
    - `is_active`
    - `is_deleted`
    - `is_new`

5. **Other**
    - `post_id` - Searches for a single post ID in either the added post IDs or the removed post IDs.
    - `name_matches` - Searched for the pool name using normalization and wildcard matching.
    - `updater_name` - Searches using a single user name.
