### ISSUE TITLE
Add support for 2048 Tumblr image links

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4324]
Tumblr now has a 2048 image format, so this new size needs to be checked for and used when it is available. The following link can be used to test any updates.

https://kome-no-id.tumblr.com/image/190996209038

**Comment by nonamethanks** [comment]
As mentioned in issue #4380, we should go through all alt_sizes+original-size images returned by the API and compare their resolution, and pick the biggest one, rather than hardcode the biggest format. There's several cases where the original_size image is not the biggest available pic.
