### ISSUE TITLE
Unable to search for pictures by source site

### ISSUE THREAD

**Issue by tartarsauces** [danbooru/danbooru#4327]
I tried to look for some images that have pixiv as a source by typing "source:http://pixiv.net" like in the cheat sheet but it keeps giving me the error on picture.
![image](https://user-images.githubusercontent.com/61872610/76082371-47202200-5fbc-11ea-9f21-b7b4fac9eba3.png)
However, "-source:http" and "source:pixiv/fastrunner2024" don't give me this error, though the latter doesn't show any results like it should (there is at least one image by that artist which has a pixiv source on Danbooru.

**Comment by BrokenEagle** [comment]
The shorthand Pixiv source search as above was removed a while back (since images no longer use the STACC name in the image format), so you need to use a fully qualified source search like below.

```
source:http://*.pixiv.net/*/fastrunner2024
```

**Comment by BrokenEagle** [comment]
Since there was no response and it's not actually an issue, I'm closing this.
