### ISSUE TITLE
Artist urls field accepts duplicates if using different scheme (http/https)

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4336]
Example:
https://danbooru.donmai.us/artist_versions?search%5Bid%5D=679932

All of those added urls were already existing in https form (two active, two deleted).

**Comment by evazion** [comment]
This was fixed for most well-known sites in 10dac3ee51b7a3140b55dd24471a4eb8f779787f. For arbitrary sites it's still possible because we don't know which URL is the right one, http:// or https://.
