### ISSUE TITLE
Users shouldn't be able to vote on their own bulk update/etc requests

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4357]
Tested on https://danbooru.donmai.us/forum_topics/16713
![image](https://user-images.githubusercontent.com/12946050/77599147-1c165780-6f04-11ea-917a-989c929c0e57.png)

Also "Reason:" shouldn't be added to the forum post if the reason is empty.

**Comment by evazion** [comment]
I don't view this as a problem, but okay.
