### ISSUE TITLE
Bulk updates shouldn't prevent you from reversing the order of aliases/implications

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4358]
Currently if you try to do something like what I did in [forum#164423](https://danbooru.donmai.us/forum_topics/5860?page=2#forum_post_164423), you get stopped with the following error:

`Error: Error: Antecedent tag must not be aliased to another tag (create implication defloration -> virgin)`

Besides the fact that it displays "Error:" twice, bulk requests (if I understood correctly) are now processed sequentially, so there shouldn't be a need to wait for part of a request to be approved before being allowed to submit the rest of it.

**Comment by evazion** [comment]
I think this is fixed now. Reversing the direction of an alias should work.
