### ISSUE TITLE
Allow builders to move small (artist) tags manually rather than having to request a bulk update every time

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4359]
Moving tags manually currently breaks a lot of things, from saved searches to bookmarks (since the artist ID changes).
Builders should have a way to bulk move very small tags (<50 posts maybe?) because translation mistakes and lazy artist naming happen pretty often.

**Comment by nonamethanks** [comment]
Something that occurred to me, there should be a mod action registered whenever something like this would happen, as to being able to distinguish properly and unproperly moved artists.


And thinking about it it's probably a good idea to have it apply to any kind of category, not just artists.

**Comment by BrokenEagle** [comment]
> And thinking about it it's probably a good idea to have it apply to any kind of category, not just artists.

Maybe start with artists first and see how that works out. Artists are a little more clearcut, and I'm a little worried about the other categories being abused or accidentally misused. Just my two red cents.
