### ISSUE TITLE
builders+ should be exempt from dmail captcha

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4361]
I'm getting blocked by cloudflare every couple of hours when I try to respond to a DMail. 
It should be assumed that builders+ (and probably gold+ too given that they have to pay for an upgrade) are trustable enough not to have these measures put on them.

It's especially annoying when you have to do those "select all" ones, because clicking the "I am human" button is not enough.

**Comment by evazion** [comment]
Fixed.
