### ISSUE TITLE
No note borders on certain browsers

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4362]
https://danbooru.donmai.us/posts/3837464
![image](https://user-images.githubusercontent.com/12946050/77786125-927a9d00-705d-11ea-801e-789c1df547ce.png)

Tested on chrome android & desktop and vivaldi.
This makes it very hard to see if a post has been translated.

**Comment by BrokenEagle** [comment]
I'm not experiencing this on my Chrome Android. 

![Screenshot_20200327-111950](https://user-images.githubusercontent.com/21149935/77787598-03e62b80-701d-11ea-8da6-c8622b835563.png)

**Comment by nonamethanks** [comment]
I figured it out, the problem is caused by dark mode. On light mode the border appears fine.
