### ISSUE TITLE
Hover for large embedded notes gets in the way and covers unreasonable amounts of the picture

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4363]
Example: https://danbooru.donmai.us/posts/3729413
![image](https://user-images.githubusercontent.com/12946050/77786687-83e0b580-705e-11ea-9585-7de88d5829d9.png)

Embedded notes have no reason to show an hover that big, because unlike normal notes their state is already represented by default. Just make them editable through double click or display a small hover with text like normal notes instead.

**Comment by BrokenEagle** [comment]
-1 Clicking is already triggering the movable status.

Instead, the note body can be changed to read "Click to edit".
