### ISSUE TITLE
No way to see tag vandalism anymore

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4364]
Before, you could see tag vandalism easily by looking at dark red/dark green changes in a user's post history. Now reverted tags are not shown differently anymore. This is a pretty serious loss of functionality.

Also ties to issue #4354 because this makes spotting differences much harder.

**Comment by nonamethanks** [comment]
Note that none of the current version comparison types replace the old way. Previous and subsequent only count the other closest post version, and current only shows the diff between current version and latest version, with no way to know which tags were reverted.

Reverted tags should be shown with a different coloration like before.

**Comment by nonamethanks** [comment]
A good example of this:
Neither subsequent nor current in the following post version (https://danbooru.donmai.us/post_versions?search%5Bpost_id%5D=3810511&type=previous) show exactly what happened. 
![image](https://user-images.githubusercontent.com/12946050/77790118-8514e100-7064-11ea-8cd5-cef96322f1cb.png)


There's no way for someone now to know whether the user removed those tags. Yes, I could check the post versions, but that's impossible in the case for example that an user decides to populate a tag with hundreds of posts or to nuke it from them.

**Comment by BrokenEagle** [comment]
I'll go ahead and add another column with the added/removed tags from the previous version as well, and have that be compared against the subsequent/current version when those modes are used.
