### ISSUE TITLE
Save and display deleted usernames for mods+

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4383]
Brought up by OOZ on discord. It's useful for moderation purposes to have a deleted account's username visible without having to go to the forums and search for quotes to that user's posts.

**Comment by luni3359** [comment]
How about adding a link to the name change reports? Because otherwise I think it'd clutter the interface on users that change names too frequently.

**Comment by nonamethanks** [comment]
This is for deleted accounts, not name changes. When an account is deleted their username is erased too. It's good to avoid indexing when someone doesn't want their name associated with danbooru anymore, but doesn't help for sockpuppets etc.
