### ISSUE TITLE
Prevent custom CSS softlocks

### ISSUE THREAD

**Issue by easyaspi314** [danbooru/danbooru#4385]
While I haven't tested it, it is theoretically possible to softlock yourself out of Danbooru by setting a custom CSS to something like this:

```css
* {
    display: none !important;
}
```
This applies to the settings, so you can't edit it back.

Obviously that is an extreme example of something only an idiot would do, but there are other things that could have a similar effect that can come up accidentally, such as bad element positioning, accidentally disabling interactivity, overlaps, opacity, disabling scrolling, selecting the wrong element, etc.

The only way to fix it would be to manually disable it in inspect element or tab around, something mobile devices can't even do.

I believe that custom CSS should *not* be enabled on the settings pages, and/or there should be a URL kill switch parameter (e.g. `&enable_custom_styles=false` or something). This makes everything basically foolproof, as people don't care if the settings are pretty.

**Comment by lllusion3469** [comment]
Disabling custom CSS on the settings page would break some (imo) legitimate use-cases, e.g. I use it to make the "custom css" and "frequent tags" `<textarea>`s less tiny:
```css
#user_favorite_tags, #user_custom_style {
  height: 500px
  ; /* unimportant */
}
```
---
The `; /* unimportant */` hack is necessary because [normally `!important` would be forcibly inserted with no way to opt out](https://github.com/danbooru/danbooru/blob/692981e964e8d703a9c9743676aa1d1de0569fea/app/logical/custom_css.rb#L7) and with `!important` the `<textarea>` isn't manually resizable anymore. (it's also caused me some other problems in the past)

**Comment by evazion** [comment]
Use https://danbooru.donmai.us/settings?css=false to disable custom css.

> The ; /* unimportant */ hack is necessary because normally !important would be forcibly inserted with no way to opt out 

In hindsight it was a bad idea to insert `!important` automatically, but that's difficult to change now without breaking existing css.

**Comment by lllusion3469** [comment]
If you wanted to change it, couldn't you modify the existing custom css in the database like in [custom_css.rb](https://github.com/danbooru/danbooru/blob/692981e964e8d703a9c9743676aa1d1de0569fea/app/logical/custom_css.rb#L7) in place (maybe adding an explanatory comment on top of the custom css) and remove `CustomCss.parse`? Shouldn't be too difficult, I think.

I don't know how many of the current ~750000 users actually have custom CSS, though, and I couldn't figure out how to do it with pure postgres `regexp_replace` (it might be possible using `regexp_split_to_array`, `unnest ... with ordinality`, `string_agg`, `like '@important%'`, and `regexp_replace`).

It would still break old styles from the forum but it's not like styles were never broken before - only recently with `#image-container` → `.image-container`.
