### ISSUE TITLE
Update keyboard shortcuts page to reflect new changes

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4390]
https://danbooru.donmai.us/static/keyboard_shortcuts

"z" to zoom, etc

Perhaps it sould be a wiki page, like the bookmarklet notice, so that builders can update it, instead of having to change the code for it.

**Comment by evazion** [comment]
The keyboard shortcuts page is hardcoded because it uses some special formatting that isn't supported by dtext.
