### ISSUE TITLE
Automatically add artist tag to tagbox on upload page

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4392]
Unlike with translated tags, there aren't cases where the artist tag should not be added (unless the artist entry is wrong, but in that case the entry should be corrected instead).

It'll also help with new users not tagging artists even when an artist tag exists (which happens pretty often from what I've seen while approving posts).

**Comment by Unbreaky** [comment]
Would this just be the first time the upload page is loaded or?

**Comment by nonamethanks** [comment]
I was thinking something like autoclicking the translated tag for artists, where it's autoadded to the tag box.

**Comment by Unbreaky** [comment]
Yes but would it just do it the first time the upload page was loaded or every time artist tags were fetched?

**Comment by nonamethanks** [comment]
Good question. No idea to be honest. Probably better to do it on every refresh, by tying it to the javascript that shows/refreshes the related tags, and checking if it's already inserted in the tag box.

**Comment by Unbreaky** [comment]
The main reason I'm asking is that some sources can give multiple artist tags and all of them being added automatically could be quite annoying, this used to be the case when an image were sourced to a Fantia post before I removed post URLs from a bunch of artist entries that had them for some reason, there are probably other cases out there as well but I don't know any off-hand.

This would be better solved by fixing those artist entries (if possible) when coming across them though.

**Comment by nonamethanks** [comment]
Yeah I remember that bug too, it should be addressed before this is done. IIRC it happens because the url parser keeps removing url parts until it gets to top level domains and matches everything.

**Comment by evazion** [comment]
In this case it's done when the upload page is first loaded, not every time you click "Fetch source data". Mainly because doing it in Javascript is more complicated.

**Comment by BrokenEagle** [comment]
I'm reopening this since the artist tag really needs a space after it. There's no issue if the user starts out by clicking the tags in the tag list, but if they start typing, then the lack of a space will interfere with autocomplete, and having to add in a space every time will be annoying.
