### ISSUE TITLE
"No route matches" on upload redirection to post page

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4393]
![image](https://user-images.githubusercontent.com/12946050/78581072-a67b8700-7833-11ea-8d12-65dc6dd33a98.png)
Today I got this for https://danbooru.donmai.us/uploads/2864787. That page now works, so it was a temporary error, but it might be worth looking into why it happened.

**Comment by Unbreaky** [comment]
I got this error today, it happened when I refreshed the page after the "This upload is being processed" message was showed, one more refreshed and I got the uploaded image instead.

**Comment by nonamethanks** [comment]
Can confirm what Unb said, it only happens when I click on "upload" before the file has finished processing.

**Comment by evazion** [comment]
Should be fixed as part of abdab7a0a8101e9c112b5bba51b477e9bbed3c3d.
