### ISSUE TITLE
No preview on upload page when not using bookmarklet

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4396]
Example:
* go to https://danbooru.donmai.us/uploads/new
* add https://www.pixiv.net/artworks/69064717 to the source field
All parameters are fetched correctly but no preview shows up.

In the console I get the following:

```javascript
uploads.js.erb:146 Uncaught TypeError: Cannot read property 'naturalWidth' of undefined
    at update_scale (uploads.js.erb:146)
    at dispatch (jquery.min.js:2)
    at v.handle (jquery.min.js:2)
```

**Comment by evazion** [comment]
Fixed as part of abdab7a0a8101e9c112b5bba51b477e9bbed3c3d.
