### ISSUE TITLE
Replacing corrupted image returns "source already exists"

### ISSUE THREAD

**Issue by OOZ662** [danbooru/danbooru#4409]
post #3859608 was only uploaded about halfway, not rendering in full size and having half a grey thumbnail. Leaving the replacement fields with their default contents as follows:

> Replacement URL: https://www.pixiv.net/artworks/80737765
> Final Source: https://i.pximg.net/img-original/img/2020/04/12/16/22/58/80737765_p0.jpg

fails with an error akin to "post with source [url] already exists." Given one's attempting to replace an existing image that seems like a method that shouldn't cause a failure. In the end I replaced it by downloading the source image and blanking the Replacement URL, but that's definitely not a desired solution.

**Comment by lllusion3469** [comment]
I can't find the issue right now but I'm pretty sure it's still possible to work around that by changing some part of the url to uppercase - in your case e.g. https://www.Pixiv.net/artworks/80737765
