### ISSUE TITLE
Proposal: Backseat User Moderation

### ISSUE THREAD

**Issue by OOZ662** [danbooru/danbooru#4410]
Here's a not-uncommon scenario:
- A new user does something relatively minor; they don't tag well, they leave dumb comments, etc. They could use a warning or a couple-days ban at most.
- Some other user, usually of Builder level, leaves them a scathing negative feedback about it. Likely there was no prior DMail communication about the infraction.
- A moderator (namely me) comes by, sees the feedback, and figures that's enough torture for the user.
- While the staff is away, user continues their dumb thing or does a new dumb thing
- Builders, sometimes up to three, dogpile in and bury the account in negs.
- Moderator returns to find Discord on fire with mockery and the long line of negs and has to decide whether to ban after all that.

I understand that they're trying to help. It's been suggested that they do this instead of contacting staff because they're worried about "being called banhappy" and told to "give the account a chance," but that seems to happen regardless of whether they get their stings in first since I won't ban a first infraction if they've already been negged. I feel like this encourages problems on both sides; "backseat moderation" by a horde of users and leaving the other user feeling ganged up on before getting banned which lowers the "effectiveness" of temp bans and I suspect increases the likelihood of malicious retribution.

My current thoughts are that something mirroring the new comment/forum report system should be implemented for user accounts. Restrict negative or non-positive feedbacks to Mod+ (or, the more potentially-popular but more painful to enforce option: create a rule against using them for this purpose), add a Report button to user account pages and a thread or table-page with reported accounts on it, and add some kind of feature to alert staff to activity within it (thread email subscriptions, top-banner alerts ala "check the queue"). But given I know nothing of code, I defer to other opinions as well.

**Comment by nonamethanks** [comment]
I think something as drastic as removing user feedbacks for non-mod users would be a pretty bad decision, especially given the past drama involving moderators. I don't think I need to go into details, but mods need to be held accountable too.
Furthermore, taking away feedbacks would punish users who have used them correctly, while those who didn't would still keep finding other ways to stir up drama.

There's already a warning in the feedbacks page that tells people not to give frivolous negs and to first contact the other party. This should be enforced and people who ignore it should be actively warned. Maybe show a mod-only flag in the feedbacks page if someone giving a negative/neutral feedback has not sent the receiving user a dmail in the last X weeks or something similar (obviously this should not apply to positive feedbacks).

**Comment by BrokenEagle** [comment]
### Reports

Well the good news is that there has always been an option to report users, but it has been turned off in the code so far. The bad news is that the current way moderation reports work makes it difficult to turn them on as is because the system enforces a uniqueness constraint on new reports, i.e. a user can only ever report an instance of something once. This means that a user would only ever be able to report a user once and never again after that. This can be worked on, but it won't be the instant flip of a switch.

### Feedback

As for feedbacks, perhaps there should be checks enforced by the system that the user has to fulfill in order to escalate the situation.

1. Neutral feedback

    Must attach at least one DMail (mod-only visibility) with the option to attach multiple DMails.

2. Negative feedback

    Must link a neutral feedback created by the user, with the option to attach one or more DMails (mod-only visibility).

Exceptions to the above would be moderators and any feedback auto-generated by the system.

**Comment by nonamethanks** [comment]
That doesn't include however cases where users have been warned through other means, like forums or comments (plenty of cases like that, I've done it myself in the past). 
It'd be easier imo to just add a second prompt that asks you if you're really sure when submitting a feedback. That way there's really no excuse if you still decide to go through with it without reason.

**Comment by nonamethanks** [comment]
This issue is not really relevant anymore since the introduction of user reports, because people have switched to using those instead of giving useless feedbacks, so I guess we can consider it solved.
