### ISSUE TITLE
Update the Terms of Service and flag form

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4415]
The terms of service and flag form have been very outdated for several years now. Some of it is as old as 7 years.
It's been brought up time and time again but nobody ever did anything about it, so I'm opening this so we don't keep forgetting about it.
If it's not possible to move them to a locked wiki page like it was done for the bookmarklet, so builders can update them as needed, they should be updated. (I don't see the risk in allowing builders to edit them though)

Some examples:

> 
> You may not upload any of the following:
> * Non-anime: Photographs of American porn actresses, for example, are prohibited. Photographs of cosplayers, figures, or prominent figures in the industry are acceptable.

This is very badly worded and often causes people to flag anything that is not anime (including, but not limited to, [rabbit drawings](https://danbooru.donmai.us/posts/3270524), [non-immediately-anime-like drawings](https://danbooru.donmai.us/posts/2225979), [and other random content](https://danbooru.donmai.us/post_flags?commit=Search&search%5Bis_resolved%5D=true&search%5Breason_matches%5D=not+anime)). 

>* The following may be uploaded, but will be put to a higher level of artistic and qualitative scrutiny than normal, and (if applicable) you must tag them with the corresponding tag. Please do not upload more than 20 a day of these works:

Very few users upload >20 posts a day at all, let alone this kind of content. The sentence would be fine without pointing out such a number.

>*Western: Drawings of characters from non-Japanese comics, games, and other properties.

This has not been prohibited for a long time (see the 12k Overwatch posts, etc)

>*The following may be uploaded but are generally not recommended unless a better copy cannot be found:

This section lacks a warning about third-party edits in general.

>*Hard translations: Images that have been edited to replace the original language are discouraged.

This instead should explicitly point out that official english versions are allowed - I've seen them flagged in the past.

**Comment by BrokenEagle** [comment]
I agree that this should be made into a locked wiki page. This will allow for changes to be discussed on the forum to be implemented quickly without having to rely on the site maintainers to hard code them.

In the unlikely event that there are bad edits (Builders **should** know better than to do this), they can be easily reverted. Also, monitoring the page for edits isn't that hard with the use of EventListener ([forum #1234](https://danbooru.donmai.us/forum_topics/14747)). I'm already doing that myself for most of the the high profile wiki pages.

**Comment by nonamethanks** [comment]
Apparently the flag notice is already a wiki (https://danbooru.donmai.us/wiki_pages/help:flag_notice). I wasn't aware of this. I'll wait before editing it until this is resolved, however.

**Comment by evazion** [comment]
I agree with extracting the upload rules, but certain parts of the terms of service like the privacy policy and the copyright infringement policy are there for legal reasons and need to remain uneditable.

**Comment by nonamethanks** [comment]
Just a note, I've updated [the flag notice](https://danbooru.donmai.us/wiki_pages/help:flag_notice) since we've gotten a few more off-topic flags since. I've tried to keep it brief, but i've removed the "off-topic" term because that invites a lot of warring as we've already seen in [topic #16692](https://danbooru.donmai.us/forum_topics/16692), and "off-topic" hasn't meant anything for a while.
