### ISSUE TITLE
Can't go to next page, while on first page

### ISSUE THREAD

**Issue by goldenevil5** [danbooru/danbooru#4432]
My account (Goldenevil5) is having a problem where I can't go to the next page of seemly all character tags. Even for some like Reimu who has 10+ I can't get to the second page

**Comment by evazion** [comment]
Possible fixed by 986bc6e314430738a6d20c5d0be560f3a8efff12 (if you had the "Deleted post filter" account setting turned on) or by 828347dfc519fefa7cd3daf5519625c9dd95beb7 (if you were searching for aliased character tags).

**Comment by evazion** [comment]
I believe this is fixed, comment again if this is still an issue.
