### ISSUE TITLE
Separate forum/comment/etc report notice

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4434]
Ref: [forum #166002](https://danbooru.donmai.us/forum_topics/9127?page=304#forum_post_166002)

Separating them would make it possible to include helpful links to wiki pages and guidelines for each type of report.

**Comment by BrokenEagle** [comment]
It would be much simpler to just add more information to the report notice wiki. That's why it's editable after all. There's not a whole lot there right now as it is, so it's being heavily underutilized.

**Comment by nonamethanks** [comment]
Well, OOZ662 said in the discord that in three months they had an average of almost two reports a day, so it'd be helpful to separate them so that specific info can be listed. For example the comment etiquette is irrelevant for forum posts.

**Comment by BrokenEagle** [comment]
Why not just have something like the following?

<hr>

### Comments

Blah blah comments.

### Forum posts

Blah blah forum posts.

......
......

<hr>

Etc. etc.

**Comment by nonamethanks** [comment]
Closing this since the various rules were condensed into the [Community Rules](https://danbooru.donmai.us/wiki_pages/help%3Acommunity_rules), so I just added a link to that.
