### ISSUE TITLE
Autotag image metadata

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4442]
We already have [photoshop_(medium)](https://danbooru.donmai.us/posts?tags=photoshop_%28medium%29+), though it's pretty underused currently, mostly because you can't tell without checking EXIF unless the artist says so in the commentary.

It'd be worthwile to automatically extract that kind of info from a picture's EXIF metadata and add it to the post on upload like we already do for other meta tags. Other potentially large tags would be painttool_sai_(medium) and clip_studio_paint_(medium), which currently don't exist.

Since it'd be a removable tag, the backlog for already uploaded posts can be populated by users (I'll do it one of these days probably).

Not sure what other kind of info can be extracted from EXIF data that would be relevant to Danbooru.

**Comment by nonamethanks** [comment]
BTW related to issue #4113 in that EXIF data sometimes also stores creation date, so that'd also be a nice thing to record, though impossible currently.

**Comment by GlassedSilver** [comment]
I love this idea!

**Comment by nonamethanks** [comment]
I've started populating the exif tags. I'll update the issue with all the new tags once I'm done going through all posts.

**Comment by nonamethanks** [comment]
Forgot to update this.
https://i.fiery.me/TQNeF.txt
This is the extraction of all EXIF softwares up until post 3943592. I havent processed it yet, created necessary tags etc. I've created a few software tags under [Drawing Softwares](https://danbooru.donmai.us/wiki_pages/tag_group:drawing_software.html) but it's still a work in progress.

**Comment by GlassedSilver** [comment]
You're doing God's work, man.
