### ISSUE TITLE
Two tag search gives option to create wiki page when one is a metatag

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4455]
[status:active test_tag](https://danbooru.donmai.us/posts?tags=status%3Aactive+test_tag) for me shows the "Wiki" tag and gives me the option to create a wiki with title "status:active test_tag".

Also works with other metatags, example: [id:1,2,3 -test](https://danbooru.donmai.us/posts?tags=id%3A1%2C2%2C3+-test), though in this case it doesn't work if the wiki doesn't exist. Seems negated tags only show a wiki if they exist, otherwise only the "posts" tab is shown. Not sure if this is intended.

**Comment by evazion** [comment]
The intended behavior as per #4343 is to show the Wiki tab when the search contains a single tag, even if it has other metatags. The bug here was that the create new wiki link used the full search for the new wiki title.
