### ISSUE TITLE
When uploading, automatic source data fetching doesn't trigger IQDB

### ISSUE THREAD

**Issue by luni3359** [danbooru/danbooru#4456]
You have to click "Similar".
![before](https://user-images.githubusercontent.com/16832398/81488518-57a87f00-922f-11ea-8d41-41bd07fbcf98.png)
![after](https://user-images.githubusercontent.com/16832398/81488505-1dd77880-922f-11ea-98f6-7d6a9e4ebd33.png)

**Comment by evazion** [comment]
Fixed as part of abdab7a0a8101e9c112b5bba51b477e9bbed3c3d and 21dcf53dcb111579d38135ca84444a3b22d3d805. The similar button was removed, now IQDB results are always shown after you choose the file or source.
