### ISSUE TITLE
access-control-allow-origin header sent twice

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4485]
We're sending access-control-allow-origin twice.

https://github.com/danbooru/danbooru/blob/af50e10c3a723a10916633be37a0ba4f1e0199b5/app/controllers/application_controller.rb#L69
https://github.com/danbooru/danbooru/blob/24ab98ccc83915207a00bce19ad521fa4674324f/config/webpacker.yml#L75

![image](https://user-images.githubusercontent.com/12946050/82846638-26e06f00-9eea-11ea-9083-db5ec0d0a9ec.png)

**Comment by evazion** [comment]
Fixed. This was inadvertently being set in Nginx.
