### ISSUE TITLE
Syntax error in danbooru application

### ISSUE THREAD

**Issue by SakurabaKiyoka** [danbooru/danbooru#4501]
build a danbooru server by wiki's guide,then i try to access the page,it shows errors.

app/logical/post_query_builder.rb:330: syntax error, unexpected keyword_in, expecting keyword_when
app/logical/post_query_builder.rb:407: syntax error, unexpected keyword_in, expecting keyword_when
app/logical/post_query_builder.rb:409: syntax error, unexpected keyword_in, expecting keyword_end
app/logical/post_query_builder.rb:411: syntax error, unexpected keyword_in, expecting keyword_end
app/logical/post_query_builder.rb:413: syntax error, unexpected keyword_in, expecting keyword_end
app/logical/post_query_builder.rb:418: syntax error, unexpected keyword_end, expecting end-of-input
app/logical/post_query_builder.rb:330: syntax error, unexpected keyword_in, expecting keyword_when
app/logical/post_query_builder.rb:407: syntax error, unexpected keyword_in, expecting keyword_when
app/logical/post_query_builder.rb:409: syntax error, unexpected keyword_in, expecting keyword_end
app/logical/post_query_builder.rb:411: syntax error, unexpected keyword_in, expecting keyword_end
app/logical/post_query_builder.rb:413: syntax error, unexpected keyword_in, expecting keyword_end
app/logical/post_query_builder.rb:418: syntax error, unexpected keyword_end, expecting end-of-input
app/logical/post_query_builder.rb:330: syntax error, unexpected keyword_in, expecting keyword_when
app/logical/post_query_builder.rb:407: syntax error, unexpected keyword_in, expecting keyword_when
app/logical/post_query_builder.rb:409: syntax error, unexpected keyword_in, expecting keyword_end
app/logical/post_query_builder.rb:411: syntax error, unexpected keyword_in, expecting keyword_end
app/logical/post_query_builder.rb:413: syntax error, unexpected keyword_in, expecting keyword_end
app/logical/post_query_builder.rb:418: syntax error, unexpected keyword_end, expecting end-of-input
app/logical/post_sets/post.rb:10:in `initialize'
app/controllers/posts_controller.rb:13:in `new'
app/controllers/posts_controller.rb:13:in `index'

![issues](https://user-images.githubusercontent.com/16064020/83964151-b839e300-a8e5-11ea-8eb4-917090029a82.png)

I don't know what happening.my ruby version is ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu] system Ubuntu 19.10 x64 server

**Comment by evazion** [comment]
Ruby 2.7 is the minimum required version. The guide needs to be updated to explain this. For now you can either use Ubuntu 20.04, or install rbenv then install ruby-2.7 (see https://gorails.com/setup/ubuntu/19.10#ruby-rbenv).
