### ISSUE TITLE
Clicking "View wiki" on Artists with no wiki redirects to the posts page

### ISSUE THREAD

**Issue by luni3359** [danbooru/danbooru#4507]
Makes it hard to make a wiki page for a new artist.
This happens in the posts page, didn't check if it happens on other places. I deleted the sidebar on the first screenshot because the tags were getting in the way of what I tried to bring attention to.

Artist with no wiki page:
![2020-06-13_190702](https://user-images.githubusercontent.com/16832398/84581665-6394dd00-ada9-11ea-9f58-19c942150cfc.png)

Artist with wiki page:
![2020-06-13_190732](https://user-images.githubusercontent.com/16832398/84581676-70b1cc00-ada9-11ea-844c-b0b031b9927b.png)

**Comment by nonamethanks** [comment]
I think this was done on purpose to discourage people from making artist wikis.
