### ISSUE TITLE
Show limited view of other user's uploads on the upload index

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4544]
As I understand it, these were hidden because some users were harassing other users for min-tagging on upload, or because sensitive links were being uploaded. However, being able to see other user's uploads is useful as it can show whether errors you are experiencing are happening to other users. Therefore, allow all users to see each other's uploads, but just present a sanitized display when the upload is not your own. Probably just the status message and the post ID link.  This would include the API as well.

**Comment by BrokenEagle** [comment]
@evazion Is there a reason why failed uploads can't be shown to other users? That was kind of the biggest point for seeing other's uploads, as it would show if anyone else is experiencing the same upload errors.

**Comment by evazion** [comment]
If you accidentally click on the bookmarklet while browsing (which happens sometimes), the error message can reveal which page you were on. If this happens on a social media site like Facebook, it can reveal your real world identity. If you can't see the error message, there's not much point in showing the failed upload.
