### ISSUE TITLE
Show a "not implemented" message instead of showing an exception on source download methods

### ISSUE THREAD

**Issue by thenamewastaken** [danbooru/danbooru#4545]
When trying to e.g. upload a picture using the "URL" field, if Danbooru is not configured with the proper informations to "log in" the provided address, an error message showing the exception and the stack trace is shown.
It would be better to add a "this feature is not implemented" page when the relevant settings are nil (or another "falsey" value) and one tries to use said feature.

It would probably be best to have this fine-grained for each website API, so that the message doesn't appear if the site using Danbooru has, for example, configured pixiv but not DeviantArt.

**Comment by nonamethanks** [comment]
Just for the record, if you want to completely disable a strategy on your fork, what you should do is edit this array and comment the strategies you're not interested in:
https://github.com/danbooru/danbooru/blob/42f0112c385ee6b47501186b8be18f1eeb238880/app/logical/sources/strategies.rb#L3-L19
