### ISSUE TITLE
Error raised when using search with two "order" tags 

### ISSUE THREAD

**Issue by tengri7** [danbooru/danbooru#4546]
Hi, 

I don't think it is a legitimate use case, but I just wanted to point out the issue. When I try to search with both tags "order:rank" and "-ordfav:%username%" (note the dash '-' before the second tag), it throws an unhandled error like follows:

Error
PG::UndefinedTable: ERROR: missing FROM-clause entry for table "favorites" LINE 1: ...@ to_tsquery('danbooru', E'''fav:%user_id%''')) AND (favorites.... ^

Details
ActiveRecord::StatementInvalid exception raised
app/logical/post_sets/post.rb:108:in `posts'
app/controllers/posts_controller.rb:14:in `index'

**Comment by nonamethanks** [comment]
You should be using "-fav:" instead, as two order tags together don't make sense, but yeah it could fail more gracefully.

**Comment by tengri7** [comment]
Thanks for the tip. Yes, I'm not very familiar with all the rules behind using tags so I just copied the default tag from the Favorites page.

**Comment by nonamethanks** [comment]
Closing this since it's already tracked in the second point of issue #4436.
