### ISSUE TITLE
How to diasable the showing Explicit and Questionable rating post

### ISSUE THREAD

**Issue by JohnSmith868** [danbooru/danbooru#4557]
I install danbooru on Ubuntu, and run 
bundle exec rails server.
 And then I upload a post and set it to Explicit rating, but I still see it after log out.
Is there are safemode on danbooru?

**Comment by nonamethanks** [comment]
The following block defines when tags are blocked: https://github.com/danbooru/danbooru/blob/afef9cc9ab523b77824d88b11c2d07f4a37c7539/app/models/post.rb#L1464-L1470

What is your aim? If you want to set non-safe posts to be invisible unless you're logged in, you need to do something like changing `levelblocked `to have a check for the rating like `safeblocked `does, and change` user.is_gold?` to `user.is_member?`

**Comment by JohnSmith868** [comment]
Yes, I want to set non-safe posts to be invisible unless you're logged in, and I change `!user.is_glod?` to `!user.is_member?` in  `levelblocked`, but it doesn't work

**Comment by JohnSmith868** [comment]
I find the solusion about it, I define new method `isMember` and modify `visible?`.
thanks for your help
