### ISSUE TITLE
Option to delete from mod queue

### ISSUE THREAD

**Issue by ampersham** [danbooru/danbooru#4559]
Next to approve, disapprove, detailed rejection etc, I an option for direct deletion could be appropriate to add for easy removal of blatant off-topic content that should just be speedily removed from the queue.

**Comment by nonamethanks** [comment]
I'm not sure a delete button in the queue is a good idea. In the main site we rarely delete stuff directly, it feels like it'd be a dangerous source of misclicks.

**Comment by PiiXelx64** [comment]
> I'm not sure a delete button in the queue is a good idea. In the main site we rarely delete stuff directly, it feels like it'd be a dangerous source of misclicks.

delete with confirmation alert or smth could work tho

**Comment by nonamethanks** [comment]
Closing as wontfix for the above reason.
