### ISSUE TITLE
Allow users to disable user tooltips

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4561]
Currently post tooltips can be disabled through user settings, but user tooltips cannot. Either repurpose the existing setting so that it covers both tooltips, or create a new setting so that each tooltip can be disabled separately.

**Comment by evazion** [comment]
Wontfix. Most sites have this feature these days, including Pixiv, Twitter, DeviantArt, Tumblr, Github, and Reddit, and none of them have options for disabling it.

If you don't want this behavior, then either don't hover over usernames or use `#user-tooltips { display: none; }`.
