### ISSUE TITLE
Suggestion: Ambiguous/Do-not-use tag category

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4562]
This specific suggestion, among the various categories, has been proposed many times before, but I just noticed Gelbooru has it too ([example](https://gelbooru.com/index.php?page=post&s=view&id=5414568&tags=booty)), which makes a strong case for adopting it since it seems to work fine for them, so I'm opening this for consideration.
![image](https://user-images.githubusercontent.com/12946050/88729494-530bac80-d134-11ea-9bc2-d1ab83692d3f.png)

The category would be basically for tags that should not be used. This doesn't sound very useful at first, but there are many implications to consider: first of all the ability to use a "ambtags:>0" (or whatever it would be named) search, and then the fact that a warning could be tied to such tags so that people using them immediately notice. Also, it'd be much easier to spot such tags in the sea of blue that normal taglists can be.

This kind of category would be especially useful for things that cannot be aliased [(keyboard](https://danbooru.donmai.us/posts?tags=keyboard) is an example).

I know we want to avoid having a rainbow on the sidebar, but as these tags should never be used, that shouldn't be a problem, as they would effectively be handled like tagme and regularly sorted through.

And we have many of these tags. Here's a very partial list: https://danbooru.donmai.us/wiki_pages/list_of_disambiguation_pages

Feel free to immediately close this of course if it's rejected.

**Comment by BrokenEagle** [comment]
In addition to the points that nonamethanks brought up, the proposed new tag category would also be useful as a highlight in the wikis for tags that should or should not be in certain wikis. For example, the "list of" page that was mentioned above should just be a sea of grey, and any outliers would be instantly and clearly highlighted. Additionally, if the use of an ambiguous tag was used in any particular wiki, than that would also be highlighted for potential removal.

Another usecase could also maybe be the missed searches page, as many of the tags showing up there would be potential candidates for being made ambigous tags if they aren't already.

Also, besides using the "ambtags:>0" to find incorrectly tagged posts, the `/tags` endpoint could also be used for this, as it already normally only shows tags with postcounts greater than 0, and searching by the new category would bring up the full list of deprecated tags that are currently in use.

Finally, I'd also like to see the antecedents of aliases be given this category as well. As such, it would probably be better to give this category the same name as Gelbooru, i.e. "deprecated", which is more inclusive towards the aliases. This would also help highlight those cases in the wiki where an alias was left behind in a wiki without being updated to the consequent.
