### ISSUE TITLE
Appeals shouldn't count towards limit when accepted

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4566]
Currently, trying to appeal a post on the same day you've appealed another, even if the previous was then reapproved, is not possible. There's no reason why it shouldn't. Rather, the check should happen for unresolved appeals.

**Comment by BrokenEagle** [comment]
I changed the labels because the current behavior may have been intentional.

**Comment by evazion** [comment]
Fixed in e8dcc9c56.
