### ISSUE TITLE
Proposal: raise appeal count to match flags

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4567]
For as long as I've been an approver I've never really seen anyone abuse the appeal system in terms of volume, and the only time someone ever appealed too much was in the case of a member. If users were allowed to be appeal more posts at once it would also encourage them to use a feature that is pretty much almost always discarded in favor of posting in the forums.

**Comment by evazion** [comment]
Fixed in e8dcc9c56.
