### ISSUE TITLE
Don't unicode-normalize commentary

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4575]
An example: https://danbooru.donmai.us/posts/4018655 / https://twitter.com/i/web/status/1285891125694263296
"𝚂𝚞𝚐𝚎𝚛 𝚊𝚗𝚍 𝚂𝚙𝚒𝚌𝚎" becomes "Suger and Spice" because it passes through normalization (as far as I understand):
![image](https://user-images.githubusercontent.com/12946050/89475824-55e84c00-d789-11ea-8481-9aa27a116bbc.png)

This normalization makes sense in wikis because we want to get translated tags properly, but for commentary we want the most faithful version we can get and there shouldn't be any issue in avoiding unicode normalization.

**Comment by luni3359** [comment]
I agree, it would be nice to keep this information as-is rather than normalized.
