### ISSUE TITLE
Artist creation tool should normalize handles to be lower-case

### ISSUE THREAD

**Issue by ampersham** [danbooru/danbooru#4588]
Ie if I click to create a new artist entry for Isabelle, it should adjust all the characters in his name to be lower-case:
https://danbooru.donmai.us/artists/new?artist%5Bsource%5D=https%3A%2F%2Ftwitter.com%2FAC_Isabelle%2Fstatus%2F1294272787704696834

I don't know if this would cause any issues for other sources

**Comment by BrokenEagle** [comment]
All the characters are lowercase in the example you provided, so I don't think this is a problem. If you're talking about in the URL, well we don't normalize the caseness because caseness can matter.

**Comment by nonamethanks** [comment]
I'm not sure I understand this issue either, case sensitiveness for source matching is handled in each source, and for all sites we support it doesn't matter for artist usernames, so it's never a problem.
