### ISSUE TITLE
duplicate tags in a bunch of older posts

### ISSUE THREAD

**Issue by bipface** [danbooru/danbooru#4589]
a few hundred posts still contain duplicate tags `tall_image`, `long_image`, `wide_image`, `honkai_(series)`.
looks like the result of #2257
there's too many instances to be fixed by hand, IMO

The post page does reflect it:
![Capture](https://user-images.githubusercontent.com/24604367/90307203-82cdf900-df17-11ea-99a9-f9c10b9d3a5c.PNG)
(evidently it also screws up the sorting?)

query to get the full list:

```sql
select p.id, t.name, count(1)
from `danbooru-data.danbooru.posts` p,
  unnest(p.tags) as t
group by p.id, t.name
having count(1) > 1
order by p.id;
```

**Comment by nonamethanks** [comment]
I fixed them all with a script (there were 154 posts like that).
