### ISSUE TITLE
Find Users by IP and Vice-Versa Broken

### ISSUE THREAD

**Issue by OOZ662** [danbooru/danbooru#4596]
Clicking the Users and IPs links on a user's page results in the following:

    undefined local variable or method `attributes' for #<IpAddressPolicy:0x000055cec16a4cb8> Did you mean? api_attributes
    NameError exception raised
    app/policies/ip_address_policy.rb:7:in `html_data_attributes'
    app/models/application_record.rb:65:in `html_data_attributes'
    app/logical/table_builder.rb:61:in `all_row_attributes'
    app/views/table_builder/_table.html.erb:14
    app/views/table_builder/_table.html.erb:13:in `each_with_index'
    app/views/table_builder/_table.html.erb:13
    app/views/table_builder/_table.html.erb:1
    app/helpers/application_helper.rb:257:in `table_for'
    app/views/ip_addresses/_index_by_user.html.erb:5
    app/views/ip_addresses/index.html.erb:26
    app/controllers/application_controller.rb:43:in `respond_with'
    app/controllers/ip_addresses_controller.rb:15:in `index'
Swap `_index_by_user.html` for `_index_by_ip_addr.html` depending on link clicked.

**Comment by evazion** [comment]
Fixed in 4c3b4671efabdfab195a51e49058e62e6fa6436b.
