### ISSUE TITLE
Inconsistent search behavior when searching by age

### ISSUE THREAD

**Issue by luni3359** [danbooru/danbooru#4602]
As far as I've been made aware, ``approver:`` doesn't work in the same way that ``commenter:`` and ``noter:`` do in conjunction with ``age:``, hence the inconsistent behavior.

Example:
1. Someone searches ``approver:<user> age:<2h`` expecting to see approvals that user made in the past 2 hours.
2. ``age:<2h`` is interpreted as the post's age, rather than the time since the post has been approved.

**Comment by nonamethanks** [comment]
Related to issue #4503 - we'd need an order:approved or similar.

**Comment by evazion** [comment]
`age:` is the age of the post, not the age of anything else (when the post was approved, when it was flagged, when it was deleted, etc). Having it take on different behavior based on other metatags in the search would be confusing and also nonsensical in the face of more complex searches like `approver:evazion user:evazion age:<2h`.
