### ISSUE TITLE
Provide search parameter to detect empty string on text fields

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4604]
Discussed on Discord with @evazion. Currently, the only way to search for empty strings is to use the `*_regex` qualifier, e.g. `search[reason_regex]=^$` , however regexes are a pretty high hurdle for most regular users, so it would be beneficial to provide a standard parameter qualifier for all text fields

https://github.com/danbooru/danbooru/blob/c830973bd4a78b6d8487817ab32c4597fa093906/app/logical/concerns/searchable.rb#L198

The parameter could this for be something like `*_present` or `*_blank` , or perhaps both.

**Comment by evazion** [comment]
Fixed in #4893. Use `search[field_present]=false`, e.g. https://danbooru.donmai.us/wiki_pages?search[body_present]=false.
