### ISSUE TITLE
Databse export links are broken

### ISSUE THREAD

**Issue by bethouxa** [danbooru/danbooru#4605]
Links to the database export mentioned in the wiki (https://github.com/danbooru/danbooru/wiki/Database-export) return a 404 Not Found. All parts, from aa to ay, seem to have the issue.

**Comment by nonamethanks** [comment]
Those dumps have been broken for a long time, they're not coming back. I'll delete that wiki page since it's 6 years old and has never been updated after its creation.

 There's issue #4454 tracking the creation of new dumps.
