### ISSUE TITLE
Error "Directory does not exist '/var/www/danbooru2/current'" when running bundle exec cap production deploy

### ISSUE THREAD

**Issue by stampylongr** [danbooru/danbooru#4615]
Whenever I run `bundle exec cap production deploy`, I keep getting the error that the directory does not exist. However, when I create it, the process goes through a little more, but then it tells me it can't move the directory. Am I doing something wrong?

Log: <https://paste.ubuntu.com/p/KnwKyXWCT9/>

Edit: typo, oops.

**Comment by thenamewastaken** [comment]
`current` has to be a symlink to a directory. It will be changed during deploy to the actual installation directory, so when you are deploying for the first time you can just do `cd /var/www/danbooru2 && ln -s /tmp current` then call `bundle`.
The deployment should take care of this or at least have it mentioned in the install file, though.

**Comment by stampylongr** [comment]
That seemed to do the trick. Thanks!
