### ISSUE TITLE
Upload filesize change

### ISSUE THREAD

**Issue by kirikiyonami** [danbooru/danbooru#4617]
I want to increase the possible size of the uploaded file, I changed danbooru_default_config.rb, nginx.conf, danbooru.conf but still get warnings and then, validation error.
![chrome_AKHe1cB6SD](https://user-images.githubusercontent.com/56955307/97851256-2e603b80-1d06-11eb-9379-2f32089a924f.png)
![chrome_283eMg56j9](https://user-images.githubusercontent.com/56955307/97851360-5354ae80-1d06-11eb-8f6e-442f08169d94.png)
![chrome_nU9OUrClNH](https://user-images.githubusercontent.com/56955307/97851371-5780cc00-1d06-11eb-9cbf-7c75228dfd14.png)

**Comment by nonamethanks** [comment]
Did you restart your server after doing the change? Because the configs are only loaded on start. It works for me that way.

**Comment by evazion** [comment]
Yes, you need to restart nginx and your Danbooru instance after changing the config.

**Comment by kirikiyonami** [comment]
I have restarted nginx
