### ISSUE TITLE
New User Regisration Errror

### ISSUE THREAD

**Issue by kirikiyonami** [danbooru/danbooru#4618]
I`m already have Admin account, but when i try to register each other I have this:
![chrome_lTm1B2oX3T](https://user-images.githubusercontent.com/56955307/97851588-99aa0d80-1d06-11eb-9edf-2f4980be5bd1.png)
I get it on /users/new

**Comment by luni3359** [comment]
This is happening on your own Danbooru instance, correct?

**Comment by kirikiyonami** [comment]
> This is happening on your own Danbooru instance, correct?

Yes

**Comment by evazion** [comment]
You need to log out of your admin account first. You can't create a new account while logged into an existing account (see #4541).

**Comment by KnuffelBeestje** [comment]
> You need to log out of your admin account first. You can't create a new account while logged into an existing account (see #4541).

Weird, that doesn't seem to work.

**Comment by kirikiyonami** [comment]
> > You need to log out of your admin account first. You can't create a new account while logged into an existing account (see #4541).
> 
> Weird, that doesn't seem to work. I can't create a new account when logged out.

Same situation

**Comment by nonamethanks** [comment]
I actually get the same error if I try to register two accounts in quick succession on my instance from the same IP. @evazion I wonder if this is caused by the anti-spam measures that were implemented recently.

**Comment by evazion** [comment]
I added an option to disable verification of new accounts. I also made it so that verification is disabled by default for personal installations running on localhost or the local network.
