### ISSUE TITLE
New Relic: "Deployment not recorded: Application Danbooru does not exist."

### ISSUE THREAD

**Issue by stampylongr** [danbooru/danbooru#4620]
Whenever I try to run `bundle exec cap production deploy`, I keep getting the error that the application Danbooru does not exist. I already set up an account at New Relic, and I have entered a license key, however, it says it will create the app when it receives logs, but the program won't send logs until it sees the app exists.

What do I do?

Log: <http://paste.ubuntu.com/p/bJgjxXc9YX>

**Comment by thenamewastaken** [comment]
Make sure you edited `config/deploy/production.rb` with your actual set-up.
