### ISSUE TITLE
Give autogenerate IQDB/sample/preview capability to moderators

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4623]
As seen from #3386, this is a recurrent issue. Giving moderators this capability would allow for them to share in the work and would most likely quicken the response to any issues. I believe that the image replacement function includes both of these regeneration capabilities, but that seems like an awful lot of spam will be added to the image replacement index, considering that there is currently 250K+ posts that need to be fixed.

This could also be made granular, to reduce the load on the servers, but also to accurately document the fixes that occur on each post.

* Example: 
```
Method: POST
URL: /post_regenerations
Body: 
{
    post_id: 1234,
    type: iqdb
}
```

The different types should be **iqdb**, **sample**, and **preview**. The only thing the records would need to store are the post ID, the type, the timestamps, and the creator.

**Comment by nonamethanks** [comment]
Yeah having this would help a lot, it would allow us to do regular scans of missing content.

**Comment by nonamethanks** [comment]
It's now fixed.
