### ISSUE TITLE
Give unlimited searches for builders at least

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4644]
Given that during winter sale everyone got unlimited tags, it doesn't seem like performance's a concern.

There's many legit applications for 12+ tag gardening searches, such as color exclusions (you can't do for example -*_hair because that gets all the qualifiers).

I myself have several queries that I had to split in multiple parts to be able to garden stuff, such as searches for "hetero" or "male_focus" or clothings with missing colored tags. 
For example, "-brown_hair -blue_hair -blonde_hair -black_hair -white_hair -silver_hair -purple_hair -pink_hair -red_hair -orange_hair -grey_hair -bald -monochrome" is already 13 tags and normally impossible, and yet still results in 600k+ posts. This search doesn't account for the hundreds of thousands remaining posts under "-green_hair -aqua_hair -no_humans -helmet -head_out_of_frame" etc.

**Comment by evazion** [comment]
I'll wait until after the winter sale to do this. Wildcard searches will still need some kind of limit because searching for things like all `a*` tags would not be good. Currently the limit is 25, but it could be more like 250.
