### ISSUE TITLE
Space/underscore character inserted after 2 characters when changing Artist->Group

### ISSUE THREAD

**Issue by Kikimaru** [danbooru/danbooru#4647]
e.g. https://danbooru.donmai.us/artist_versions?search%5Bupdater_id%5D=781002

Removing a Group entry on an artist page seems to mark the old text as having a space/underscore after 2 characters.
Slightly inconsistent.

**Comment by evazion** [comment]
I assume you're talking about this edit:

https://danbooru.donmai.us/artist_versions?search[artist_id]=176413#artist-version-891857

What happened here is you tried to remove the group name `wegon`, but instead you accidentally replaced it with a space. 02c9498 fixed it to disallow group names consisting of only blank characters.
