### ISSUE TITLE
Searching for any posts that are parents or are children returns no results

### ISSUE THREAD

**Issue by luni3359** [danbooru/danbooru#4648]
**Steps to reproduce:**
1. Make the following search: ``~child:any ~parent:any``
2. There's no results

**Expectation:**
* Posts that have children on them, and posts that have a parent

**Result:**
* Nobody here but us chickens!

**Comment by nonamethanks** [comment]
You have to use "child:any parent:any".

**Comment by luni3359** [comment]
> You have to use "child:any parent:any".

That only results with posts that both have children and are parents themselves, all the results are both green and yellow bordered.

**Comment by nonamethanks** [comment]
Ah my bad, I misunderstood your request.

**Comment by luni3359** [comment]
Just to clarify, the desired result would be something like "any posts that have any sort relationship".

**Comment by nonamethanks** [comment]
I dug a bit into this, and it seems PostQueryBuilder needs a rewrite to handle metatags. It doesn't look like it'd be hard, just a chore.


Compare how optional tags are handled in https://github.com/danbooru/danbooru/blob/4a3057bcb762f315bbd9986c4bd49eaa7d7e8abb/app/logical/post_query_builder.rb#L75 vs metatags in https://github.com/danbooru/danbooru/blob/4a3057bcb762f315bbd9986c4bd49eaa7d7e8abb/app/logical/post_query_builder.rb#L98

Metatags basically simply lack that logical part.

**Comment by evazion** [comment]
Fixed as part of 9d3069802. `~child:any ~parent:any` now works (or `child:any or parent:any` in the new syntax).
