### ISSUE TITLE
Migrate to Twitter v2 API

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#4656]
https://developer.twitter.com/en/docs/twitter-api/early-access
https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/introduction
https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/migrate

**Comment by evazion** [comment]
This is blocked by the fact that the v2 API still can't return the URL for videos and animated GIFs:

> https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/media
>
> Media refers to any image, GIF, or video attached to a Tweet. The media object is not a primary object on any endpoint, but can be found and expanded in the Tweet object. 
>
> The object is available for expansion with ?expansions=attachments.media_keys to get the condensed object with only default fields. Use the expansion with the field parameter: media.fields when requesting additional fields to complete the object. **Note that video URLs are not currently available, only static images.**

**Comment by nonamethanks** [comment]
That's possible now, but the bigger issue is the absolutely asinine way they calculate rate limits. They're much, much worse than 1.1, so I'm not sure if there's any reason to migrate until we're forced at gunpoint.

**Comment by evazion** [comment]
I switched to the syndication API instead. This returns everything we need and it doesn't require authentication, even for NSFW tweets.

https://cdn.syndication.twimg.com/tweet-result?id=1577831592227000320
https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2Ftwotenky%2Fstatus%2F1577831592227000320&widget=Tweet
