### ISSUE TITLE
Nijie: "Download failed: couldn't find download url"

### ISSUE THREAD

**Issue by Mistars** [danbooru/danbooru#4665]
```
An error occurred: error: Sources::Strategies::Base::DownloadError - Download failed: couldn't find download url for https://nijie.info/view.php?id=410608

app/logical/sources/strategies/base.rb:158:in `download_file!'
app/logical/upload_service/utils.rb:82:in `get_file_for_upload'
app/logical/upload_service/preprocessor.rb:76:in `start!'
app/logical/upload_service/preprocessor.rb:61:in `block in delayed_start'
app/logical/current_user.rb:10:in `scoped'
app/logical/current_user.rb:24:in `as'
app/logical/upload_service/preprocessor.rb:60:in `delayed_start'
app/jobs/upload_preprocessor_delayed_start_job.rb:6:in `perform'
```
See also [forum #177907](https://danbooru.donmai.us/forum_topics/9127?page=313#forum_post_177907), [forum #178005](https://danbooru.donmai.us/forum_topics/9127?page=313#forum_post_178005) and [forum #178020](https://danbooru.donmai.us/forum_topics/9127?page=313#forum_post_178020).

**Comment by nonamethanks** [comment]
As I mentioned in the forums, @evazion should first check if the account is having issues and the Nijie tests are running properly on the live instance. On mine it all works correctly.

**Comment by evazion** [comment]
Looks like we cached a bad login cookie for Nijie. At first the strategy was failing because it returned the login page. I cleared the login cookie and now it works.

Currently we cache the login cookie for 1 week and the cookie was last updated 5 days ago. There should have been an error in the logs if the login failed, but there wasn't. So I'm guessing the cookie expired.

**Comment by nonamethanks** [comment]
@evazion it's broken again. I'm going to see if I can fix this tomorrow.

**Comment by evazion** [comment]
I reduced the cache lifetime to 1 hour and changed it to delete the cookie if we get a login prompt while trying to fetch the html page. These are bandaid solutions though because I still don't know what's causing the cookie to prematurely expire.

**Comment by nonamethanks** [comment]
Your solution is easier than what I had in mind. Let's wait a month or two and see if that fixes it. My bots are using the same cookie for about a year now so I have no idea what's causing this either.

**Comment by nonamethanks** [comment]
This hasn't happened in a while now. Closing.
