### ISSUE TITLE
Broken network link for some IPs

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4666]
Example: all the 2405: IPs in [here](https://danbooru.donmai.us/ip_addresses?search%5Bgroup_by%5D=ip_addr&search%5Buser_id%5D=782125).

![image](https://user-images.githubusercontent.com/12946050/104414240-3d6a3200-5570-11eb-85e3-6aeea200fa87.png)

**Comment by evazion** [comment]
These are Cloudflare Tor IPs. The IP lookup service we're using isn't returning any data for them and we're not handling it correctly when we don't get any data back.

https://blog.cloudflare.com/cloudflare-onion-service
