### ISSUE TITLE
Validate custom CSS

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#4678]
Custom CSS should be validated to ensure that it's syntactically valid CSS. It's possible for users to accidentally paste non-CSS into the CSS box.

**Comment by bipface** [comment]
[tokenising](https://www.w3.org/TR/css-syntax-3/#token-diagrams) , [parsing](https://www.w3.org/TR/css-syntax-3/#parser-diagrams)

**Comment by bipface** [comment]
worth noting that custom css is currently subjected to a regex transformation in [custom_css.rb](https://github.com/danbooru/danbooru/blob/692981e964e8d703a9c9743676aa1d1de0569fea/app/logical/custom_css.rb), which causes issues such as #4398. If we end up with a server-side css parser we should use it for this purpose as well

**Comment by lllusion3469** [comment]
But if you did use a proper CSS parser to add `!important`, it would almost certainly break [the workaround](https://github.com/danbooru/danbooru/issues/4385#issuecomment-608684557) to get the current regex to _not_ add it, which has [legitimate use cases](https://github.com/danbooru/danbooru/issues/4398#issuecomment-610934323). I suggested getting rid of it altogether, but it's not my decision to make (I would code migrations and whatever is necessary to prevent breakage, though).
