### ISSUE TITLE
user profile 'flags' count links to `/post_flags` with different search criteria

### ISSUE THREAD

**Issue by bipface** [danbooru/danbooru#4690]
• as a privileged user, delete any of **your own** posts via the 'delete' button in the left panel
• go to your `/profile` page — note that the 'flags' count has increased by one
• click the number, which links to `/post_flags?search%5Bcreator_name%5D={username}`
• the deleted post is not listed in the results

to fix: either the 'flags' count count should exclude such instances, or the linked search page should include them

**Comment by BrokenEagle** [comment]
In your tests are you deleting posts that were uploaded by the same user? Because those won't be shown with the `creator_id` or `creator_name` search fields, even if that user is a moderator. I found this out myself since I've self-flagged several of my own posts in the past.

**Comment by bipface** [comment]
ah yes you're right, only self-deletes seem to be affected; i'll update the steps
