### ISSUE TITLE
Better UX for disabling tooltips from the tooltips

### ISSUE THREAD

**Issue by luni3359** [danbooru/danbooru#4697]
The icon that shows up on the tooltips is very misleading, and it goes against the standard. I don't remember disabling this feature on purpose.

If you alt-tab while the tooltip is showing up and then return quickly while getting the cursor on top of the tooltip before it goes away it makes you think it's going to remain open until you click the X. The fact that there's a tooltip on the button is nearly pointless because it takes much longer for the tooltip to show up on hover than it does to click it reflexively.

![Misleading icon](https://user-images.githubusercontent.com/16832398/106944056-c564d700-66eb-11eb-8fb9-fa9af3c8fe6d.png)
_I don't think anybody would wonder what will show up after hovering on an X button._

Proposal: Perhaps instead of having an X symbol it would work better with a cog, and instead of being an instant toggle it should send users to the settings. I know that would be extremely annoying because it would move you away from the posts, so maybe it could show up some quick settings on top of the page for a user to interact with.

**Comment by nonamethanks** [comment]
I agree that it's kind of a pain because I've accidentally disabled tooltips before. A tooltip with an explicit option to disable tooltips like the newly introduced comment menu tooltip would be a way to fix this.
