### ISSUE TITLE
corrupt files throw misleading error 'Md5 confirmation doesn't match'

### ISSUE THREAD

**Issue by bipface** [danbooru/danbooru#4699]
• fill a `.png` file with garbage and try to upload it
• preprocessor throws on `validate_file_ext`, with a good error message
• submit the upload
→ leads to error page `Validation failed: Md5 confirmation doesn't match Md5`
which is of course meaningless to the user.

i'm guessing this happens because in the first request (to the preprocessor), where the actual image data is uploaded, the file is rejected, so when the upload is submitted there's no file to compare the md5 against — which is a similar scenario to #4608.
i haven't been able to figure out where this md5 comparison is actually performed though.

**Comment by nonamethanks** [comment]
This also happens when you try to upload animations from disk that are too long, or submit the upload too soon (issue #4608), or the image has an unsupported input profile (issue #4612). It's basically a generic error for whenever the upload fails. It could use some better wording for known errors.

**Comment by evazion** [comment]
Fixed as part of abdab7a0a8101e9c112b5bba51b477e9bbed3c3d.
