### ISSUE TITLE
Odd behavior on older versions of Chrome.

### ISSUE THREAD

**Issue by Anthony-B-Russo10** [danbooru/danbooru#4701]
Within the past hour of using the site on Chrome 49 the site has stopped accepting normal key input and instead redirects to the next page on a tag and the view image at full res just redirects to viewing the file itself rather then staying on the page that it is on. Though I don't fully know if this is a problem with the page or a Chrome settings issue because it worked on a slightly older version and it worked the way it is supposed to.

**Comment by bipface** [comment]
before this issue is dismissed, there may be legitimate reasons for running outdated chrome such as: old android devices which are stuck on old OS versions (and may have limited ability to download or side-load newer apps)

**Comment by nonamethanks** [comment]
Was also reported in https://danbooru.donmai.us/forum_topics/18032 by two Firefox users.
