### ISSUE TITLE
Stop auto-filling 'Other name' with Pixiv stacc names beginning in 'user_'

### ISSUE THREAD

**Issue by Kikimaru** [danbooru/danbooru#4743]
Simple really. 
It's ugly as sin & should not be encouraged for new artist entries.

**Comment by evazion** [comment]
A badly named artist tag is better than no artist tag. The people creating tags like this wouldn't create artist tags at all if we forced them to figure out names by themselves.

We could try to offer better suggestions here, such as attempting to romanize names automatically (nontrivial, especially considering things like kanji, Chinese names, names that conflict with other tags, etc), or try to pull names from other profiles (Twitter, etc). But having users not tag artists at all if they can't figure out the perfect name is not an option.

**Comment by Kikimaru** [comment]
This is not in regards to the artist tag, it's for the 'Other names' field.
