### ISSUE TITLE
Artist -> Other Names: Names with upper case characters cannot be found

### ISSUE THREAD

**Issue by Kikimaru** [danbooru/danbooru#4744]
If an artist's 'Other name' entry contains even a single upper case character, it is not possible to find the artist entry by searching for the other name.

**Comment by luni3359** [comment]
I'm getting mixed results with this. Some names with capital letters in them show up, while others don't. I can't find any patterns, whether it's just one capital letter or multiple.

**Comment by evazion** [comment]
This was fixed in e203c6f73.
