### ISSUE TITLE
BUR layout partly broken on iOS

### ISSUE THREAD

**Issue by LoginToView** [danbooru/danbooru#4747]
![](https://cdn.discordapp.com/attachments/796438141686251600/816446931190153226/image0.png)
The Request and Reason boxes take the entire horizontal space, and the example text inside the Request box stays on one line.

**Comment by evazion** [comment]
Can confirm with Chrome 86 on iOS 14. It seems that iOS doesn't support newlines in the `placeholder` attribute despite it being required by the standard.

https://developer.mozilla.org/en-US/docs/Learn/Forms#The_placeholder_attribute
https://html.spec.whatwg.org/multipage/form-elements.html#attr-textarea-placeholder
