### ISSUE TITLE
Add a way to set API keys to read-only mode

### ISSUE THREAD

**Issue by SuzakuMedli** [danbooru/danbooru#4749]
It would be convenient if I could make an API key read-only without having to go through and manually whitelist the dozens (hundreds?) of endpoints that use the GET method.

**Comment by evazion** [comment]
What do you need this for? Most applications shouldn't need access to literally everything. Giving read access to everything gives access to a number of potentially sensitive things. This includes:

* Your private dmails.
* Your personal email address.
* Your account settings.
* Your login history, including IPs and locations (not visible to users at the moment, but will be in the future)
* Your upgrade receipts (if you bought or gifted any Gold or Platinum upgrades)
* Any moderation reports you've created (https://danbooru.donmai.us/moderation_reports).
* Which forum topics you've read (https://danbooru.donmai.us/forum_topic_visits.xml).
* Your saved searches.
* Your other API keys, which can lead to privilege escalation.
* Mod-only information if you're a Mod, including things like private forum threads, flags, IP bans, mod reports, etc.

The fear here is especially untrusted third-party phone applications asking for full access then stealing private data from users.

**Comment by SuzakuMedli** [comment]
I wanted to give a script I'm writing full access to the API without having to worry about accidentally editing something. I could keep the API key set to read-only until I wanted to make an edit, toggle it, make whatever changes, then toggle it back again.

But considering the fact that this would potentially encourage users to be less careful with their API keys and permissions because they mistakenly believe that read-only means safe, I would be okay with this issue being closed.
