### ISSUE TITLE
Filesize sometimes is missing in the upload page for twitter and other sites

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4756]
The size eventually appears after a few refreshes. We should just apply it to the html like we already do for the resolutions:

https://github.com/danbooru/danbooru/blob/3b3b6b5a2c803ba1e973e1913a31440b515cbca8/app/javascript/src/javascripts/uploads.js.erb#L149-L158

**Comment by evazion** [comment]
Currently we get this from the `Content-Length` header, which is optional.

I don't think it's possible to get the filesize of an `<img>` tag in Javascript. The closest thing is the performance timing API (e.g. `performance.getEntriesByName($("#image").attr("src"))[0].decodedBodySize`), but this doesn't work for cross-domain requests (Twitter images).

https://stackoverflow.com/a/45409613

**Comment by evazion** [comment]
Fixed as part of abdab7a0a8101e9c112b5bba51b477e9bbed3c3d.
