### ISSUE TITLE
Tags should be sorted naturally, not alphabetically

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4760]
For example "Rockman 10" gets put before "Rockman 2". See screnshots.

![image](https://user-images.githubusercontent.com/12946050/110837815-02e7f180-82a2-11eb-8203-3131f24b5fd7.png)

Not sure how many places this applies to, but it also applies to taglists: https://testbooru.donmai.us/posts/80
![image](https://user-images.githubusercontent.com/12946050/110837984-39257100-82a2-11eb-891a-901a058e534c.png)

**Comment by BrokenEagle** [comment]
I found the following gem that is still being maintained that could handle this.

https://github.com/dogweather/naturally

**Comment by nonamethanks** [comment]
For things like the tags index it'd have to be done in SQL for correct pages, but that would probably be too much of a pain. At least for tag lists in posts however it should be easy enough.

**Comment by evazion** [comment]
It's possible to do in SQL but it requires a custom function and an extra index on every field sorted this way (not just `tags.name`, but potentially `wiki_pages.name`, `users.name`, `artists.name`, and anything else that would need to be sorted this way).

Inside posts I think it's rare to have tags that need to be sorted this way. You basically need a tag that a) ends with a number b) the number goes to at least 10 and c) multiple versions of the tag appear on the same post. `rockman_10` is about the only example I could find of this. Other examples include:

* `pokemon_m01` and `pokemon_ep001` tags, but these are already zero-padded, and you don't normally have multiple Pokemon movies or Pokemon episode tags on the same post anyway.
* `dragon_quest_x` and `final_fantasy_x`, but you don't often have multiple Dragon Quest or Final Fantasy characters from different games in the same post, plus these use roman numerals, so now we're in to parsing roman numerals.

https://stackoverflow.com/a/48809832
https://blog.codinghorror.com/sorting-for-humans-natural-sort-order/

**Comment by evazion** [comment]
I don't think this is worth it. I did some performance testing and found that sorting tag lists in natural order was 5x slower than alphabetical order, even with an optimized implementation. This is non-negligible considering that we render tag lists hundreds of times per second. Rendering tag lists is performance-critical because have to do it on every search and every post view.
