### ISSUE TITLE
Can't expand input fields past a certain size

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4764]
Not sure if it's just me, but on Chrome since last update I can't expand inputs manually more than this size:
![image](https://user-images.githubusercontent.com/12946050/111054271-9fa9bb00-846b-11eb-816b-6ba588c6b8a6.png)

Needless to say, for BURs and for editing wikis it's a nightmare, I basically have to copy the text into an external editor. It applies to every boxed input field on site.

The offending CSS is this:
https://github.com/danbooru/danbooru/blob/808c039f03b9b04b1a9d2e3c1df43a63ffb0eecd/app/javascript/src/styles/common/simple_form.scss#L66-L69
(added here): 
https://github.com/danbooru/danbooru/commit/b8d95ace64d78ffef2b663930235e590f0e672d0#diff-6ba88d7d20854047dfe6541119b7ba63270fdccc8f1b4d1df785e1ebecc23afaR57-R60

Was this intentional, or a side effect?

Seems it's also not possible to fix this with custom CSS (see [this discord discussion](https://discord.com/channels/310432830138089472/310846683376517121/820473736146321439))

**Comment by evazion** [comment]
The intended behavior is that textareas are full screen width on small screens (screens less than 60rem or 960px wide), and 60rem / 960px wide on large screens. I guess a media query would be better here. Just setting `width: 60rem` will make it too wide for small screens.

**Comment by nonamethanks** [comment]
Having this size as default is ok, it's just the fact that it cannot be resized that is terrible for large bodies.
