### ISSUE TITLE
When you post a comment on a picture over a certain age, no-bump should be selected automatically

### ISSUE THREAD

**Issue by deusexcalamus** [danbooru/danbooru#4769]
As the subject says, this might help people avoid (unintentionally) bumping years old pictures with replies.

Not sure what the threshold should be, though.

**Comment by luni3359** [comment]
I don't see why this should be necessary. Encouraging activity by default seems like a positive thing to me.

**Comment by deusexcalamus** [comment]
> 
> 
> I don't see why this should be necessary. Encouraging activity by default seems like a positive thing to me.

Shrug. My reply was just a suggestion, the real target is the main post :p

**Comment by Thayol** [comment]
To be honest this would be something wanted as a user setting, but after reading Luni's comment, I believe we don't need this feature. Thinking twice before posting is better than having a default no-bump because there will be no/late feedback for inappropriate comments.

**Comment by nonamethanks** [comment]
Gonna close as wonfix since it doesn't look like there's interest in this from the big boss.

There's already a bump limit after X comments so people commenting on long threads already don't bump those anyway, and I don't think it's necessary either to auto-not-bump old posts. Also it makes it harder to find rulebreaking comments.

**Comment by luni3359** [comment]
Does that mean that the there won't be any bumps after X comments, even if the post is trending? If so then maybe that should be different, for the sake of user engagement.

**Comment by nonamethanks** [comment]
The bump limit currently is 40, it's defined here https://github.com/danbooru/danbooru/blob/master/config/danbooru_default_config.rb#L147
