### ISSUE TITLE
docker-compose.simple.yaml - fails to find mimemagic gem

### ISSUE THREAD

**Issue by bipface** [danbooru/danbooru#4776]
the `bundle install` step fails with
`your bundle is locked to mimemagic (0.3.5), but that version could not be found in any of the sources listed in your gemfile`

it seems manually bumping the gemfile to use 0.3.6 allows the build to succeed

**Comment by evazion** [comment]
Looks like another leftpad moment.

https://news.ycombinator.com/item?id=26566925
https://github.com/rails/rails/issues/41750
https://github.com/minad/mimemagic/issues/97
https://github.com/minad/mimemagic/issues/98

**Comment by Vornir** [comment]
I'd hate to reopen this issue right after it was closed, but mimemagic has updated 0.3.6 to 0.3.7 which means the build fails

**Comment by evazion** [comment]
0.3.7 is still partly broken because it adds a new dependency on `shared-mime-info` 2.0, but 2.0 isn't available in Ubuntu 20.04 or Debian stable.

hxxps://github.com/mimemagicrb/mimemagic/issues/108

**Comment by evazion** [comment]
Fixed by upgrading to Rails 6.1.31, which dropped the dependency on mimemagic.
