### ISSUE TITLE
Some thumbnails have an overly large filesize

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#4777]
Some thumbnails are overly large, sometimes over 1MB in size:

https://cdn.donmai.us/preview/f5/5e/f55ea296db2c6ddc4ea428e62f479369.jpg
https://cdn.donmai.us/preview/52/c2/52c2bc56999f52c60c9a48df82b1a1d8.jpg
https://cdn.donmai.us/preview/6b/6e/6b6e8a863931fd80c10df4612c70600d.jpg

`find preview -size +100k -ls` reports 2400 thumbnail images over 100kb large. Judging by `exiftool` it looks like they contain unstripped metadata.

**Comment by nonamethanks** [comment]
I just regenerated https://cdn.donmai.us/preview/f5/5e/f55ea296db2c6ddc4ea428e62f479369.jpg and now it's 6kb in size, so it seems the thumbnails are now generated correctly at least. It should only be a matter of regenerating the existing large ones.

**Comment by evazion** [comment]
Fixed.
