### ISSUE TITLE
wildcard searches yield wrong results when no matches

### ISSUE THREAD

**Issue by bipface** [danbooru/danbooru#4778]
example:
[/counts/posts?tags=nosuchtag*](https://danbooru.donmai.us/counts/posts?tags=nosuchtag*)
```
Post count for nosuchtag*: 4403927
```

when there *are* matches, it works fine:
[/counts/posts?tags=mtd_*](https://danbooru.donmai.us/counts/posts?tags=mtd_*)
```
Post count for mtd_*: 6 
```

**Comment by Thayol** [comment]
Dupe of issue #4435
