### ISSUE TITLE
iqdb.org refused to connect.

### ISSUE THREAD

**Issue by htomeload** [danbooru/danbooru#4785]
I don't know what happen, I just use this site with Image Search Options Extension until about at least 2 weeks ago I guess, I think it maybe random server problem so I stop using it but even now problem still present. I think my IP might be blocked for unknown reasons.

My IPV4: 49.48.35.254

**Comment by nonamethanks** [comment]
iqdb.org is not hosted by us. 
See https://twitter.com/SauceNAO/status/1383592814005551109 and http://saucenao.blogspot.com/2021/04/recent-events.html for details on why it's down.
