### ISSUE TITLE
Add support for Reddit

### ISSUE THREAD

**Issue by KalpacMuskoxen** [danbooru/danbooru#4786]
Under normal circumstances, avoiding Reddit like the plague would be perfectly reasonable. However, given the popularity of artists who post their work exclusively on r/hololive, integrated support may be a justifiable sin if only to make it easier to post artwork from there.

**Comment by nonamethanks** [comment]
I don't like the idea of adding support for Reddit, because the vast majority of posts from there are reposts, so I'm afraid it would encourage users to post third-party compressed samples.

**Comment by GlassedSilver** [comment]
I agree with nonamethanks

**Comment by nonamethanks** [comment]
Gonna close this as wontfix because I doubt it's going to ever be done.
