### ISSUE TITLE
Default Admin Password

### ISSUE THREAD

**Issue by ASimpleUserAccount** [danbooru/danbooru#4789]
I was able to successfully install danbooru, as stated in the quickstart guide.
Sadly i cannot find the password for the already existing Admin account.
Where can i find it?

**Comment by BrokenEagle** [comment]
You create a user, which includes username/password. The first user created becomes an admin account.

**Comment by ASimpleUserAccount** [comment]
Sorry for my late Answer.
I have set up a multible new VM and created a new User.
The Problem is, the User i create has the UserID 2, there is/was already a UserID 1 an its called "DanbooruBot".
This "DanbooruBot" already exists everytime i install/set up the server.
"DanbooruBot" is Admin and my User is only a member ...
![DanbooruBot](https://user-images.githubusercontent.com/83498789/117245828-c1a43600-ae3b-11eb-827b-85484710dc59.PNG)

Any idea on how to delete this user or log in as that user?

**Comment by Thayol** [comment]
This was resolved in issue #4795 as [stated](https://github.com/danbooru/danbooru/issues/4795#issuecomment-835399085) by @ASimpleUserAccount
