### ISSUE TITLE
video_with_sound tag sometimes not added automatically

### ISSUE THREAD

**Issue by bipface** [danbooru/danbooru#4791]
reported by brokeneagle

- upload `4734d9ca3c728b840a5d2a8419248b34.mp4` ( [post #4498271](https://danbooru.donmai.us/posts/4498271) )
- tag `video` is added automatically but not `video_with_sound`

debugging reveals that the code is able to detect the audio channel, yet somehow the tag isn't applied:

```rb
   70:       tags << "video_with_sound" if media_file.has_audio?
=> 71:       tags << "animated_gif" if media_file.file_ext == :gif && media_file.is_animated?
   72:       tags << "animated_png" if media_file.file_ext == :png && media_file.is_animated?
   73:       tags.join(" ")
   74:     end
   75:
(byebug) eval tags
["video_with_sound"]
(byebug) eval media_file.has_audio?
true
```
( [https://github.com/danbooru/danbooru/blob/master/app/logical/upload_service/utils.rb](https://github.com/danbooru/danbooru/blob/master/app/logical/upload_service/utils.rb) )

further confusion [here](https://github.com/danbooru/danbooru/issues/3915#issuecomment-423609856) where it sounds like the feature is dismissed as *wontfix*, yet the code is there and getting called

**Comment by nonamethanks** [comment]
Could it be related to issue #4041?

**Comment by BrokenEagle** [comment]
This happened again on [post #4524238](https://danbooru.donmai.us/posts/4524238).

**Comment by evazion** [comment]
This is no longer relevant since `sound` is no longer automatically tagged at all due to the high false positive rate from silent audio tracks.
