### ISSUE TITLE
The first user created will not be an administrator account

### ISSUE THREAD

**Issue by pinkdark** [danbooru/danbooru#4795]
The quickstart installation was successful and I created an account (users / new)
But the account level is a member. I'm not an administrator.
How can I get an administrator account?

**Comment by nonamethanks** [comment]
Did you run [the rake tasks](https://github.com/danbooru/danbooru/blob/master/INSTALL.debian#L161)? Or are you running it via docker?

**Comment by ASimpleUserAccount** [comment]
I have the same Problem. I am running it in Docker.
First User (UserID 1) already exists directly after the installation and is called "DanbooruBot" (Admin).
The Account i created is UserID 2 and its only a Member.

**Comment by nonamethanks** [comment]
FYI you can change the user level of any account directly from the database, as a temporary solution.

**Comment by ASimpleUserAccount** [comment]
Can you explain me how to do that?

**Comment by pinkdark** [comment]
> Did you run [the rake tasks](https://github.com/danbooru/danbooru/blob/master/INSTALL.debian#L161)? Or are you running it via docker?

I'm running with docker.

**Comment by pinkdark** [comment]
I changed from the database and was able to become an administrator.
The following is a memo.

`update users set level=50 where id='2';`

**Comment by pinkdark** [comment]
I think the database name and user name will be the same as the docker-compose.yaml you created.
For example, "danbooru"
I'm not familiar with it, so I'm not sure if it's helpful, but I'll show you the procedure.
My environment (VMware, Ubuntu 20.04.2 LTS)

start up
`cd danbooru/config/docker
sudo docker-compose up -d`

find container ID
`sudo docker ps -f "name = postgres"`

access container
`sudo docker exec -it <CONTAINER_ID_HERE> /bin/bash`

connect to psql
`psql -h <CONTAINER_ID_HERE> -d <DBNAME_HERE> -U <USERNAME_HERE>`

change account level
`update users set level=50 where id='2';`


I hope it helps.

**Comment by ASimpleUserAccount** [comment]
Thanks this did work!
Sadly, i have an new problem. If i post a picture i cant "see" it (The webrowser (Edge/Firefox/Chrome) doesn't display it ... but it is uploaded and approved).

**Comment by nonamethanks** [comment]
FYI if you want your account to be owner level it should be 60, not 50.

**Comment by evazion** [comment]
This is somewhat tricky because if you have a public facing Danbooru instance, and you don't already have an Owner-level user, then the next user to sign up will become the Owner.
