### ISSUE TITLE
Twitter strategy mistakenly replaces any @name with a twitter link

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4796]
This means skeb, pawoo and similar links using @-style references are converted to broken twitter links. Try for example fetching the commentary from https://twitter.com/i/web/status/1384357920993779720

Caused by this:
https://github.com/danbooru/danbooru/blob/e36fb6fee3acab168fc2e0ea45410027a5f8f295/app/logical/sources/strategies/twitter.rb#L203

**Comment by tmarkandeya** [comment]
Replacing it with (?<!\/)@([a-zA-Z0-9_]+)\b should work
From https://discord.com/channels/310432830138089472/310846683376517121/869385947257647145

**Comment by Unbreaky** [comment]
Is this ever gonna get fixed? It's quite annoying.

**Comment by NamelessContributor** [comment]
The hashtag regex is also wrong, see for example [post #5822571](https://danbooru.donmai.us/posts/5822571).

I found [this code](https://github.com/twitter/twitter-text/blob/master/java/src/main/java/com/twitter/twittertext/Regex.java) from Twitter describing valid hashtags but most importantly they can't start with a number and most special characters should be treated the same as a space.
