### ISSUE TITLE
CORS error on non-danbooru subdomains causes ugoira files to not display when logged in

### ISSUE THREAD

**Issue by registered-to-post-this** [danbooru/danbooru#4799]
When a user is logged in, ugoira files (example: https://safebooru.donmai.us/posts/4504920) on subdomains other than danbooru.donmai.us will not display due to a "CORS Missing Allow Origin" error:
![1](https://user-images.githubusercontent.com/50346643/118054005-604bfd80-b33a-11eb-9b03-a36d5cc4f398.png)

This error appears on all subdomains that were tested (safebooru, shima, kagamihara, saitou).
This error does not appear to affect filetypes other than .zip or users that are not logged in.
This error affects 2 of 3 browsers that were tested (Firefox 88.0.1, Chrome 90.0.4430.212). Pale Moon 29.2.0 is unaffected for reasons which are a mystery to me.

**Comment by luni3359** [comment]
This needs some more testing from other people. I tried that link on Chromium 91, Firefox 88 and 89, and I didn't find any errors. Disabled the cache just in case and I wasn't getting any errors loading them either.

**Comment by Thayol** [comment]
This only happens for me if I set the default width to original.

## Steps to reproduce
* Open the [settings](https://shima.donmai.us/settings)
* Set **Default image width** to `original`
* Open any `.webm` ugoira ([example](https://shima.donmai.us/posts/4584576)) on a non-danbooru subdomain

**Comment by Thayol** [comment]
I am pretty sure that issue #4780 is closely linked with this one. The site should serve files from their own URLs, regardless of CORS settings.

**Comment by evazion** [comment]
Should be fixed now. All images are now served from `cdn.donmai.us` regardless of which subdomain you're on.
