### ISSUE TITLE
Update API documentation after disabling of "is_favorited"

### ISSUE THREAD

**Issue by LilyStilson** [danbooru/danbooru#4803]
At the current moment (23 May 2021) [API documentation](https://danbooru.donmai.us/wiki_pages/api%3Aposts) still contains disabled field `is_favorited`. If you will try to fetch a post through an API, it won't return you an `is_favorited` field, because it was disabled, as stated in this [comment](https://github.com/danbooru/danbooru/issues/4652#issuecomment-754993802) on #4652.

Please, update API documentation with current API changes.

**Comment by nonamethanks** [comment]
Done.
