### ISSUE TITLE
Change creator to creator_id on forum post attributes

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4807]
It makes it difficult to properly get the information on the user, or filter by user, especially since names can change or contain non-ASCII/printable characters. This problem only seems to exist for forum posts on the topic show page. The forum index page works just fine.

https://github.com/danbooru/danbooru/blob/748fcdddcf15a67a6cf003c149b3e4d4bf92208c/app/components/forum_post_component/forum_post_component.html.erb#L4

I'm not sure if this problem exists elsewhere (using the user name instead of the user ID), but if it does, then those should be switched over as well.

**Comment by evazion** [comment]
This will be a breaking change if anyone uses this.
