### ISSUE TITLE
Submitting an artist update creates a new version even if no changes have been made

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4809]
The following is not the only time, but the most recent occurrence.

**Example:** https://danbooru.donmai.us/artist_versions?search[id]=922287

**Comment by nonamethanks** [comment]
That happens with every version, including post edits. issue #4354

**Comment by luni3359** [comment]
If the underlying problem is the same, this issue should be closed in preference of the earlier one.

**Comment by evazion** [comment]
I can't reproduce this. I assume these were caused by version merging, as per #4354.
