### ISSUE TITLE
Support for embedded posts/images in wiki pages

### ISSUE THREAD

**Issue by luni3359** [danbooru/danbooru#4828]
Adding the ability for users to put images in wikis to better illustrate what they stand for can really help with user experience. It can also solve the problem of wiki previews showing really lewd pictures, or pictures where the focus of the tag is obfuscated in the selected picture. This way we could clearer examples to the reader.

There was an existing issue (#2538) about it before, but it was closed without discussion.

**Comment by evazion** [comment]
This was implemented in f56256ba7.
