### ISSUE TITLE
newpool: metatag doesn't parse correctly

### ISSUE THREAD

**Issue by bipface** [danbooru/danbooru#4848]
- enter `newpool:'my new pool'` in the tag edit field and save
- → expect: new pool is generated titled `my new pool`
- → actual: new pool is generated titled `'my` and the post is tagged `new`, `pool`

---

- enter `newpool:new\ pool` in the tag edit field and save
- → expect: new pool is generated titled `new pool`
- → actual: new pool is generated titled `new\` and the post is tagged `pool`

**Comment by nonamethanks** [comment]
You have to use double quotes.

**Comment by evazion** [comment]
You can now use double-quoted strings, single-quoted strings, or backslash-escaped strings with metatags:

* `newpool:"foo bar"`
* `newpool:'foo bar'`
* `newpool:foo\ bar`

This works with any tag edit metatag, most notable with `source:`.
