### ISSUE TITLE
"order:score" times out

### ISSUE THREAD

**Issue by ddevault** [danbooru/danbooru#4854]
Searching for all posts ordered by score times out:

https://danbooru.donmai.us/posts?tags=+order%3Ascore

This used to work pretty well, so I'm assuming there was a regression or the database grew large enough to push it over the threshold.

**Comment by nonamethanks** [comment]
Can confirm, it takes a long while for me too with a mod account and times out in incognito.

**Comment by evazion** [comment]
This works now, even for users with a low search timeout. There were various database upgrades in the last few months that probably made this possible - new database server, latest Postgres version, and schema changes to reduce the size of the posts table.

**Comment by ddevault** [comment]
Thanks!
