### ISSUE TITLE
Theirs no API version of this URL

### ISSUE THREAD

**Issue by nonetrix** [danbooru/danbooru#4861]
The: issue:
 - http://gelbooru.com/index.php?page=post&s=random doesn't seem to have a API 
 - https://gelbooru.com/index.php?page=dapi&s=random&json=1 returns nothing

Ways to solve this maybe:
- return the post in JSON or XML
- make a error message if this can't be added for some reason, for example
```
{"Error": "Invalid url"}
```
I want to make a Discord bot that grabs a random post, I can just grab the redirect but this isn't exactly ideal in my opinion

If I am somehow messing something up I am extremely sorry for wasting your time

**Comment by nonamethanks** [comment]
This repository is for [Danbooru](https://danbooru.donmai.us/), not Gelbooru.

**Comment by nonetrix** [comment]
Sorry for getting to two confused somehow 🥲
