### ISSUE TITLE
Retire deletion appeal thread

### ISSUE THREAD

**Issue by kittey** [danbooru/danbooru#4863]
The deletion appeal thread lost its function quite a while ago and all users figured out that they have to use the appeal function. By now, all approvers should have realized that the deletion appeal thread is just legacy baggage and it should be retired.

Why? The deletion appeal thread is just cluttering the forum notifications at this point. Quite often, I see the Forum link in italics because there’s a new forum post, but when I go check, it’s just the deletion appeal thread again.

**Comment by evazion** [comment]
The initial purpose was just to appease users of the old thread, and to nag approvers who only pay attention to status:pending. I agree it causes too much noise.
