### ISSUE TITLE
random=true in api only returns one post

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4867]
https://danbooru.donmai.us/posts.json?limit=15&random=true should return 15 results, not one, because https://danbooru.donmai.us/posts?limit=15&random=true works fine.

**Comment by Midorina** [comment]
Can reproduce. It has started happening this morning.

**Comment by nonamethanks** [comment]
It could be caused by the pudate to pundit 2.1.1: see https://github.com/varvet/pundit/blob/master/CHANGELOG.md
