### ISSUE TITLE
Unexpected results when sorting by random

### ISSUE THREAD

**Issue by SuzakuMedli** [danbooru/danbooru#4870]
**Post order is no longer randomized when sorting by random.**
Random posts are now returned in descending order by ID when sorting by random, they used to be returned in a random order.

**Sorting by random does not return all posts for searches with a low post count.**
When getting random posts from a search with a low post count, a limited number of results are returned.

For example, I get 15 results when searching [dai_(dragon_quest)](https://danbooru.donmai.us/posts?tags=dai_(dragon_quest)), I expect to get the same 15 results in a random order when searching [dai_(dragon_quest) order:random](https://danbooru.donmai.us/posts?tags=dai_(dragon_quest)+order:random), but instead I get a variable number of results each time I repeat the search. Using a higher limit increases the number of results returned on average.

**The `random` URL parameter effectively allows users to add `order:random` to their search without it counting against their tag limit.**
An anonymous/member level user can search for https://danbooru.donmai.us/posts?tags=scenery+no_humans&random=1, but not https://danbooru.donmai.us/posts?tags=scenery+no_humans+order:random, despite them technically being the same search.

You can also use it to do things you aren't normally able to do, like sort random posts by score.
https://danbooru.donmai.us/posts?tags=rating:safe+order:score&random=1 should be the same as https://danbooru.donmai.us/posts?tags=rating:safe+order:score+order:random, but the latter doesn't work because you can't use the same metatag twice in one search.

It also isn't mentioned anywhere in the documentation. I would expect to find it in [help:common_url_parameters](https://danbooru.donmai.us/wiki_pages/help:common_url_parameters).

**Comment by evazion** [comment]
Fixed in 0baca68 by adding a `random:N` metatag and making `order:random` truly random. The `random` URL param now redirects to a `random:N` search.
