### ISSUE TITLE
/uploads: "possible unmatched constraints" error

### ISSUE THREAD

**Issue by RaisingK** [danbooru/danbooru#4873]
Uploading post #4756764 sent me to this error page, though the upload itself still succeeded:

    No route matches {:action=>"show", :controller=>"posts", :id=>nil}, possible unmatched constraints: [:id] Did you mean? post_url posts_url posts_path post_atom_url

    ActionController::UrlGenerationError exception raised
    app/views/uploads/show.html.erb:25

**Comment by nottalulah** [comment]
Duplicate of #4393

**Comment by nonamethanks** [comment]
Closing in favor of the older one.
