### ISSUE TITLE
Delete disapprovals when a post enters the modqueue

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4876]
Since approvers that have already disapproved won't see the posts in the upload queue anyways.

**Comment by nonamethanks** [comment]
The solution to this problem is to purge disapprovals, not block appeals.

**Comment by BrokenEagle** [comment]
Well, whatever the solution needs to be, because currently users are wasting their appeals.

**Comment by BrokenEagle** [comment]
Changed the title to reflect what probably should be done, i.e. keep disapprovals around for unapproved posts until they are put back into the modqueue with an appeal, or approved posts when they are put back into the modqueue with a flag.
