### ISSUE TITLE
"Access Denied" after submitting an upload

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#4880]
Two reported instances where submitting an upload redirected to an "Access Denied" message in the last week or so. 

First instance happened when two users were trying to upload a large (~50MB) mp4, second instance happened when a user clicked submit repeatedly while having internet issues. The latter also apparently caused a double upload, somehow ([post #4775940](https://danbooru.donmai.us/posts/4775940) and [post #4775938](https://danbooru.donmai.us/posts/4775938)).

Also worth noting that my upload which gave me the permission denied error later redirect to the post which was credited to another user, rather than showing an error page because it was a duplicate.

Maybe related to issue #4393?

**Comment by nottalulah** [comment]
Possibly caused by this function calling `.first` which could return an upload not belonging to that user, could mean the uploader_id is overwritten so when the next user submits their upload it no longer belongs to them.

https://github.com/danbooru/danbooru/blob/bc73d47643b217ca30efebb864cd0eb4f13632b2/app/logical/upload_service/preprocessor.rb#L45-L51

**Comment by nottalulah** [comment]
Apparently the reason for the double upload involved the user opening the upload page before the upload was revised, and since Danbooru had already downloaded the old file, it created a post from it. A similar thing happened today where a user uploaded an image from a tab they had open for a few hours which was revised in the interim, and that caused the source to be set to the new image URL rather than the old one (so the timestamp didn't match).

**Comment by evazion** [comment]
Should be fixed as part of abdab7a0a8101e9c112b5bba51b477e9bbed3c3d.
