### ISSUE TITLE
Get rid of search timeout

### ISSUE THREAD

**Issue by thomasflrs** [danbooru/danbooru#4896]
My internet isn't that great, so every time I try to search something I get the search timeout. Please get rid of that function so that I can actually use the website.

**Comment by nonamethanks** [comment]
The search timeout is not based on your connection, but on the time that the database takes to find results. It's determined by how complex a query is, your connection's quality has no impact on it.

**Comment by evazion** [comment]
The database server has been upgraded. This should help significantly with search timeout errors.

https://danbooru.donmai.us/forum_topics/19606
