### ISSUE TITLE
Duplicate disapprovals

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4901]
https://danbooru.donmai.us/post_disapprovals?commit=Search&search%5Border%5D=id_desc&search%5Bpost_id%5D=4834905

![image](https://user-images.githubusercontent.com/12946050/136694009-690f6324-fed8-403e-8301-77c3c1a16ffe.png)

I couldn't duplicate it by spamming the disapproval button so not sure how it's happening.

**Comment by nottalulah** [comment]
https://testbooru.donmai.us/post_disapprovals?commit=Search&search%5Border%5D=id_desc&search%5Bpost_id%5D=119

Spammed "no interest" in modqueue with a 3 second delay network filter.
