### ISSUE TITLE
Prevent artist entries from being made on disambiguation tags

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#4908]
ref. [artist #197730](https://danbooru.donmai.us/artists/197730), previously with [artist #53775](https://danbooru.donmai.us/artists/53775) and [artist #212836](https://danbooru.donmai.us/artists/212836)

People will accidentally make artist tags using names that have disambiguation wikis. Perhaps just disallow creation of an artist tag if a tag already has a wiki, or give a warning requiring confirmation when doing so.

**Comment by evazion** [comment]
f8aa985a16635a9e99a257a89b619e86f22810ea forbids making artist entries for deprecated tags. Ambiguous tags should be marked as deprecated.
