### ISSUE TITLE
Wrong color for certain samples

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4920]
Compare the full size and sample for this post: https://danbooru.donmai.us/posts/4909574?q=parent%3A4909574

**Comment by evazion** [comment]
More test images:

https://danbooru.donmai.us/media_assets?search%5Bmetadata%5D%5BICC_Profile%3AProfileDescriptionML%5D=Cintiq+Pro+13
https://danbooru.donmai.us/media_assets?search%5Bmetadata%5D%5BICC_Profile%3ARedMatrixColumn%5D=0.5918+0.25865+0.00502
https://danbooru.donmai.us/media_assets?search%5Bmetadata%5D%5BICC_Profile%3ABlueMatrixColumn%5D=0.14488+0.09674+0.75648
https://danbooru.donmai.us/media_assets?search%5Bmetadata%5D%5BICC_Profile%3AGreenMatrixColumn%5D=0.23277+0.68282+0.06836

The color profile isn't being respected for some reason when the image is resized.
