### ISSUE TITLE
Wiki pages sometimes have the wrong color for tags on dark mode

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#4922]
Wrong colors:
![firefox_2021-11-15_08-12-59](https://user-images.githubusercontent.com/26291500/141780202-61fb78f6-fe36-439a-ad2a-026571fe34ac.png)
Expected colors:
![firefox_2021-11-15_08-13-42](https://user-images.githubusercontent.com/26291500/141780238-101b2ac0-69e8-4bb6-91d3-86b1feaeb169.png)

It consistently happens for me on https://danbooru.donmai.us/wiki_pages/rnd.jpg.html

**Comment by BrokenEagle** [comment]
I get the expected colors on both Chrome and FIrefox.

- Chrome 95.0.4638.69 (64-bit)
- Firefox 87.0 (64-bit)

It could be a caching issue, or some kind intermittent bug on the browser. Restarting the browser/OS could perhaps fix it. Also one could try clearing the cache or trying on a new browser profile.

**Comment by nottalulah** [comment]
Seems it's just a bug with some completely unrelated stylesheet (basically trying to match `*wiki*.jp*` which also matched `/wiki_pages/rnd.jpg`). I didn't realize it was matching because I have Stylus tucked away in some menu where I never see the icon.
