### ISSUE TITLE
"Show scores" setting should be preserved

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4930]
If you go away from the posts page (like to go on the forums) and then come back to it, the buttons are gone and you have to do a full page refresh to get them back. When it was a mode, it used to be preserved across pages.

**Comment by BrokenEagle** [comment]
As an addendum to this request, it would be nice if this value was available on the HTML `<body>`, that way, custom CSS selectors can be set based upon whether the score mode is on or off.

**Comment by evazion** [comment]
> As an addendum to this request, it would be nice if this value was available on the HTML `<body>`, that way, custom CSS selectors can be set based upon whether the score mode is on or off.

Added `data-cookie-post-preview-show-votes` to the <body> tag, and a `.post-preview-show-votes` class to thumbnails.
