### ISSUE TITLE
'pool_string' doesn't show up in the api

### ISSUE THREAD

**Issue by hiocas** [danbooru/danbooru#4936]
In testbooru post 209 is in a pool, the endpoint https://testbooru.donmai.us/posts/209.json does have the 'pool_string' field.

In danbooru post 3126673 is in a pool but the endpoint https://danbooru.donmai.us/posts/3126673.json doesn't have the 'pool_string' field.

In the wiki (https://danbooru.donmai.us/wiki_pages/api%3Aposts) 'pool_string' is written so I'm assuming it's not supposed to be only in testbooru.

**Comment by nonamethanks** [comment]
pool_string was removed from the api a while ago, see https://github.com/danbooru/danbooru/commit/7d503f088e732e4da27447d40990707eae112158


> 
> If you need to see which pools a post belongs to, do this:
> 
> * https://danbooru.donmai.us/pools.json?search[post_ids_include_any]=318550

I've updated the wiki page.

Aside from that, @evazion Testbooru needs to be updated, it's over 2 months behind in terms of code.

**Comment by evazion** [comment]
> Aside from that, @evazion Testbooru needs to be updated, it's over 2 months behind in terms of code.

Fixed.
