### ISSUE TITLE
random=true being counted as a tag

### ISSUE THREAD

**Issue by redblade7** [danbooru/danbooru#4939]
Not sure if this is the place to report this, but since 12/9/2021, the following call to the API fails:

https://danbooru.donmai.us/posts.json?random=true&tags=bound+1girl&limit=1

It redirects to:

https://danbooru.donmai.us/posts.json?limit=1&tags=1girl+bound+random%3A1

and gives the error "You cannot search for more than 2 tags at a time." when there are only 2 tags.

No problems with the tag count when searching via the Web site.

**Comment by smowtenshi** [comment]
https://danbooru.donmai.us/forum_posts/202063 should make it clear

**Comment by evazion** [comment]
Working as intended as per #4870 and 0baca68a377eeb6b9d42bdaa640478016c24f8c8. The random parameter has been replaced by a tag.
