### ISSUE TITLE
Score/Vote buttons missing from /users/123 pages

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4941]
Thumbnails in the profile/users pages should show those controls like everywhere else.

**Comment by BrokenEagle** [comment]
They're not shown everywhere else. Only on the non-post/comment pages. For example, the following gallery type pages don't have them either.

- pool gallery
- pool show
- fav group show
- wiki show
- artist show

There is also all of the other pages with thumbnails shown for each item:

- post votes index
- post versions index page
- upload index
- post approvals index
- post appeals index
- post flags index
- post replacements index
- artist commentaries index
- artist commentary versions index

For myself at least, I don't see the need to have score controls on every single page. I think it's fine to have them mostly on just the post and comment pages. Sure it might be a bit inconvenient, but I think it looks cleaner as a user interface. We also don't have tag editing or tag scripting on other pages either.

The one exception to this would be the post index-like pages, such as the popular, curated, and most viewed pages. Vote controls are missing on all of those, and those should probably have them.

**Comment by nonamethanks** [comment]
This seems to have been fixed as a side effect of the april fools' reactions.
