### ISSUE TITLE
Don't Add Comments to Posts When Doing Post Replacements

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4946]
Since post replacements now have their own records which have all of the same information, I see no reason that these should still be added, and they can disrupt the conversation.

If this is still desired for situational awareness, then perhaps comments should be given a boolean or category so that a portion of them can be hidden by users if they desire. One advantage to this approach is that the comments that my image scanner (and RaisingK et al) adds to posts could also be hidden.

If we do categories, then we could divide the conversations even further, which would benefit a few other situations, such as translation notes or requests.

Based on that, here are a few category ideas:

- General
- Translation
- Request (i.e. character request, etc)
- Technical/System

**Comment by evazion** [comment]
Removed replacement comments.

Comment categories make the comment system too complicated. Commenting should be as simple as writing your message and clicking post. Your shouldn't have to think about what category your comment fits into. Or have users chastise you for using the wrong category.

I'd really prefer if all bot actions were performed with dedicated bot accounts. There are a lot of other bot activities like automated tag edits, artist edits, commentary edits, and forum posts that ought to be separate from normal account activity. I can provide limited-access DanbooruBot API keys for doing things like posting comments as DanbooruBot if necessary.

**Comment by BrokenEagle** [comment]
Yeah, one reason I haven't been using a bot account is because it doesn't have the same permissions that my Builder level account does. If it's possible to get a bot account I create upgraded to Builder, then I would start using that instead for all of my automated actions.

@evazion I created a new account just now for this purpose. I'll wait until it's upgraded though to start using it. It only needs Builder permission and not Unlimited Uploads.

- **BrokenEagleBot:** https://danbooru.donmai.us/users/861076

For the DanbooruBot thing, I think it would be best to keep those as server actions only, and leave other bot actions to other accounts for better accountability.

**Comment by nonamethanks** [comment]
I'm going to slowly switch to bot accounts too myself, but it's going to take some time as I have a lot of spaghetti code I wrote years ago that needs to be ported.

@BrokenEagle I gave your bot builder.

**Comment by BrokenEagle** [comment]
Ah, many thanks for that. I went ahead and switched most of my code over to the new account.

I'll be keeping some things under my old account still though, like for instance some of my artist code, since it basically just does the heavy work of checking the URL active status, plus looking for additional URLs to add, but it's only done on a singular basis, and I manually have to verify everything and sometimes cleanup afterwards.

Anything that is mostly hands-off though will now go under the new account.
