### ISSUE TITLE
Failed to run Danbooru using docker-compose: Operation not permitted

### ISSUE THREAD

**Issue by nofmal** [danbooru/danbooru#4967]
I'm having trouble running Danbooru using Docker Compose on Arch Linux.

```shell
danbooru_docker-postgres-1  | chmod: changing permissions of '/var/lib/postgresql/data': Operation not permitted
danbooru_docker-postgres-1 exited with code 1
danbooru_docker-cron-1      | http://danbooru:3000 not up yet; retrying in 5s
danbooru_docker-jobs-1      | http://danbooru:3000 not up yet; retrying in 5s
danbooru_docker-jobs-1      | http://danbooru:3000 not up yet; retrying in 5s
danbooru_docker-cron-1      | http://danbooru:3000 not up yet; retrying in 5s
danbooru_docker-danbooru-1  | rails aborted!
danbooru_docker-danbooru-1  | ActiveRecord::ConnectionNotEstablished: could not translate host name "postgres" to address: Name or service not known
danbooru_docker-danbooru-1  | 
danbooru_docker-danbooru-1  | 
danbooru_docker-danbooru-1  | Caused by:
danbooru_docker-danbooru-1  | PG::ConnectionBad: could not translate host name "postgres" to address: Name or service not known
danbooru_docker-danbooru-1  | 
danbooru_docker-danbooru-1  | Tasks: TOP => db:prepare
danbooru_docker-danbooru-1  | (See full trace by running task with --trace)
danbooru_docker-danbooru-1 exited with code 1
danbooru_docker-cron-1      | http://danbooru:3000 not up yet; retrying in 5s
danbooru_docker-jobs-1      | http://danbooru:3000 not up yet; retrying in 5s
^CGracefully stopping... (press Ctrl+C again to force)
```

Here's the docker version I use:

```shell
$ docker --version && docker-compose version
Docker version 20.10.12, build e91ed5707e
Docker Compose version 2.2.3
```

**Comment by nonamethanks** [comment]
It looks like the postgres container does not have the permissions to modify [the danbooru-data volume](https://github.com/danbooru/danbooru/blob/master/docker-compose.yaml#L93).  
Just throwing random guesses here, but how are you launching docker? Is the user you're launching docker-compose with in the docker group? If not, is your docker installation configured to be rootless (https://docs.docker.com/engine/security/rootless/)? Have you tried deleting and recreating that volume (if this is your first time running, if you have an existing installation don't do that or it'll nuke the data)?

**Comment by nofmal** [comment]
My user is already in the `docker` group, but nothing worked. I also tried appending `user: root` into the postgres service and force-recreated the whole thing, but to no avail.

**Comment by nonamethanks** [comment]
user: root in my experience is a bad idea because it modifies the permission of whatever it's touching in the actual filesystem.

If you do `ls -ltrah /var/lib/docker/volumes/danbooru-data` what do you see? There should be a folder in there assigned to the docker group. Try manually removing that physical volume and see if that fixes it.

If that doesn't work either, try setting the mount for postgres to an actual folder. Something like 

```
    volumes:
      - "/path/to/a/folder/you/own:/var/lib/postgresql/data"
```

**Comment by nofmal** [comment]
> If that doesn't work either, try setting the mount for postgres to an actual folder.

I tried this method, and now it's working properly. Thank you very much!

I ran into this trivial problem early on though:

```shell
danbooru_docker-danbooru-1  | rails aborted!
danbooru_docker-danbooru-1  | ActiveRecord::ConnectionNotEstablished: connection to server at "postgres" (172.18.0.4), port 5432 failed: Connection refused
danbooru_docker-danbooru-1  | 	Is the server running on that host and accepting TCP/IP connections?
```

But all I had to do was run `docker-compose up` one more time, and now it's working just fine.

---

Before I close this issue though, I have one more question. I actually placed my docker images on a custom location instead of `/var/lib/docker`. They are in a Windows partition, and GNOME, when mounting it, gives them the following user/group:

```shell
$ ls -ltrah /path/to/windows/docker/volumes/danbooru-data/
total 4.0K
drwxrwxrwx 1 myusername myusername    0 Jun  9  2020 _data
drwxrwxrwx 1 myusername myusername    0 Jan 21 11:58 .
drwxrwxrwx 1 myusername myusername 4.0K Jan 22 03:05 ..
```

Do you reckon this is why the `chmod` earlier was failing? Why does it only affect the postgres service?

**Comment by nonamethanks** [comment]
If it's a windows partition does that mean it's NTFS? Maybe postgres is doing something that doesn't interact well with that. I woulnd't be able to tell you the reason but I can think of many things that could wrong, like case insensitiveness, symlinks or other issues with permissions.

Another thing that comes to mind, and it's an issue I've found before, is that maybe the user inside the other docker images is using the same uid as your host user (for example the danbooru docker [creates a single user, "danbooru"](https://github.com/danbooru/danbooru/blob/master/config/docker/Dockerfile.danbooru#L73), which would get the default user ID 1000, and so be[ considered the "same user" as your host user](https://medium.com/@mccode/understanding-how-uid-and-gid-work-in-docker-containers-c37a01d01cf), if it was the first user you created), but postgres is using a different one, so it can't write to them. This is all just speculation though.

Anyway, glad you figured it out.
