### ISSUE TITLE
NoMethodError when trying to display some modreports

### ISSUE THREAD

**Issue by kittey** [danbooru/danbooru#4971]
[Modreport 240](https://danbooru.donmai.us/moderation_reports?search[id]=240) and some others can’t be displayed and shows this error instead:
```
Error
undefined method `dtext_shortlink' for nil:NilClass

Details
    NoMethodError exception raised
    app/views/moderation_reports/index.html.erb:19
    app/logical/table_builder.rb:66:in `value'
    app/views/table_builder/_table.html.erb:17
    app/views/table_builder/_table.html.erb:16
    app/views/table_builder/_table.html.erb:15:in `each'
    app/views/table_builder/_table.html.erb:15:in `each_with_index'
    app/views/table_builder/_table.html.erb:15
    app/views/table_builder/_table.html.erb:14
    app/views/table_builder/_table.html.erb:13:in `each_with_index'
    app/views/table_builder/_table.html.erb:13
    app/views/table_builder/_table.html.erb:1
    app/helpers/application_helper.rb:260:in `table_for'
    app/views/moderation_reports/index.html.erb:14
    app/controllers/application_controller.rb:61:in `respond_with'
    app/controllers/moderation_reports_controller.rb:17:in `index'
```

Edit: Seems to happen for reports against comments that were hard-deleted.

**Comment by evazion** [comment]
There were six stray modreports against hard-deleted comments. These reports have been deleted. For posterity, they were:

* https://danbooru.donmai.us/forum_topics/16565?page=13#forum_post_169779
* https://danbooru.donmai.us/forum_topics/16565?page=13#forum_post_169777
* https://danbooru.donmai.us/forum_topics/16565?page=14#forum_post_169900
* https://danbooru.donmai.us/forum_topics/16565?page=14#forum_post_169901
* https://danbooru.donmai.us/forum_topics/16565?page=19#forum_post_170057
* https://danbooru.donmai.us/forum_topics/16565?page=19#forum_post_170058

I'm not sure how the comments came to be hard-deleted.
