### ISSUE TITLE
Way to mark flags as invalid for admins

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4980]
I know flags should be handled by approvers, but now DMK has discovered that he can flag and he's been flagging posts with sockpuppets for bullshit reasons. There needs to be a way to mark flags as invalid, at least for admins, because sockpuppets make the moderation queue useless since we don't have status locks anymore.

https://danbooru.donmai.us/posts/4284498/events this post for example was flagged twice by him. With the same latest account he flagged another two posts. How long till he flags them again?

Just make it so that marking a flag as invalid puts it back to active, and if the post was approved by someone else in the meanwhile revert it.

**Comment by evazion** [comment]
I made it so admins can approve the same post more than once. This way flags can always be overruled by admins.

I don't think it's necessary to have a system for marking flags as invalid because the way you say a flag is wrong is by approving the post.
