### ISSUE TITLE
Can't populate tag string from upload url anymore

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4987]
The latest update removed the ability to automatically add tags to the upload tag box via url.

Something like https://danbooru.donmai.us/uploads/new?url=http%3A//pbs.twimg.com/media/FKcXKrdVkAAXuls.jpg%3Aorig&tag_string=upvote:nonamethanks doesn't work anymore. I know several users were using it to automatically add fav/upvote from the bookmarklet. I also use it all the time to automatically add the correct source when I'm uploading deleted posts from my scraper.

The permitted attributes are still [in the code](https://github.com/danbooru/danbooru/blob/master/app/policies/upload_policy.rb#L20) so I'm assuming this is a bug.

**Comment by evazion** [comment]
Usage is now like `https://danbooru.donmai.us/uploads/new?url=...&post[tag_string]=...&post[rating]=...`
