### ISSUE TITLE
Add Twitter Emojis to Commentary

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4992]
These emojis are much higher resolution and easier to see, plus most of them won't render with any of the system-installed fonts, so they show up only as boxes. As a part of this, the font sizes should be increased as well, especially for the commentary title. Perhaps a font size of 32px for the title, and 20-24px for the body.

### References:

- https://github.com/twitter/twemoji

**Comment by evazion** [comment]
The whole topic of displaying emojis on the web is a lot more complicated than it appears. I settled on overriding the system native emoji font with a bundled version of the Twemoji font, which ensures all emoji can be rendered, but this has downsides as well (larger pageloads, non-native appearance, worse legibility in some cases).

https://nolanlawson.com/2022/04/08/the-struggle-of-using-native-emoji-on-the-web/
