### ISSUE TITLE
Unexpected error: ActiveRecord::RecordNotUnique sometimes appears when uploading posts

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4999]
![image](https://user-images.githubusercontent.com/12946050/152744917-29899549-bc75-4423-bb59-4f13d11704c0.png)
Got this error for [post #5112846](https://danbooru.donmai.us/posts/5112846), though it was uploaded fine . I've gotten it at least a few times today.

**Comment by evazion** [comment]
I think this was probably caused by accidentally submitting the upload form twice. This would lead to trying to create two posts with the same md5, which would fail with this error.
