### ISSUE TITLE
Tumblr redesign wreaks havoc on the 3 people that still use it, also me

### ISSUE THREAD

**Issue by KalpacMuskoxen** [danbooru/danbooru#5054]
Tumblr just rolled out a fresh new look that (despite being very aesthetically pleasing and making it WAY easier to view shadowbanned blogs on desktop) appears to have broken some site functionality when it comes to uploading posts on Danbooru.

It's not consistent as to which post links work and which don't, though. Here's one that doesn't: https://gummuru.tumblr.com/post/184794716304/i-dont-care-what-anyone-says-default-mii-gunner

**Comment by evazion** [comment]
I don't know what the original bug was, but this works now.
