### ISSUE TITLE
Wildcard searches return unexpected results when combined with OR searches

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5056]
Since a wildcard search is functionally just the top 100 tags ORed together, the results you get for something like `~a ~b *c*` don't necessarily contain either `a` or `b`, which is likely not what anyone using them expects. It should probably be something like `(~a ~b) AND (*c*)` instead. It would be nice if AND searches were natively supported, but I'm not sure how reasonable that would be.

**Comment by evazion** [comment]
Fixed in b810c43. This is a breaking change. `black_* white_*` now acts like `black_* and white_*` (find posts with at least one black tag AND one white tag); before it was like `black_* or white_*` (find posts with at least one black tag OR one white tag).
