### ISSUE TITLE
Modqueue: filtering by tag breaks ordering

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#5057]
https://danbooru.donmai.us/modqueue?search%5Btags%5D=age%3A%3E10minutes&search%5Border%5D=modqueue_asc
https://danbooru.donmai.us/modqueue?search%5Btags%5D=age%3A%3E10minutes&search%5Border%5D=modqueue_desc

These two links show the same results to me. I tried with fav:, downvote: etc and they all break the ordering.

**Comment by CoreMack** [comment]
It's not just metatags, it's any tag.  I can't order the modqueue at all unless my search is empty
