### ISSUE TITLE
.webp images upload support

### ISSUE THREAD

**Issue by SystemZ** [danbooru/danbooru#5065]
Currently danbooru supports creating webp images for thumbnails from uploaded images but it doesn't accept uploading this format.

It offers better compression and less size than jpg but those are lost if we need to convert it back to jpg or png before uploading

**Comment by nonamethanks** [comment]
The only site we support that currently hosts webp is newgrounds, and only for the lower quality alternate images past the first one. 

I don't think size should be a concern over getting the original file. webp uploads would nearly always be [lossless-lossy](https://danbooru.donmai.us/wiki_pages/lossless-lossy) conversions, which we don't allow.
