### ISSUE TITLE
Add Fur Affinity support

### ISSUE THREAD

**Issue by KalpacMuskoxen** [danbooru/danbooru#5071]
As much as it pains me to say this, I dare say it's time to address the (anthropomorphic) elephant in the room - there's a fair share of posts from Fur Affinity, and it would make the posting process so much easier if the site could automatically fetch the highest quality image, tags, and artist commentary all at once when uploading, as we do with posts from the other art sites.

**Comment by evazion** [comment]
Fixed by #5147.
