### ISSUE TITLE
Images rated "Adult" on Newgrounds no longer upload.

### ISSUE THREAD

**Issue by KalpacMuskoxen** [danbooru/danbooru#5077]
Trying to upload a post from Newgrounds rated "Adult" brings up this error, but works fine for other content ratings.

![2022-03-29_23-34-51](https://user-images.githubusercontent.com/78698406/160772809-e24745e9-acf5-4310-8537-09bc191836a7.png)

**Comment by nonamethanks** [comment]
Welp, apparently they require login now.

**Comment by evazion** [comment]
The session cookie is called `vmkIdu5l8m` and the value changes with every request, but apparently you can store an old value and it stays valid.

**Comment by evazion** [comment]
Something just changed. The cookie is now called `vmk1du5l8m` (note the `I -> 1`) and you need a `NGBrowserValidation` cookie, otherwise you get a hCaptcha page. This happens even on the homepage.

**Comment by evazion** [comment]
The captcha page was only temporary, now it works again.
