### ISSUE TITLE
Admin ability to upload posts longer than 140 seconds is broken

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#5081]
It just returns "Upload failed: Duration must be less than 140 seconds."
You can try with https://files.catbox.moe/3mdnv8.mp4 (not that I wanted to upload it, just one example from the request thread)

**Comment by SystemZ** [comment]
What version are you using?
It works for me flawlessly after setting `DANBOORU_MAX_VIDEO_DURATION` env to something higher than 140 seconds.

**Comment by nonamethanks** [comment]
Well that's the problem, admins are supposed to be able to bypass that limit.

**Comment by SystemZ** [comment]
Oh ok, now I understand.
Yes I can confirm, even as admin you need to set this higher in settings.
