### ISSUE TITLE
Use user's preferred color scheme by default

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5084]
Check the `prefers-color-scheme` media selector to default to light/dark mode. There'll have to be an "auto" theme option for logged-in users, currently only light/dark exist.

**Comment by luni3359** [comment]
This ought to apply for those not logged in as well. Most people are lurkers and their preferred theme should be respected too.

**Comment by NamelessContributor** [comment]
It does apply to logged-out users, the default "auto" setting follows the browser setting. On Chrome this follows the system-wide setting, on Firefox it can be independently set.

**Comment by luni3359** [comment]
Oops... I tested this yesterday in a private window and I swear I still got the light theme even with a dark theme. Thanks for clearing it up.
