### ISSUE TITLE
Always show original source for a post

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5086]
There should be a way to see the original source for a post. Since you can edit it in the upload form or after submission before the first version stops merging, people can just upload from file/url then remove/alter the source and there is no way to see where it came from. I've seen this happen a few times already.

**Comment by nonamethanks** [comment]
Uploading paywalled content is already forbidden, so that's not really an issue.

**Comment by bipface** [comment]
i sometimes upload directly from my own fileserver for convenience, and override the source in order to avoid exposing my IP address,
so if the original source becomes a field, i think it should be restricted to approvers or higher (at a minimum)

**Comment by evazion** [comment]
>I sometimes upload directly from my own fileserver for convenience, and override the source in order to avoid exposing my IP address

This is the reason why it's not shown. Sources can contain private information and I don't know how to avoid that except by making a huge whitelist of known good sites that are allowed to show the source.
