### ISSUE TITLE
Add Naver support

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#5087]
https://grafolio.naver.com/works/1866683

https://post.naver.com/viewer/postView.nhn?volumeNo=25376261

https://blog.naver.com/karmiel/221312112090

**Comment by evazion** [comment]
Naver consists of a bunch of different sites:

* https://blog.naver.com (Naver Blog, a blogging site)
* https://post.naver.com (Naver Post, a blogging site nearly identical to Naver Blog, yet still considered a separate site)
* https://cafe.naver.com (Naver Cafe, a forum/community type site)
* https://grafolio.naver.com (Naver Grafolio, a portfolio type site. Now at https://grafolio.ogq.me)
* https://comic.naver.com (Korean version of Naver Webtoons)
* https://webtoons.com (English version of  Naver Weboons)
* https://chzzk.naver.com (a Twitch clone)

I've added support for Naver Blog and Naver Post. Naver Cafe is used by some artists so it could be worthwhile to add. Grafolio isn't used by many artists but might have some unique work.

Webtoons is a commercial platform that aggressively goes after other sites [1], so it would be too risky to add. It's not a site people upload from anyway.

[1]: https://torrentfreak.com/naver-webtoon-targets-hundreds-of-piracy-sites-ahead-of-public-listing-231024/
