### ISSUE TITLE
"undefined method: newgrounds_session_cookie" when trying to upload from Newgrounds

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#5089]
What's really strange to me is that I don't see newgrounds_session_cookie anywhere in the source for the newgrounds strategy. Did you accidentally deploy uncommitted changes or am I going insane?

<https://www.newgrounds.com/art/view/kionant/lopunny-2> (nsfw)
![image](https://user-images.githubusercontent.com/12946050/161308490-2178983d-f741-4e31-a980-dbed0814afa8.png)

See also issue #5077.

**Comment by evazion** [comment]
Oops, I accidentally committed it in 0f58c737975ec9eeb8db4eb5c89fd62120e7446a.

**Comment by evazion** [comment]
Rolled back that commit.
