### ISSUE TITLE
BURs with incorrect updated_at attribute

### ISSUE THREAD

**Issue by CoreMack** [danbooru/danbooru#5093]
This search: https://danbooru.donmai.us/bulk_update_requests?commit=Search&search%5Border%5D=updated_at_desc has several out-of-order results.  This is because there's a bunch of BURs that, despited having been approved months or even years ago, have updated_at timestamps set to 2022-03-31.
For example, the oldest incorrect BUR (that I found), https://danbooru.donmai.us/bulk_update_requests/33 has "updated_at":"2022-03-31T20:42:27.532-04:00" despite not being touched in years.

**Comment by evazion** [comment]
The `tags` field for these BURs was fixed as part of 226faae8ec20fb2e683e2873358668a381411307. The `updated_at` timestamp is correct in that a field in these BURs was updated.
