### ISSUE TITLE
Add twitter image description feature to commentary

### ISSUE THREAD

**Issue by fredgido** [danbooru/danbooru#5107]
example: https://twitter.com/8_siranami/status/1500774463293431815
Should it be added?

**Comment by luni3359** [comment]
I think it should

**Comment by luni3359** [comment]
Sorry about that, I'm retarded.

**Comment by BrokenEagle** [comment]
This data doesn't show up with the V1.1 of the API. However, it does show up in the GraphQL version. I'm not sure if it shows on the V2 of the API.

On that note, it shows up under the media as attached to the image entity itself as the key `ext_alt_text` , meaning that each image could potentially have it's own description. I'm not sure what the best way to handle this would be. Does the image description only go with that particular post for that image, or would it go to all posts as an umbrella commentary. The former would make it more relevant to that particular post, but would also make copying the translated commentary from one post to the others a more difficult task. The latter though would include a bunch of details which may not be relevant and could potentially be distracting to the image.

**Comment by BrokenEagle** [comment]
- 4 images, alt text on 4 images: https://twitter.com/maruyo_/status/1521844593804906496

Regarding my comment above, it indeed is the case that each image can have its own alternate text.
