### ISSUE TITLE
Fix script 097_normalize_post_sources.rb doesn't fix some stuff

### ISSUE THREAD

**Issue by GlassedSilver** [danbooru/danbooru#5109]
I'm not sure if this even is one intended scope of the normalize script, if it is not consider this a suggestion for another fix script, but I recently deployed a tool in my software stack called Grabber and it can pass images to my local danbooru instance, even passing the source URL of the file. In this case it's a pixiv asset.

The source as displayed by my danbooru instance now:
![Screenshot 2022-04-11 004822](https://user-images.githubusercontent.com/1912133/162643211-fa56da4a-4e82-4ac1-9368-890f5c652019.png)

When I would like it to get converted to the usual style (sampling from the donmai.us instance)
![Screenshot 2022-04-11 004928](https://user-images.githubusercontent.com/1912133/162643250-01e41c7b-8e47-4be4-9142-f7a99b4ed502.png)

**Comment by nonamethanks** [comment]
Is that a space in the source link? Right before the "p0"? 

Standard pixiv direct image urls should already be normalized by default.

**Comment by GlassedSilver** [comment]
Dear Lord, thank you so much for this! I think I spotted a problem with the way that the URL got handled by Grabber. Maybe a setting in there. Anyhow, thank you so much for the extremely speedy reply and the very good eye!
