### ISSUE TITLE
083_generate_media_asset_variants.rb throws DeadWorker error after some hundreds of successful IDs

### ISSUE THREAD

**Issue by GlassedSilver** [danbooru/danbooru#5111]
When I run the fix script from within danbooru's danbooru_danbooru container shell using this command:

`root@50824e0aa654:/danbooru/script/fixes# ./083_generate_media_asset_variants.rb`

I get this error eventually, always around the same ID.

```
[lots of IDs listed here, up to these the script works beautifully]
id=924
id=926
id=925
/root/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:86:in `rescue in work': Parallel::DeadWorker (Parallel::DeadWorker)
        from /root/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:83:in `work'
        from /root/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:482:in `block (4 levels) in work_in_processes'
        from /root/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:597:in `with_instrumentation'
        from /root/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:481:in `block (3 levels) in work_in_processes'
        from /root/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:469:in `loop'
        from /root/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:469:in `block (2 levels) in work_in_processes'
        from /root/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:222:in `block (4 levels) in in_threads'
/root/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:84:in `load': end of file reached (EOFError)
        from /root/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:84:in `work'
        from /root/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:482:in `block (4 levels) in work_in_processes'
        from /root/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:597:in `with_instrumentation'
        from /root/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:481:in `block (3 levels) in work_in_processes'
        from /root/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:469:in `loop'
        from /root/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:469:in `block (2 levels) in work_in_processes'
        from /root/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.22.1/lib/parallel.rb:222:in `block (4 levels) in in_threads'
```

What can I do to fix this? Maybe set overcommit memory on redis?

**Comment by nonamethanks** [comment]
Try modyfing the script so that it looks like

```ruby
rescue StandardError => e
  STDERR.puts "id=#{media_asset.id} status=FAILED e='#{e}'"
rescue => e
  STDERR.puts "exc #{Process.pid}"
  STDERR.puts "worker failed: #{e.class}"
  STDERR.puts e.backtrace
ensure
  media_file&.close
end

```
So that we can figure out what's going on.

**Comment by GlassedSilver** [comment]
> If "EOFError" refers to the file, that might be because the file is corrupted perhaps? Are these old assets from before we had stricter checks for corrupted uploads?

Not sure when that change was made, but could be. The range of uploads where it stopped working is from around April 2020. I'll put what you suggested in the script and see which image exactly triggered that error, then I'll inspect it and see if it's hashing out okay.

**Comment by GlassedSilver** [comment]
It's much slower without parallel, but it's chugging along. 👍 

I'll let it run whilst having breakfast. Thank you so much everyone for the help, it's super appreciated!

**Comment by nottalulah** [comment]
They're intended as one-off fix scripts. If you find yourself needing to run a task on a schedule for any reason it would be better to turn it into a [background job](https://github.com/danbooru/danbooru/blob/master/app/jobs/README.md) and schedule it in [danbooru_maintenance.rb](https://github.com/danbooru/danbooru/blob/master/app/logical/danbooru_maintenance.rb).

**Comment by GlassedSilver** [comment]
> They're intended as one-off fix scripts. If you find yourself needing to run a task on a schedule for any reason it would be better to turn it into a [background job](https://github.com/danbooru/danbooru/blob/master/app/jobs/README.md) and schedule it in [danbooru_maintenance.rb](https://github.com/danbooru/danbooru/blob/master/app/logical/danbooru_maintenance.rb).

Thank you! I thought as much since those background jobs are already a thing, just wondered if there's something I might be missing. Just want my instance to be well taken care of. :)

**Comment by nottalulah** [comment]
By the way, we have a #technical channel in our [Discord](https://discord.gg/danbooru). It might be easier to get real-time feedback there, if you need any pointers.

**Comment by GlassedSilver** [comment]
> By the way, we have a #technical channel in our [Discord](https://discord.gg/danbooru). It might be easier to get real-time feedback there, if you need any pointers.

Good to know, although to be honest it's nice having threads like these, because since they are publicly accessible without an app anyone in the same position can quickly find an answer. I don't know how many folks out there use a personal danbooru instance, but in the very least it also makes it easier to self-document my shenanigans and reference stuff at a later time.

But the pointer is appreciated, I can't say I'd never use it, I guess atm I'm busy enough with many other things to not everything is as urgent now.

Bless your kind soul for the tip though. I'll join the server for sure, if just for chit chat. :)
