### ISSUE TITLE
Twitter v1.1 API with OAuth2 bearer tokens 404s sensitive tweets in certain countries

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5117]
Danbooru instances hosted in Canada and Germany (maybe others) can't have any files uploaded from any Twitter link marked "sensitive", which sometimes includes an entire artist, or just individual tweets. Direct image links also seem to not work. Might be fixed by #4656, but it seems OAuth1.0a signed requests to the 1.1 API still work properly. 

Not presently an issue on donmai but I hope it can be fixed anyway.

example:

[This artist's entire profile is marked "sensitive" so nothing of theirs will upload.](https://twitter.com/Seraziel/status/1496295429910274056)

**Comment by evazion** [comment]
I can't reproduce this. I tried both the v1 and v2 APIs, and both Canadian and German IPs using a VPN. The tweet is marked as sensitive, but it's still returned by the API and the image can still be downloaded.

Note that it's possible for tweets to be withheld in certain countries for legal reasons, in which case there's probably nothing we can do.

https://help.twitter.com/en/rules-and-policies/tweet-withheld-by-country

**Comment by nottalulah** [comment]
They're definitely not withheld, I could still see the API responses in the v2 API at the time. I have errored uploads in my database from as little as 21 hours ago after this issue persisted for a few months, but it appears that for whatever reason within the last day something was changed to fix it. The same requests that used to 404 now seem to work fine. I have no idea why.

**Comment by nottalulah** [comment]
I haven't noticed issues with this again so I'll just close this issue.
