### ISSUE TITLE
Regular tags are now case-sensitive 

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5136]
Regression from before when case didn't matter in searches. Now "[ARKNIGHTS](https://danbooru.donmai.us/posts?tags=ARKNIGHTS)" turns up no results while "[arknights](https://danbooru.donmai.us/posts?tags=arknights)" works as expected.

**Comment by NamelessContributor** [comment]
This only affects single-tag searches, [ARKNIGHTS SOLO](https://danbooru.donmai.us/posts?tags=ARKNIGHTS+SOLO) works. See ca5dd61728b44ac58aac10c82327cfbea0a0d2b6.
