### ISSUE TITLE
add support for weibo share urls

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5165]
https://share.api.weibo.cn/share/304950356,4767694689143828.html

The `.html` is unnecessary, the `4767694689143828` is equivalent to the long illust id in mobile URLs (https://m.weibo.cn/detail/4767694689143828), but the page also loads without it (https://share.api.weibo.cn/share/304950356).

**Comment by kidonng** [comment]
The `mid` is present in the HTML:

```html
<a class="m-btn-ellipse m-btn-block m-btn-orange" href="[javascript:void(0)](about:blank)" onclick="forward(0,4767694689143828,'')"
```

Something like `forward\(0,(\d{16})` should be able to capture that.
