### ISSUE TITLE
Don't allow wide_image and tall_image to be manually tagged

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5171]

**Comment by evazion** [comment]
I'm inclined to just nuke these tags. `wide_image` is equivalent to `ratio:>=4:1` and `tall_image` is equivalent to `ratio:<=1:4`. They have an additional requirement that the image be at least 1024px wide or tall, but in practice this only filters out a hundred or so posts.

**Comment by nottalulah** [comment]
I would've suggested a nuke but since the resolution autotags had a nuke rejected a while ago I wasn't sure if it would be desirable.
