### ISSUE TITLE
Add `api:` to the list of meta wikis

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#5206]
I.e. the following piece of code:

https://github.com/danbooru/danbooru/blob/15a0fd604bc58c1da1f3d028160bf4bac28734bf/app/models/wiki_page.rb#L6

Just change it to:

```ruby
  META_WIKIS = ["list_of_", "tag_group:", "pool_group:", "howto:", "about:", "help:", "template:", "api:"]
```

**Comment by nonamethanks** [comment]
Fixed in ab900beffd0fc108395b5923575c0938ecb64752.
