### ISSUE TITLE
Twitter video .02 seconds over the duration limit 

### ISSUE THREAD

**Issue by Fuuf7** [danbooru/danbooru#5217]
https://twitter.com/mutturineko/status/1130149811720560641

140.02 seconds long, so its blocked from uploading. 
I would appreciate a longer duration limit in general, since there's a decent amount of touhou animations going beyond 2:20, though I get the aversity to those 14 minute overwatch SFM porn videos.

**Comment by luni3359** [comment]
I would consider this a bug since there's no way for the end user to tell the difference.
