### ISSUE TITLE
Ai_tags uploading via post request

### ISSUE THREAD

**Issue by Kille250** [danbooru/danbooru#5218]
With the new commit ai_tags should be automatically be added after a new media asset is generated. It is working, but if you upload images or videos via post requests nothing will be added to the ai_tags page.

**Comment by Kille250** [comment]
Also uploading via URL‘s won‘t generate any.

**Comment by evazion** [comment]
Can you give more details? This should be working.

**Comment by Kille250** [comment]
> Can you give more details? This should be working.

yea it's working after you pushed the production image. Can close it!
