### ISSUE TITLE
How to run BigQuery queries?

### ISSUE THREAD

**Issue by vedantroy** [danbooru/danbooru#5222]
I'm trying to run a BigQuery query, but I get:
> Access Denied: Project danbooru1: User does not have bigquery.jobs.create permission in project danbooru1.

The query in question is:
```
SELECT tags.name, COUNT(id) AS num, SUM(file_size)/1000000000 AS GB FROM [danbooru.posts] GROUP BY tags.name ORDER BY GB DESC LIMIT 20;
```

Is there something I need to be doing to be able to run queries?

**Comment by nonamethanks** [comment]
You need to create your own project. After that you'll be able to run queries.

**Comment by vedantroy** [comment]
Thanks for the response. I have my own project. The issue is, I'm not sure how to query the danbooru project.
BigQuery supports "public datasets", but I don't think the project "danbooru1" is a public dataset.
Is there something obvious here that I'm missing?

**Comment by nonamethanks** [comment]
You have to query the tables like `SELECT * FROM danbooru1.danbooru_public.posts LIMIT 1`

**Comment by vedantroy** [comment]
Solved! Thanks.
