### ISSUE TITLE
`PG::AmbiguousColumn: ERROR:  column reference "bit_prefs" is ambiguous` searching users by posts

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5225]
https://danbooru.donmai.us/users?search[posts][post_tag_matches]=self_upload&search[is_banned]=true

**Comment by evazion** [comment]
Your search should be <https://danbooru.donmai.us/users?search[is_banned]=true&search[posts_tags_match]=self_upload>.
