### ISSUE TITLE
Unexpected error: NoMethodError on the jobs page

### ISSUE THREAD

**Issue by aTan-aka-Xellos** [danbooru/danbooru#5229]
Open "https://danbooru.donmai.us/jobs".
Displayed error:
`NoMethodError exception raised
app/views/jobs/index.html.erb:14
app/logical/table_builder.rb:66:in `value'
app/views/table_builder/_table.html.erb:17
app/views/table_builder/_table.html.erb:16
app/views/table_builder/_table.html.erb:15:in `each'
app/views/table_builder/_table.html.erb:15:in `each_with_index'
app/views/table_builder/_table.html.erb:15
app/views/table_builder/_table.html.erb:14
app/views/table_builder/_table.html.erb:13:in `each_with_index'
app/views/table_builder/_table.html.erb:13
app/views/table_builder/_table.html.erb:1
app/helpers/application_helper.rb:278:in `table_for'
app/views/jobs/index.html.erb:12
app/controllers/application_controller.rb:64:in `respond_with'
app/controllers/jobs_controller.rb:8:in `index'`

![Screen Shot 2022-07-19 at 22 13 42](https://user-images.githubusercontent.com/7886823/179759779-5034c52f-d03d-4344-ab5b-48e8dcb71f4d.jpg)

**Comment by thelaao** [comment]
This is already fixed on ba36e48bff92b1c784dd752d3fe6d3d8b336631b, but is not yet deployed on danbooru.
You can view the jobs on betabooru: https://betabooru.donmai.us/jobs

**Comment by aTan-aka-Xellos** [comment]
@thelaao 
1. Open https://betabooru.donmai.us/jobs
2. Select Queued or Finished
3. Click Search

**Actual result:** 
Unexpected error: NameError.

![Screen Shot 2022-07-20 at 11 37 34](https://user-images.githubusercontent.com/7886823/179884212-a0865ba1-077e-43e3-9cda-0c69277cf99a.jpg)
