### ISSUE TITLE
Purging - Some random hiccups - installing / configuring - cookies/sessions

### ISSUE THREAD

**Issue by dvflextech** [danbooru/danbooru#5232]
So, I tried the manual setup, got it running, but kept getting some sort of application.js error.
I gave up on manual install.

Installed docker-compose, ran the docker-compose setup and got it working.
Changed some configs, uploaded a few images (Everything works.. kinda)
Set everything to a ddns hostname rather than localhost/local ip.
Noticed it was using localhost to server images.. after looking around a bit, I found it was the storage config, so I set a custom image_url to handle images. Thumbnails still kinda failed (on port 80, not 3000). Then realized host machine is running nginx still.
Ended it. Using port 3000 works exclusively and properly for images.
Go to login, because I had finalized my setup. Can no longer login. It stores something when I login, but the page itself still shows Login. Logging in from IP rather than ddns works as suspected.

How can I purge everything changed/installed from manual install?
like, sudo apt remove yarn rails ruby nginx postgresql
then remove user danbooru + rm -rf /home/danbooru/*
What are the commands to purge docker, too and just completely start over?

Just feels very cumbersome. Just wanna start over and do a straight proxy from 80 on host to 3000 once it's all proper.
Should I just clean up the host? Can I fix the cookies/sessions problem?

**Comment by nonamethanks** [comment]
Unfortunately, yes, you'll have to manually check what the script installed and remove each yourself. That's why docker is so superior. 

As for docker, you only need to remove the volumes it created to reset the installation completely. So 
```
docker volume rm danbooru-images
docker volume rm danbooru-data
docker volume rm iqdb-data
```

For the cookie/session issue, have you tried setting both DANBOORU_CANONICAL_URL and DANBOORU_HOSTNAME? Their values need to be respectively like "https://my.site.com" and "my.site.com" (or whatever you're using as host). Make sure to set the right protocol you're using for DANBOORU_CANONICAL_URL  (http vs https).

You can set these in the docker compose file itself or in the danbooru_custom_config.rb file if you are using that.

**Comment by dvflextech** [comment]
SOLVED

> Unfortunately, yes, you'll have to manually check what the script installed and remove each yourself. That's why docker is so superior. [...]
> For the cookie/session issue, have you tried setting both DANBOORU_CANONICAL_URL and DANBOORU_HOSTNAME? Their values need to be respectively like "https://my.site.com" and "my.site.com" (or whatever you're using as host). Make sure to set the right protocol you're using for DANBOORU_CANONICAL_URL (http vs https).

> You can set these in the docker compose file itself or in the danbooru_local_config.rb file if you are using that.

Thanks for the fast reply!
I get into the container using ` sudo docker exec -it adc7a8f7e3fa /bin/bash`
(Which is the rails image listening on 0.0.0.0 3000)
In /danbooru/config I do `nano dan*.rb` and I see (actual host truncated for security)
```
    def hostname
      "my.host.name" 
    end
```
and

```
    def canonical_url
      "http://my.host.name"
    end
```
I set a custom session/cookie of
`    def session_cookie_name
      "_xbooru_session"
    end
`
At http://my.host.name:3000 login results in no cookie being set
At http://192.168.2.165 login results in cookie (_xbooru_session) + My account & Upload being available.

Editing docker-compose.yaml with my.host.name actually resolved the issue.
So, if anyone else has a similar issue, editing docker-compose.yaml actually solves some config issues/discrepancies. 

- Edit docker-compose.yaml  DANBOORU_CANONICAL_URL= to your expected URL
- sudo docker-compose restart
Profit.
