### ISSUE TITLE
Having issues authenticating into danbooru under subdomain

### ISSUE THREAD

**Issue by ReSummit** [danbooru/danbooru#5235]
I've been trying to log / register a new account into danbooru under a subdomain but it refuses to recognize that the browser is logged in or registers a new account. I'm currently using NGINX as the reverse-proxy with SSL and then danbooru running through docker-compose behind it.

Some of the things I found that might contribute to this is:

1. When registering, no CSRF token is sent to the server, resulting in an "Can't verify CSRF token authenticity" error. I'm not sure why this happens because it works through the local network. I tried manipulating the headers in NGINX to some configurations like passing headers and not allowing proxy buffering but no dice; logs also just reciprocate the same error in the development environment.
2. In the response headers, the `Set-Cookie` header's `domain` key only gives the top level domain (e.g. instead of "my.domain.com" it is ".domain.com"). My Chromium browsers as a result reject this `Set-Cookie` header, which looks to be the reason why this issue is occurring.

Here is an example of the missing CSRF token during registration:
![image](https://user-images.githubusercontent.com/23018622/184526096-4fb7c88a-5f43-43fe-bf54-8963b5e1d237.png)

Here is an example `Set-Cookie` header:
![image](https://user-images.githubusercontent.com/23018622/184525980-dd2d7c14-4ec7-42dd-be2a-0d7436d82515.png)

Any clues on which files might involve these issues?
(Edit: Missed the image of the CSRF token, whoops)

**Comment by evazion** [comment]
> In the response headers, the Set-Cookie header's domain key only gives the top level domain (e.g. instead of "my.domain.com" it is ".domain.com"). My Chromium browsers as a result reject this Set-Cookie header, which looks to be the reason why this issue is occurring.

Try changing or deleting the `tld_length` line in `config/initializers/session_store.rb`. Currently it's hardcoded to 2; you may need to change it depending on your subdomain structure.

**Comment by nonamethanks** [comment]
I'm having the same issue when launching the default docker compose with no alteration. Trying to register a user returns "Error: Can't verify CSRF token authenticity"

**Comment by nonamethanks** [comment]
After a lot of tests I can confirm that `domain: all` is the culprit.

**Comment by KenwoodFox** [comment]
Is this config option not present in the current config file? Im having this same issue but i *dont* use multiple subdomains, only one.
