### ISSUE TITLE
Can't make it work (yarn install errors, no password supplied error, couldn't create danbooru2 database, etc)

### ISSUE THREAD

**Issue by Laizrod** [danbooru/danbooru#5253]
Hello. I have an issue with the installation of danbooru.
I tried and re-tried multiple times on new fresh installes Debian and Ubuntu Server VMs but I cannot manage danbooru to work and it's kinda frustrating.

I follow without any problem the [Ubuntu Installation Guide](https://github.com/danbooru/danbooru/wiki/Ubuntu-Installation-Help-Guide) up to the ``yarn install --check-files`` step where I get my first error. Indeed, when I execute this command I get this error:

```
Unknown Syntax Error: Unsupported option name ("--check-files").
$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--skip-builds]
```
I tried and made many researches but couldn't find any way to fix this. This is my first issue.
The only option left to me was to simply execute ``yarn install`` which gives me this:
```
➤ YN0000: ┌ Resolution step
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide @babel/core (p8784d), requested by @babel/cli
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide @babel/core (p9fbd3), requested by @babel/eslint-parser
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide @babel/core (p2e634), requested by @babel/plugin-proposal-decorators
➤ YN0002: │ stylelint-config-recommended-scss@npm:5.0.2 [b1981] doesn't provide postcss (p4b89c), requested by postcss-scss
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 325ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yaml@npm:1.10.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs-parser@npm:20.2.9 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:17.2.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yauzl@npm:2.10.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 37s 605ms
➤ YN0000: ┌ Link step
➤ YN0062: │ fsevents@patch:fsevents@npm%3A2.3.2#builtin<compat/fsevents>::version=2.3.2&hash=11e9ea The platform linux is incompatible with this module, link skipped.
➤ YN0007: │ @fortawesome/fontawesome-free@npm:5.15.4 must be built because it never did before or the last one failed
➤ YN0007: │ core-js@npm:3.25.0 must be built because it never did before or the last one failed
➤ YN0007: │ typopro-web@npm:4.2.6 must be built because it never did before or the last one failed
➤ YN0009: │ typopro-web@npm:4.2.6 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-610d28c9/build.log)
➤ YN0009: │ typopro-web@npm:4.2.6 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-610d28c9/build.log)
➤ YN0000: └ Completed in 10s 567ms
➤ YN0000: Failed with errors in 48s 723ms
```
(here's a screenshot if you prefer like this for the eyes lol)
![Termius_PpeLlchDGn](https://user-images.githubusercontent.com/36924895/190876050-9b8d43a1-174a-4f9d-95cf-c36428636172.png)

I couldn't fix it either, so I tried to continue anyway, then I get this.
``bundle exec rake db:create db:migrate``
```
[ElasticAPM] Agent disabled with `enabled: false'
fe_sendauth: no password supplied
Couldn't create 'danbooru2' database. Please check your configuration.
rake aborted!
ActiveRecord::ConnectionNotEstablished: fe_sendauth: no password supplied
/home/danbooru/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
/home/danbooru/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'

Caused by:
PG::ConnectionBad: fe_sendauth: no password supplied
/home/danbooru/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
/home/danbooru/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
```
Again, couldn't manage to fix it and this logically leads to the following (same) errors:
`` bundle exec rails server --binding 0.0.0.0``
```
=> Booting Puma
=> Rails 7.0.3 application starting in development 
=> Run `bin/rails server --help` for more startup options
[ElasticAPM] Agent disabled with `enabled: false'
[GoodJob] [7526] GoodJob started scheduler with queues=* max_threads=5.
[GoodJob] Notifier errored: ActiveRecord::ConnectionNotEstablished: fe_sendauth: no password supplied
```
![chrome_pGGUrUWfN4](https://user-images.githubusercontent.com/36924895/190876091-c6c5770c-089e-471d-bcf4-b120a90fbb2c.png)

I don't know what I did wrong or what went wrong but I someone could help me understanding and solving my issues, it would be great!

Thank you

**Comment by Laizrod** [comment]
Edit : I managed to fix yarn errors by downgrading yarn to yarn1 version (``yarn set version 1.22.19``) and updating node from 10 to latest version.
Now I'm still stuck with the other ones

**Comment by evazion** [comment]
Sounds like Danbooru can't connect to the database because the database password wasn't configured.

You can either put this in your `/etc/postgresql/14/main/pg_hba.conf` file to disable password authentication (this is insecure):

```
local all all trust
```

Or you can do `export DATABASE_URL=postgresql://danbooru:password_goes_here@localhost/danbooru2` to set your database password before running Danbooru.

You can try `psql danbooru2` or `psql postgresql://danbooru:password_goes_here@localhost/danbooru2` to test your configuration.

See https://www.prisma.io/dataguide/postgresql/authentication-and-authorization/configuring-user-authentication for details on Postgres auth.

**Comment by Laizrod** [comment]
> Sounds like Danbooru can't connect to the database because the database password wasn't configured.
> 
> You can either put this in your `/etc/postgresql/14/main/pg_hba.conf` file to disable password authentication (this is insecure):
> 
> ```
> local all all trust
> ```
> 
> Or you can do `export DATABASE_URL=postgresql://danbooru:password_goes_here@192.168.1.56/danbooru2` to set your database password before running Danbooru.
> 
> You can try `psql danbooru2` or `psql postgresql://danbooru:password_goes_here@192.168.1.56/danbooru2` to test your configuration. This is assuming your database username is `danbooru`, your database IP is `192.168.1.56`, and your database name is `danbooru2`; you can change it if you setup is different.
> 
> See https://www.prisma.io/dataguide/postgresql/authentication-and-authorization/configuring-user-authentication for details on Postgres auth.

Ooh amazing, thank you man I appreciate, it worked!

Don't wanna disturb you but I have another issue though:
```
Webpacker::Manifest::MissingEntryError - Webpacker can't find application.js in /home/danbooru/danbooru/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}:
  app/views/layouts/default.html.erb:27
  app/views/layouts/sidebar.html.erb:23
  app/controllers/application_controller.rb:64:in `respond_with'
  app/controllers/posts_controller.rb:25:in `index'
```

I tried to turn compile value to true but it doesn't seem to fix the thing.

**Comment by evazion** [comment]
My first guess it's because you have Yarn 1, but Danbooru requires Yarn 2.

Try this:

```
apt-get update
apt-get install git curl build-essential

git clone https://github.com/asdf-vm/asdf.git ~/.asdf
echo "source ~/.asdf/asdf.sh" >> ~/.bashrc
exec bash # restart shell

asdf plugin add nodejs
asdf install nodejs 14.15.5
asdf global nodejs 14.15.5
npm install -g yarn
yarn set version 2.4.0

node --version # should say 14.15.5
yarn --version # should say 2.4.0
```

`asdf` is a tool for installing Ruby or Javascript versions. You may need to use it if your distro doesn't have the right version of Node.js. See https://asdf-vm.com/guide/getting-started.html.

**Comment by Laizrod** [comment]
> My first guess is that it's because you have Yarn 1, but Danbooru requires Yarn 2.
> 
> Try this:
> 
> ```
> apt-get update
> apt-get install git curl build-essential
> 
> git clone https://github.com/asdf-vm/asdf.git ~/.asdf
> echo "source ~/.asdf/asdf.sh" >> ~/.bashrc
> exec bash # restart shell
> 
> asdf plugin add nodejs
> asdf install nodejs 14.15.5
> asdf global nodejs 14.15.5
> npm install -g yarn
> yarn set version 2.4.0
> 
> node --version # should say 14.15.5
> yarn --version # should say 2.4.0
> ```
> 
> `asdf` is a tool for installing Ruby or Javascript versions. You may need to use it if your distro doesn't have the right version of Node.js. See https://asdf-vm.com/guide/getting-started.html.

Hmm thanks man but it doesn't seem to fix my issue. I also tried with different node versions (14.15.5, 14.17.0 and 16) but still doesn't seem to work. Same error message
![chrome_apC07FmaOn](https://user-images.githubusercontent.com/36924895/190900609-1502bf89-82bb-427c-b63e-e897bdd2e7b2.png)

**Comment by Laizrod** [comment]
Edit: OKAY IT ACTUALLY WORKED. I just had to run "yarn" command and then start the server. That fixed my error, now everything seems to be working.
Thank you so much for your help, you saved me.
