### ISSUE TITLE
Mod Queue: flagged/poor_quality not hiding posts I've disapproved

### ISSUE THREAD

**Issue by RaisingK** [danbooru/danbooru#5270]
`status:appealed` and `disapproved:poor_quality` seem to no longer exclude posts I've disapproved of.
`status:flagged` and `status:pending` still seem fine though?

**Comment by nonamethanks** [comment]
Did you try betabooru? It could have been fixed by 559bf1ae0aa518573b50ac97bb7dc8af1f744491.

**Comment by RaisingK** [comment]
Seems that way.
