### ISSUE TITLE
Add bookmarklet support for bbs.mihoyo.com

### ISSUE THREAD

**Issue by etoubleh** [danbooru/danbooru#5284]
Example URL: https://bbs.mihoyo.com/bh3/article/28939887

Example image URL: https://upload-bbs.mihoyo.com/upload/2022/09/14/73731802/2e25565bd6fa86d86b581e151e9778ac_8107601733815763725.jpg
Example image sample URL: https://upload-bbs.mihoyo.com/upload/2022/09/14/73731802/2e25565bd6fa86d86b581e151e9778ac_8107601733815763725.jpg?x-oss-process=image/resize,s_600/quality,q_80/auto-orient,0/interlace,1/format,jpg

The site also has a mobile version. Example URLs: https://m.bbs.mihoyo.com/bh3?channel=miyousheluodi%2F#/article/27266673
https://m.bbs.mihoyo.com/bh3/#/article/27755242

It looks like post and profile URLs vary depending on what Mihoyo game they're posted for. For example, the `bh3` part of the example URLs would be `ys` if it was a Genshin Impact post.

EDIT: The URL has changed from `bbs.mihoyo.com` to `www.miyoushe.com`.

Example URL: https://www.miyoushe.com/bh3/article/28939887

Example image URL: https://upload-bbs.miyoushe.com/upload/2022/09/14/73731802/2e25565bd6fa86d86b581e151e9778ac_8107601733815763725.jpg
Example image sample URL: https://upload-bbs.miyoushe.com/upload/2022/09/14/73731802/2e25565bd6fa86d86b581e151e9778ac_8107601733815763725.jpg?x-oss-process=image/resize,s_600/quality,q_80/auto-orient,0/interlace,1/format,jpg

**Comment by HeeroWingZero** [comment]
Adding onto this for hoyolab, Mihoyo's separate international site

Example URL: https://www.hoyolab.com/article/14554718/

Example Direct: https://upload-os-bbs.hoyolab.com/upload/2022/12/25/58551199/3356bf88b08fdc8aaa5b5e6b26f70d23_5122589414918681540.jpg

Example Sample: https://upload-os-bbs.hoyolab.com/upload/2022/12/25/58551199/3356bf88b08fdc8aaa5b5e6b26f70d23_5122589414918681540.jpg?x-oss-process=image%2Fresize%2Cs_1000%2Fquality%2Cq_80%2Fauto-orient%2C0%2Finterlace%2C1%2Fformat%2Cwebp

Unlike the Chinese site, the URLs for hoyolab do not change per copyright. See the following examples:
https://www.hoyolab.com/article/14097750 (Honkai Impact 3rd)
https://www.hoyolab.com/article/14657132 (Tears of Themis)
https://www.hoyolab.com/article/14401738 (Zenless Zone Zero)

**Comment by HeeroWingZero** [comment]
I don't know if there's any plan to add these as sources, but I figured I might as well add this bit of info just in case. The international hoyolab site now gives a  different url format if copied from the mobile app's share function (similar to Reddit). For the example link provided above it's as follows:

Desktop link:
https://www.hoyolab.com/article/14554718/

Mobile app share link:
https://hoyo.link/80GCFBAL?q=25tufAgwB8N

I don't know if the Chinese version of the site has a corresponding mobile app, so someone would need to check and see if the same happens there.
