### ISSUE TITLE
NoMethodError in sitemap when relation is empty

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5293]
For example, GET /sitemap.xml?sitemap=pools raises an error if there are no pools. Caused by .maximum returning nil for no results:

https://github.com/danbooru/danbooru/blob/a07234121da46fd2f090226d0498a3e6cb90cd60/app/views/static/sitemap_index.xml.erb#L4

However empty sitemaps are not valid so adding a `.to_i` is insufficient.

**Comment by evazion** [comment]
Generating empty sitemaps is unavoidable when the table is empty, so I think the best we can do is exclude empty sitemaps from `/robots.txt` so they don't get crawled.
