### ISSUE TITLE
CSS recompilation crashes in dev mode

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#5299]
Trying to edit the css in a local instance and running under RAILS_ENV=development returns this:

```

[PID:522] [Webpacker] Compiling...
[PID:522] [Webpacker] Compilation failed:
Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)

$ yarn run [--inspect] [--inspect-brk] <scriptName> ...

```

**Comment by nonamethanks** [comment]
PEBKAC error, I didn't do `docker compose pull`. 🤦

**Comment by nonamethanks** [comment]
Spoke too soon. The typopro problem is fixed by a pull, however I had to do "yarn install" inside the container to fix the problem.

**Comment by evazion** [comment]
Not sure what the original issue was, but now there's a `bin/dev` script for launching a dev mode environment which should fix these "it doesn't work on my machine" problems.
