### ISSUE TITLE
Error response from daemon: Invalid container name (-redis-1), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

### ISSUE THREAD

**Issue by Michaelwhite34** [danbooru/danbooru#5304]
docker-compose up
[+] Running 0/0
 - Container -postgres-1  Creating                                                                                 0.0s
 - Container -iqdb-1      Creating                                                                                 0.0s
 - Container -redis-1     Creating                                                                                 0.0s
Error response from daemon: Invalid container name (-redis-1), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

**Comment by nonamethanks** [comment]
That doesn't sound right. Did you alter the default docker compose file?

**Comment by Michaelwhite34** [comment]
> That doesn't sound right. Did you alter the default docker compose file?

No, but this is on docker windows, would that be a problem ?

**Comment by nonamethanks** [comment]
How are you running the compose file? I don't have docker desktop, but if you run `docker compose up` from the cmd in the same folder as where you saved the file do you get a different result?

**Comment by Michaelwhite34** [comment]
> How are you running the compose file? I don't have docker desktop, but if you run `docker compose up` from the cmd in the same folder as where you saved the file do you get a different result? Also what version of docker (`docker -v`)?

Docker version 20.10.20, build 9fdeb9c
First I downloaded that yaml using idm and then docker compose up.

**Comment by nonamethanks** [comment]
It's weird because normally it would generate containers called <directory>-postgres-1, etc, where <directory> is the name of the directory you're launching the command from. That's overridden by COMPOSE_PROJECT_NAME, but only if it's not empty.

What happens if you add a line immediately under version, specifying the name, like this?
```
version: "3.4"

name: danbooru

```

**Comment by Michaelwhite34** [comment]
> It's weird because normally it would generate containers called directory-postgres-1, etc, where "directory" is the name of the directory you're launching the command from. That's overridden by COMPOSE_PROJECT_NAME, but only if it's not empty.
> 
> What happens if you add a line to the file immediately under version, specifying the name, like this?
> 
> ```
> version: "3.4"
> 
> name: danbooru
> ```

It works ! WTF

**Comment by nonamethanks** [comment]
I'm curious, if you type `echo %cd%` from the cmd in the same place you were running docker-compose from, what does it say? Maybe it's from a folder with a weird name?

**Comment by Michaelwhite34** [comment]
> I'm curious, if you type `echo %cd%` from the cmd in the same place you were running docker-compose from, what does it say? Maybe it's from a folder with a weird name?

It's actually D:/

**Comment by nonamethanks** [comment]
Ah yeah, that would explain it. I pushed a fix for this.
