### ISSUE TITLE
Guide to upload image, tag and export metadata ?

### ISSUE THREAD

**Issue by Michaelwhite34** [danbooru/danbooru#5305]
I want to tag some images and export metadata. Are there guides for doing these ?

**Comment by nottalulah** [comment]
It's not really clear what you're asking. There's an Upload button on the main page, and you can just put tags into the tag box.

**Comment by Michaelwhite34** [comment]
> It's not really clear what you're asking. There's an Upload button on the main page, and you can just put tags into the tag box.

To upload I have to create an account, and then "Error: Can't verify CSRF token authenticity."

**Comment by nottalulah** [comment]
You might be running into the same as issue #5235. Take a look at the replies there and see if they help.

**Comment by Michaelwhite34** [comment]
> You might be running into the same as issue #5235. Take a look at the replies there and see if they help.

How should I modify the file  config/initializers/session_store.rb using docker ? I don't know how to inspect file structure, I guess docker works like a vm and there should be something like files when we install normally ?

**Comment by nottalulah** [comment]
You can just add it as a volume in the docker-compose file.

```yml
services:
  danbooru:
    volumes:
      - ./config/initializers/session_store.rb:/danbooru/config/initializers/session_store.rb
```

**Comment by Michaelwhite34** [comment]
> You can just add it as a volume in the docker-compose file.
> 
> ```yaml
> services:
>   danbooru:
>     volumes:
>       - ./config/initializers/session_store.rb:/danbooru/config/initializers/session_store.rb
> ```
I am using GWSL, the files are located in \\wsl$, so I did a search and found it.

**Comment by Michaelwhite34** [comment]
There seems to be a 50 mb upload size limit, can I disable it ?

**Comment by nottalulah** [comment]
I don't think you can disable it entirely but you can set `DANBOORU_MAX_FILE_SIZE: <some really big number>` in the `environment` section of the base template to increase it`

**Comment by Michaelwhite34** [comment]
> I don't think you can disable it entirely but you can set `DANBOORU_MAX_FILE_SIZE: <some really big number>` in the `environment` section of the base template to increase it`

I don't get it, which file should I modify ?

**Comment by nottalulah** [comment]
The same one as before... (docker-compose.yml)

**Comment by Michaelwhite34** [comment]
> The same one as before... (docker-compose.yml)

I can't find "DANBOORU_MAX_FILE_SIZE" in docker-compose.yml

**Comment by nottalulah** [comment]
Yes, it's not there. Add it.

**Comment by Michaelwhite34** [comment]
> DANBOORU_MAX_FILE_SIZE:

Something like DANBOORU_MAX_FILE_SIZE: 10GB ?

**Comment by nottalulah** [comment]
It'll have to be the full number, suffixes will not work. Set it to 10737418240 for 10GB.

**Comment by Michaelwhite34** [comment]
> It'll have to be the full number, suffixes will not work. Set it to 10737418240 for 10GB.

x-base-template: &base-template
  user: root
  image: ghcr.io/danbooru/danbooru:production # you can change this to danbooru:master to get the latest upstream changes
  environment:
    DANBOORU_MAX_FILE_SIZE:<10737418240>
    RAILS_ENV: production # Set this to development to force danbooru to freshly compile js/css assets (for example if you're doing local development)
    RAILS_SERVE_STATIC_FILES: true


yaml: line 29: mapping values are not allowed in this context

**Comment by nottalulah** [comment]
You don't literally include the < >, it was just meant as a substitution.

**Comment by Michaelwhite34** [comment]
> You don't literally include the < >, it was just meant as a substitution.

I tried that too, same error,

**Comment by nottalulah** [comment]
You must have bad indentation or something. I can't tell because you didn't format the file properly.

**Comment by Michaelwhite34** [comment]
> You must have bad indentation or something. I can't tell because you didn't format the file properly.

Adding a space solved it,

**Comment by Michaelwhite34** [comment]
In the dialog box it shows max upload size 10 GB, but it doesn't seem to change the actual size, still it only allows a upload small size of images. Seems to have 100 images limit.

**Comment by nottalulah** [comment]
There's no config option to increase the maximum number of files you can upload at once. You'd have to edit the source code and re-build the Docker image to do that currently.

**Comment by Michaelwhite34** [comment]
> There's no config option to increase the maximum number of files you can upload at once. You'd have to edit the source code and re-build the Docker image to do that currently.

But the files are actually stored locally, can I somehow just move the images to the "post image" location ?

**Comment by nottalulah** [comment]
I would really advise you don't try that unless you have a lot of technical experience with Rails and Danbooru.

**Comment by Michaelwhite34** [comment]
> I would really advise you don't try that unless you have a lot of technical experience with Rails and Danbooru.

Ok, then can I delete some of my posts ?

**Comment by nottalulah** [comment]
If you mean uploads that were not turned into posts yet then no it's not currently supported. You would have to do it manually in the terminal.

**Comment by Michaelwhite34** [comment]
> If you mean uploads that were not turned into posts yet then no it's not currently supported. You would have to do it manually in the terminal.

I mean how to delete some uploads.

**Comment by nonamethanks** [comment]
There's an "expunge" button on the sidebar if you're admin or owner in your instance.
