### ISSUE TITLE
`StatementInvalid` Error When Querying the `media_assets` Attribute of Uploads

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#5312]
The following URL produces an exception.

* **URL:** https://danbooru.donmai.us/uploads.json?search[media_assets][md5]=8c16bf3a57cfd0bcc807e7aa69358832
```json
{
  "success": false,
  "error": "ActiveRecord::StatementInvalid",
  "message": "",
  "backtrace": [
    "app/logical/pagination_extension.rb:141:in `records'",
    "app/logical/application_responder.rb:29:in `to_format'",
    "app/controllers/application_controller.rb:66:in `respond_with'",
    "app/controllers/uploads_controller.rb:30:in `index'"
  ]
}
```

Using the functionally equivalent long form does not however.

* **URL:** https://danbooru.donmai.us/uploads.json?search[upload_media_assets][media_asset][md5]=8c16bf3a57cfd0bcc807e7aa69358832

According to the code, that attribute path should still be accessible though.

https://github.com/danbooru/danbooru/blob/5b19e544cf1b08f823aa53e5ea08436ef0c92d6e/app/models/upload.rb#L96

Or should that path just be dropped altogether, and just always use the long form instead?

**Comment by nottalulah** [comment]
Seems to have been broken by 5565c753d0317d0caabc51df597be20311420bc5.
