### ISSUE TITLE
API error: ActionController::InvalidAuthenticityToken

### ISSUE THREAD

**Issue by anpuhach** [danbooru/danbooru#5319]
It appears in Flexbooru app (which uses danbooru API) when trying to add an image to favorites. Please take a look: https://github.com/flexbooru/flexbooru/issues/199

![image](https://user-images.githubusercontent.com/69940513/198750003-9db6e5d3-f158-4175-b1c3-bdc9c105e90d.png)

**Comment by nottalulah** [comment]
This is an issue on their end. Clients that properly implement the API have no issues.

**Comment by nonamethanks** [comment]
Login and Api Key are being sent [here](https://github.com/flexbooru/flexbooru/blob/130469d2d38521c68f295c79ef4be45d85009203/android/src/main/java/onlymash/flexbooru/data/api/DanbooruApi.kt#L52) as POST data. They should instead be sent as basic http authentication or url parameters. See https://github.com/danbooru/danbooru/commit/185c8bac82044c6fe17d4f0dfeefc761ed92dd64. These variables are not part of the data that's being created, so they should not be sent as part of the POST body.
