### ISSUE TITLE
New samples and thumbnails have wrong colors

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#5323]
Compare [old](https://cdn.donmai.us/180x180/5c/c7/5cc7d5b0d855031070390605244e5805.jpg) vs [new](https://cdn.donmai.us/180x180/1c/e0/1ce0b345a7883eb0f4dae0da6bad91e9.jpg), the old one is closer to the [full size](https://cdn.donmai.us/original/1c/e0/1ce0b345a7883eb0f4dae0da6bad91e9.png). All new thumbnails are affected.

Another example: [old ](https://cdn.donmai.us/180x180/1c/75/1c759f40927459f34b8f94c0f9868239.jpg)vs [new ](https://cdn.donmai.us/180x180/43/6a/436aee367b7f40790158dcb7c44d8e6c.jpg)vs [full size](https://cdn.donmai.us/original/43/6a/436aee367b7f40790158dcb7c44d8e6c.png)

**Comment by NamelessContributor** [comment]
This also affects samples, e.g.
https://cdn.donmai.us/sample/35/fd/sample-35fd9fb11b1705d8d0c7abf0cb9b04e9.jpg
https://cdn.donmai.us/original/35/fd/35fd9fb11b1705d8d0c7abf0cb9b04e9.jpg
