### ISSUE TITLE
Queries with "ordfav:<username>" and geometry attributes (e.g. "ratio:", "height:") crashes the api/site.

### ISSUE THREAD

**Issue by dotHTM** [danbooru/danbooru#5335]
## What I was trying to do

Run a query of my newest favorites, with certain ratio and resolution tags.

Example: `ordfav:<username> ratio:4/3`

## What I expected

A list of images whose aspect ratio is 4/3 (about 1.33), that I have favorited, and ordered from newest to oldest fav up to my page limit.

## What happens

The following error message appears:

```
Error
Unexpected error: ArgumentError.

Details
ArgumentError exception raised
app/logical/post_query_builder.rb:248:in `each'
app/logical/post_query_builder.rb:248:in `reduce'
app/logical/post_query_builder.rb:248:in `block in build_relation'
app/logical/post_query/ast.rb:330:in `visit'
app/logical/post_query_builder.rb:229:in `build_relation'
app/logical/post_query_builder.rb:260:in `posts'
app/logical/post_query.rb:81:in `posts'
app/logical/post_query.rb:264:in `block in exact_count'
app/models/application_record.rb:153:in `with_timeout'
app/logical/post_query.rb:263:in `exact_count'
app/logical/post_query.rb:258:in `block in cached_count'
app/logical/cache.rb:39:in `get'
app/logical/post_query.rb:257:in `cached_count'
app/logical/post_query.rb:220:in `fast_count'
app/logical/post_query.rb:207:in `post_count'
app/logical/post_sets/post.rb:116:in `post_count'
app/logical/post_sets/post.rb:110:in `posts'
app/controllers/posts_controller.rb:24:in `index'
```

## other notes

if I run `ordfav:<username>` I get the list of favorited items in the expected order.

If I run `ratio:4/3` I get images that have an aspect ratio of 4/3.

When I include both in the same query, the page crashes in the above error.

This also occurs on inequalities as well as equals tags when included with the "ordfav:<username>" tag.

## work around

The `fav:<username>`  tag appears to work with geometry tags, however the ordering of the posts is by upload date rather than favorited date.

**Comment by evazion** [comment]
Fix currently running on Betabooru: https://betabooru.donmai.us/posts?tags=ordfav:evazion+ratio:4/3.
