### ISSUE TITLE
Grab bilibili emotes links in dtext using emote names

### ISSUE THREAD

**Issue by HeeroWingZero** [danbooru/danbooru#5355]
The bookmarklet currently grabs the custom emotes as long raw links, such as below, from [post #5846818](https://danbooru.donmai.us/posts/5846818).
```
Day80.申鹤
我的美丽老婆快复刻吧 http://i0.hdslb.com/bfs/emote/55daf208ff65bc899cd2879f156329e4bcfda6fe.png http://i0.hdslb.com/bfs/emote/1d0126a19420fbecfde610e613bdd73f31ed28dc.png
（参考了一下官图）
```

Manually copying and pasting the source commentary nets the following: 
```
Day80.申鹤
我的美丽老婆快复刻吧[绘光计划专属_就要搞颜色][绘光计划专属_饭饭]
（参考了一下官图）
```

Grabbing the commentary in the following dtext format would maintain links to the external emotes, without bloating commentary length with raw links
```
Day80.申鹤
我的美丽老婆快复刻吧"[绘光计划专属_就要搞颜色]":[http://i0.hdslb.com/bfs/emote/55daf208ff65bc899cd2879f156329e4bcfda6fe.png]"[绘光计划专属_饭饭]":[http://i0.hdslb.com/bfs/emote/1d0126a19420fbecfde610e613bdd73f31ed28dc.png]
（参考了一下官图）
```

**Comment by evazion** [comment]
This was fixed in #5628.
