### ISSUE TITLE
Captcha protect post tag reads

### ISSUE THREAD

**Issue by Tenpi** [danbooru/danbooru#5378]
I think that you should treat tag and tag history reads as a protected privilege, so that it would be much harder for people to scrape your site for machine learning. I am aware that you can just download images and AI generate tags but it still isn't as accurate as handwritten ones.

Firstly I don't think that mass search endpoints should return any tags at all and tags should only be accessible when you access a single post like https://danbooru.donmai.us/posts/1111111.json. However, you can retrieve the tags for a mass number of posts provided that the tags cannot be traced to a single post (such as to show the tags on the sidebar). 

This would allow you to keep track of each individual post tag reads and set up a counter, so that after you access X amount of posts (such as 100 or 200) you will need to solve a captcha to see the tags of anymore posts. Or you can continue without solving the captcha and browse normally but you just won't be able to see the post tags.

I can see this becoming a problem mainly for the comments page and tooltips. For the comments page, I think tags should be stripped entirely as it's not really important to show them since the focus is on the comments. Keeping the functionality of tooltips would be the biggest problem because you would hit the captcha limit very quickly and it would get annoying. There should be an additional button that you click in the tooltip to show the tags so only the tags that you want to see get counted. Also, the tags are added to a `data-tags` attribute in the html and that should get removed. 

This won't stop the most prolific scrapers which use multiple ip and pay for captcha solving services, but I think those are hassles enough to stop a good portion of people. As for applications this would mostly stop the danbooru repost bots such as the one that reposts everything uploaded to danbooru onto gelbooru. I think AI tags would be a suitable replacement since while they might have many mistakes, they are good enough to use for searching purposes. 

It's unfortunate that some legitimate apps will be affected but in my opinion it's more important that you make it harder to scrape the tags of every post because I feel like it's too easy currently.

**Comment by nonamethanks** [comment]
This would completely destroy any API functionality, including for bots that we use for fixing artist_request, generating tag reports, and other very important parts of the site.

**Comment by Tenpi** [comment]
Meta tags don't need to be protected since they are too broad to be useful in ML. Like all breaking changes, I think you can always find new workarounds.

There can be a new endpoint that only returns aggregated tags for multiple posts (let's say at least 10 or more) it's only important that the tags cannot be traced back to a single post.

And about effectiveness, I think if people have to pay money to scrape your site it would probably mitigate the vast majority of scrapers. But if you find that these measures aren't effective you could always revert it back.

**Comment by Tenpi** [comment]
One more thing that I will add is that it seems like searches for `banned_artist` still include the source links and tags:

https://danbooru.donmai.us/posts.json?tags=banned_artist 

Since many of the source links are direct image links, this doesn't stop those works from being used in ML at all. I think that your server should strip that data out to the public.

**Comment by nonamethanks** [comment]
Removing or limiting the API this way would break pretty much anything and everything, including basic things like mobile browsing apps or downloaders like Hydrus. Go look at sankaku to see why that's a terrible idea.
