### ISSUE TITLE
Add bookmarklet support for Behance

### ISSUE THREAD

**Issue by HeeroWingZero** [danbooru/danbooru#5379]
Example post: https://www.behance.net/gallery/97612065/SailorMoon
https://www.behance.net/gallery/97612065/SailorMoon/modules/563634913

Example direct link: https://mir-s3-cdn-cf.behance.net/project_modules/fs/ea4c7e97612065.5ec92bae8dc45.jpg

Example sample links:
https://mir-s3-cdn-cf.behance.net/project_modules/1400/ea4c7e97612065.5ec92bae8dc45.jpg
https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/ea4c7e97612065.5ec92bae8dc45.jpg
https://mir-s3-cdn-cf.behance.net/project_modules/disp/ea4c7e97612065.5ec92bae8dc45.jpg

Note: FS links don't seem to generate for images that are smaller than 1400 px. See [this post](https://www.behance.net/gallery/137004683/Kakashi-and-Gojo-%28-Teachers-day-off-%29), which at most has a [max_1200 link](https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/f53adc137004683.62039f102cc00.jpg), and attempting to access an FS link nets a [blank white image](https://mir-cdn.behance.net/v1/rendition/project_modules/fs/f53adc137004683.62039f102cc00.jpg).

Example multi-image post: https://www.behance.net/gallery/37853367/The-Great-Sketch-Swap-of-2016
Permalinks can be created for individual images within groups, the following links both being from the aforementioned multi-image post
https://www.behance.net/gallery/37853367/The-Great-Sketch-Swap-of-2016/modules/235413399
https://www.behance.net/gallery/37853367/The-Great-Sketch-Swap-of-2016/modules/235473233
EDIT: Didn't notice it before, but the multi-image post is actually credited to multiple artists, with links to all their pages. For a different example, the following link has multiple images and is only linked to a single artist
https://www.behance.net/gallery/82080397/The-Revelation

**Comment by NamelessContributor** [comment]
Actual full-size URLs are like
https://mir-s3-cdn-cf.behance.net/project_modules/source/ea4c7e97612065.5ec92bae8dc45.jpg

Source: https://www.behance.net/gallery/77806021/HAIBANETachi
Sample in HTML: `<img data-ut="lightbox-image" src="`https://mir-s3-cdn-cf.behance.net/project_modules/fs/c84c0d77806021.5cb5e60c2f2fe.jpg
Full image: https://mir-s3-cdn-cf.behance.net/project_modules/source/c84c0d77806021.5cb5e60c2f2fe.jpg

Source: https://www.behance.net/gallery/105133445/My-Home
Sample in HTML: `<img data-ut="lightbox-image" src="`https://mir-s3-cdn-cf.behance.net/project_modules/2800_opt_1/8455bd105133445.5f72776aa4049.jpg
Full image: https://mir-s3-cdn-cf.behance.net/project_modules/source/8455bd105133445.5f72776aa4049.jpg

From [Image Max URL](/qsniyg/maxurl): `src.replace(/(\/project(?:_modules|s)\/+)[^/]*\//, "$1source/")`
