### ISSUE TITLE
Inconsistent zoom level on upload page

### ISSUE THREAD

**Issue by Fuuf7** [danbooru/danbooru#5382]
Something changed recently and now images with the same resolution have different zoom levels. This makes it unnecessarily difficult to tell if the images are truly a different size or not, considering that differences between pixiv, nicoseiga, twitter, and any variant sets could also cause it.

**Comment by deusexcalamus** [comment]
Seeing something similar 
![image](https://user-images.githubusercontent.com/8674645/210537911-5ec78a0d-44db-4511-ad7e-8b4a7f16993a.png)
