### ISSUE TITLE
INSTALL.debian fails on Debian: libssl1.0-dev has no installation candidate

### ISSUE THREAD

**Issue by ssterling** [danbooru/danbooru#5384]
I’m trying to install Danbooru on a Debian Bookworm VM using [INSTALL.debian](https://github.com/danbooru/danbooru/blob/master/INSTALL.debian) as of 61fa839, but I can’t successfully patch the script enough to fully work, even when using the [Ubuntu installation guide](https://github.com/danbooru/danbooru/wiki/Ubuntu-Installation-Help-Guide) as a vague guideline.  Following is the first issue I encounter in the script.

### Expected behavior

`curl -L -s https://raw.githubusercontent.com/danbooru/danbooru/master/INSTALL.debian -o install.sh && bash -e install.sh` installs onto a Debian system everything necessary for a Danbooru instance.

### Observed behavior

When run on a Debian Bookworm system, `curl -L -s https://raw.githubusercontent.com/danbooru/danbooru/master/INSTALL.debian -o install.sh && bash -e install.sh` fails with the following error messages:
```console
Package libssl1.0-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libssl1.0-dev' has no installation candidate
```

### Steps to reproduce

1. Install [Debian testing](https://cdimage.debian.org/cdimage/weekly-builds/amd64/) (2022-12-12 as of writing) on an AMD64 virtual machine using default settings, except for selecting an SSH server and deselecting desktop environments.
2. Log in as root.
3. Run `apt-get install -y build-essential git curl postgresql-15`, as the install script simply assumes the user has these packages installed.  (see also: #5385)
4. Run `curl -L -s https://raw.githubusercontent.com/danbooru/danbooru/master/INSTALL.debian -o install.sh && bash -e install.sh`, entering the hostname `pelly.ssterling.net` when prompted.

### Additional information

See [install.log](https://github.com/danbooru/danbooru/files/10300319/install.log).

The actual command run to execute the install script was `bash -e install.sh 2>&1 | tee install.log`, though, to my knowledge, this shouldn’t make any difference.

This might be a duplicate of #3481, but that got marked as stale.

**Comment by nonamethanks** [comment]
The canonical way to install danbooru is with docker. Is there a particular reason why you want to do it directly instead? Otherwise we strongly recommend just running the dockerfile.

**Comment by ssterling** [comment]
> Is there a particular reason why you want to do it directly instead?

I kept running into difficulties with Docker due to a lack of experience, so I thought I’d try installing it directly instead.  That, and nesting a container inside a VM seemed a bit odd (my server runs FreeBSD).

If manual installation isn’t actively maintained, would it be appropriate to note that in the README?

**Comment by nonamethanks** [comment]
I updated the README a bit. Honestly, the trouble you'll find trying to install danbooru manually is such that you'll have better luck just figuring out docker instead. Starting from [this line](https://github.com/danbooru/danbooru/blob/master/docker-compose.yaml#L25) there are some parameters you can edit in the docker-compose.yaml file that will help you customize your instance.

Not sure what the performance will be if you run it inside a VM, but i'd still recommend trying that first before trying to install Danbooru manually. If you're really set on doing that, you can check out the [dockerfile](https://github.com/danbooru/danbooru/blob/master/config/docker/Dockerfile.danbooru) to see the canonical steps it uses to create a Danbooru image and adapt them to your system. However if you run it manually you won't have things like iqdb automatically set up for you.

**Comment by nottalulah** [comment]
Docker containers have fairly minimal overhead (mainly in networking). If you're gonna run it in a VM anyway then Docker won't be much different.
