### ISSUE TITLE
INSTALL.debian assumes user has certain packages installed

### ISSUE THREAD

**Issue by ssterling** [danbooru/danbooru#5385]
As of 61fa839, [INSTALL.debian](https://github.com/danbooru/danbooru/blob/master/INSTALL.debian) executes the commands `git`, `curl`, `make` and `/etc/init.d/postgresql`.  On a Debian Bookworm system (2022-12-12 as of writing), I have to run `apt-get install -y build-essential git curl postgresql-15` in order to have these commands available.

**Comment by nonamethanks** [comment]
Closing as per #5384.
