### ISSUE TITLE
some skeb page(s) fail to upload

### ISSUE THREAD

**Issue by bipface** [danbooru/danbooru#5399]
attempting to upload <https://skeb.jp/@kurocazenosora/works/155> via `/uploads/new?url=...`
leads to `Upload failed: File is not an image or video`.
same result on betabooru and testbooru.

manually uploading the AVIF file seems to work fine, so I assume it's an issue with extraction.
the file in question: <https://cdn.donmai.us/original/53/a2/53a28680531955e76bb2c56c18f40f08.avif>

**Comment by evazion** [comment]
This was actually a bug in the .webp filetype detection code. Skeb gives us .webp files because we don't send the `Accept: image/avif` header.
