### ISSUE TITLE
Add bookmarklet support for note.com

### ISSUE THREAD

**Issue by HeeroWingZero** [danbooru/danbooru#5402]
Example Post: https://note.com/koma_labo/n/n32fb90fac512

Example Direct Link: https://assets.st-note.com/img/1623726537463-B8LOZ1JZUS.png

Example Sample: https://assets.st-note.com/img/1623726537463-B8LOZ1JZUS.png?width=2000&height=2000&fit=bounds&format=jpg&quality=85

**Comment by evazion** [comment]
Original images actually look like this:

https://d2l930y2yx77uc.cloudfront.net/img/1623726537463-B8LOZ1JZUS.png (4,570,943 bytes)

Not like this:

https://assets.st-note.com/img/1623726537463-B8LOZ1JZUS.png (1,407,697 bytes, noticeable dithering artifacts)

The `assets.st-note.com` link will give you the original file the first time somebody opens it, but after a few minutes a recompressed sample image is generated in the background and is served in place of the original file. The Cloudfront URL always returns the original file.

Also Note supports custom domains, which we currently don't support:

* https://note.finetoday.com/n/n419c467ac34e
* https://spodge.sports-f.co.jp/n/n7413cfd77176
* https://ur-toshikikou-gov.note.jp/n/nc13367bbd73c
