### ISSUE TITLE
How to delete not yet posted images from rails console?

### ISSUE THREAD

**Issue by frorayz** [danbooru/danbooru#5404]
I am trying to actually delete an uploaded image that is not yet made into a post. It just says "Deleted" but its not gone. How would I delete it for real with rails console? Thanks!

**Image for reference:** [image](https://imgur.com/upJWIG9)

**Comment by evazion** [comment]
Like this: `MediaAsset.find(1234).destroy!` where `1234` is the asset ID number (or `MediaAsset.last.destroy!` if it's the last upload). This may break things though or leave dangling records because normally assets are never hard deleted. Something like this may be better (untested):

```
asset = MediaAsset.find(1234)
asset.uploads.each(&:destroy!)
asset.ai_tags.each(&:destroy!)
asset.destroy!
```

**Comment by frorayz** [comment]
> asset.destroy!

Wow worked very nicely, thank you so much!
