### ISSUE TITLE
How to install optional services like IQDB, Archive & Reportbooru using Manual Install Method?

### ISSUE THREAD

**Issue by frorayz** [danbooru/danbooru#5405]
Hello,

I follow [this guide](https://github.com/danbooru/danbooru/wiki/Manual-Installation-Guide) to install Danbooru, but I am having problem installing the other services. How would I go install them manually? (I know I would have to git clone the repo's to Danbooru base install but not sure where to go from there).

Thank you in advance!

**Comment by nottalulah** [comment]
IQDB is included in the default docker-compose.yaml file. It should run fine without requiring configuration. Reportbooru doesn't even work right in production anymore, afaik. It got replaced with [native reports](https://danbooru.donmai.us/reports).

**Comment by frorayz** [comment]
> IQDB is included in the default docker-compose.yaml file. It should run fine without requiring configuration. Reportbooru doesn't even work right in production anymore, afaik. It got replaced with [native reports](https://danbooru.donmai.us/reports).

I see, Thanks for the information! Would you know how to install archive service manually?

**Comment by nottalulah** [comment]
Nope, it was easier to just remove the SQS-related bits of the code than try to set up that BS.

**Comment by frorayz** [comment]
> Nope, it was easier to just remove the SQS-related bits of the code than try to set up that BS.

I am guessing then archive working without SQS? How would I do the same? If you don't mind telling me.

**Comment by nottalulah** [comment]
No, the archives service is basically just an SQS processor. Danbooru queues post/pool changes into SQS, the archives service retrieves the changes and inserts them into a database. Just cut out the middle and have Danbooru insert changes directly into the database.

**Comment by frorayz** [comment]
> No, the archives service is basically just an SQS processor. Danbooru queues post/pool changes into SQS, the archives service retrieves the changes and inserts them into a database. Just cut out the middle and have Danbooru insert changes directly into the database.

That is a lot of middleware for greater complexity. Sounds better that way. Is there any additional steps you needed to do other than just the code changes? Does anything in DB need any changes? How would I achieve this?

**Comment by nottalulah** [comment]
The relevant tables should already be in the database. I made [this patch](https://gist.github.com/nottalulah/b8a037e4b993600f2bb8d2c60abf61a6) for my local Danbooru install which has seemed to work fine, but it's possible it could have issues I haven't noticed. Note that it leaves a lot of tests broken that I was too lazy to fix.

**Comment by frorayz** [comment]
> The relevant tables should already be in the database. I made [this patch](https://gist.github.com/nottalulah/b8a037e4b993600f2bb8d2c60abf61a6) for my local Danbooru install which has seemed to work fine, but it's possible it could have issues I haven't noticed. Note that it leaves a lot of tests broken that I was too lazy to fix.

Thank you so much for the patch! So I would just apply the patch and version history should work? and I don't really need tests.

**Comment by nottalulah** [comment]
> So I would just apply the patch and version history should work? and I don't really need tests.

It should, assuming it applies. I extracted it from a fork with other changes and haven't tested it standalone.

**Comment by frorayz** [comment]
> > So I would just apply the patch and version history should work? and I don't really need tests.
> 
> It should, assuming it applies. I extracted it from a fork with other changes and haven't tested it standalone.

Yea it failed 😓 

rayz@booru:~/danbooru$ git apply 0001-remove-SQS-requirement-for-post-pool-versions.patch
error: patch failed: app/controllers/pool_versions_controller.rb:2
error: app/controllers/pool_versions_controller.rb: patch does not apply
error: patch failed: app/controllers/post_versions_controller.rb:1
error: app/controllers/post_versions_controller.rb: patch does not apply
error: patch failed: app/logical/moderator/dashboard/queries/tag.rb:5
error: app/logical/moderator/dashboard/queries/tag.rb: patch does not apply
error: patch failed: app/logical/related_tag_query.rb:67
error: app/logical/related_tag_query.rb: patch does not apply
error: app/logical/sqs_service.rb: No such file or directory
error: patch failed: app/models/pool.rb:15
error: app/models/pool.rb: patch does not apply
error: patch failed: app/models/pool_version.rb:4
error: app/models/pool_version.rb: patch does not apply
error: patch failed: app/models/post.rb:88
error: app/models/post.rb: patch does not apply
error: patch failed: app/models/post_version.rb:7
error: app/models/post_version.rb: patch does not apply
error: patch failed: app/models/user.rb:117
error: app/models/user.rb: patch does not apply
error: patch failed: app/presenters/user_presenter.rb:90
error: app/presenters/user_presenter.rb: patch does not apply
error: patch failed: app/views/pools/_secondary_links.html.erb:5
error: app/views/pools/_secondary_links.html.erb: patch does not apply
error: patch failed: app/views/post_versions/index.html.erb:22
error: app/views/post_versions/index.html.erb: patch does not apply
error: patch failed: app/views/static/site_map.html.erb:64
error: app/views/static/site_map.html.erb: patch does not apply
error: patch failed: app/views/users/_statistics.html.erb:196
error: app/views/users/_statistics.html.erb: patch does not apply
error: patch failed: test/test_helper.rb:25
error: test/test_helper.rb: patch does not apply
error: test/test_helpers/pool_archive_test_helper.rb: No such file or directory
error: test/test_helpers/post_archive_test_helper.rb: No such file or directory

**Comment by nottalulah** [comment]
Try `git am -3 0001-remove-SQS-requirement-for-post-pool-versions.patch`. Its parent is a commit in my fork so it'll have to be merged instead.

**Comment by frorayz** [comment]
> Try `git am -3 0001-remove-SQS-requirement-for-post-pool-versions.patch`. Its parent is a commit in my fork so it'll have to be merged instead.

Applying: remove SQS requirement for post/pool versions
error: sha1 information is lacking or useless (app/models/post.rb).
error: could not build fake ancestor
Patch failed at 0001 remove SQS requirement for post/pool versions
hint: Use 'git am --show-current-patch=diff' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

Getting this now

**Comment by nottalulah** [comment]
I can't reproduce that. In a freshly-cloned Danbooru repo it applies with git am -3 for me.

**Comment by frorayz** [comment]
> I can't reproduce that. In a freshly-cloned Danbooru repo it applies with git am -3 for me.

Okay it worked on a really fresh pull of master. I will be testing if the changes work. Since I need to recreate my dbs.

**Comment by frorayz** [comment]
> The relevant tables should already be in the database. I made [this patch](https://gist.github.com/nottalulah/b8a037e4b993600f2bb8d2c60abf61a6) for my local Danbooru install which has seemed to work fine, but it's possible it could have issues I haven't noticed. Note that it leaves a lot of tests broken that I was too lazy to fix.

Thank you so much again, it working fabulously.  Really appreciate it ❤️. I will be closing this issues since my other questions are answered.

**Comment by cirnoscodingclass** [comment]
Hi, I am currently seeing the same error 

```
Applying: remove SQS requirement for post/pool versions
error: sha1 information is lacking or useless (app/models/post.rb).
error: could not build fake ancestor
Patch failed at 0001 remove SQS requirement for post/pool versions
hint: Use 'git am --show-current-patch=diff' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```

I'm currently running the latest build (427509f) so it might be breaking about of it. Is there a way you can update this script? Thanks.

**Comment by cirnoscodingclass** [comment]
> The relevant tables should already be in the database. I made [this patch](https://gist.github.com/nottalulah/b8a037e4b993600f2bb8d2c60abf61a6) for my local Danbooru install which has seemed to work fine, but it's possible it could have issues I haven't noticed. Note that it leaves a lot of tests broken that I was too lazy to fix.

Is there a way that this can be updated for the production branch [69ad1e0](https://github.com/danbooru/danbooru/commit/69ad1e0899946908ea293433aeac22f709bff9ce)?
