### ISSUE TITLE
Exclude deprecated tags from autocomplete in the post edit box

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5408]
It can cause a bit of confusion seeing deprecated tags while tagging and assuming you can add them. It would be nice to have them filtered out for tagging without removing them from search autocomplete.

**Comment by bipface** [comment]
a compromise could be to simply add a ~~strikethrough~~ or disabled style on deprecated results in general,
that would have the advantage of being able to identify deprecated tags regardless of whether you're searching or editing, plus not having to parameterise the autocomplete API based on search vs. edit and not creating confusion for users about why certain autocomplete results appear in some places and not others
