### ISSUE TITLE
Very long url-encoded links break commentary versions layout

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#5415]
https://danbooru.donmai.us/artist_commentary_versions?search%5Bpost_id%5D=6009659
https://danbooru.donmai.us/posts/6009659

On latest chrome.

![image](https://user-images.githubusercontent.com/12946050/214377731-c3191d1b-b07d-4c24-b093-5183dc888822.png)

**Comment by BrokenEagle** [comment]
"break" and "table" carry 2 very connotation when talking about Danbooru, i.e. exceptions and databases respectively, at least to myself they do. Reading the title, it seems like it's corrupting the commentary versions table in the database. Also, I wouldn't call that breaking regardless, as it still functions and is readable; instead, that's more like it's flowing outside its intended boundaries.

"Very long url-encoded links overflow the HTML cells on the commentary versions INDEX endpoint"

Or something like that. ¯\_(ツ)_/¯

**Comment by nonamethanks** [comment]
Yeah that's true, fixed the title.
