### ISSUE TITLE
pixiv uploads broken on testbooru

### ISSUE THREAD

**Issue by bipface** [danbooru/danbooru#5434]
<https://testbooru.donmai.us/uploads/new?url=https://www.pixiv.net/en/artworks/105262307>
→ `Upload failed: https://i.pximg.net/img-original/img/2023/02/11/01/28/46/105262307_p0.png failed with code 597.`

same source works fine on danbooru prod.

**Comment by evazion** [comment]
Fixed. Testbooru runs on Hetzner, which blocks Pixiv. The solution is to proxy Pixiv uploads through my home server, which may be slow.
