### ISSUE TITLE
GitHub-style dtext code blocks aren't rendered correctly in quotes

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5436]
[Here](https://danbooru.donmai.us/forum_posts/233529), the three closing backticks are included in the quote. Also happens in expands, probably others then.

**Comment by evazion** [comment]
Fixed in https://github.com/danbooru/dtext_rb/commit/c3d3976ec4e696491c1c49ab6e8ce7e3977b4ea7
