### ISSUE TITLE
Support new Bilibili link format

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5438]
Example: https://www.bilibili.com/opus/684571925561737250

The ID is the same as the old format, and old-format links still work (https://t.bilibili.com/684571925561737250).

**Comment by evazion** [comment]
The old format still seems to be in use for quoted posts, so I guess we shouldn't normalize links to the new format yet:

https://www.bilibili.com/opus/723052706467414039 (redirects to <https://t.bilibili.com/723052706467414039>)
