### ISSUE TITLE
Source showing as file://

### ISSUE THREAD

**Issue by Iratu2** [danbooru/danbooru#5441]
Hello,

I've noticed that all the uploads to my self hosted booru version give the post the file:// source if a file is uploaded manually.

![screenshot](https://user-images.githubusercontent.com/117584298/219893705-616acdde-b53f-4bf9-b13a-a1b73fef9fd2.png)

Is it an option I've missed somewhere to remove this after the upload finishes?

**Comment by NamelessContributor** [comment]
You can just delete the content of the source field and leave it empty, or write anything you want in there.

**Comment by Iratu2** [comment]
For every upload? my members don't do that so it gives my mods/approvers a lot more work to manually edit all uploads.

**Comment by ErikHumphrey** [comment]
There's no option, but you could try editing lines like https://github.com/danbooru/danbooru/blob/222b1a92ea9d78139a6465e79de3fca07f204e7e/app/models/upload.rb#L210 to use an empty string and rebuild the application.

**Comment by Iratu2** [comment]
> There's no option, but you could try editing lines like
> 
> https://github.com/danbooru/danbooru/blob/222b1a92ea9d78139a6465e79de3fca07f204e7e/app/models/upload.rb#L210
> to use an empty string and rebuild the application.

I have attempted this but did not work kept showing the source as file://, also turned source_url in line 214 to "" but resulted in a error upon uploading 
![image](https://user-images.githubusercontent.com/117584298/219900335-fa25d0f5-8870-47e8-8cd9-f73df0e0bcf5.png)

**Comment by evazion** [comment]
There's no option to change this because it's not feasible to have options for every behavior someone might want to change. Danbooru does this because we always want the original source, and the filename often contains clues towards the original source.

This is a better place to change it:

https://github.com/danbooru/danbooru/blob/ef2287382c53de98a78d161be8d5e28e550caccd/app/models/post.rb#L95-L126

Add something like `source = "" if source.to_s.starts_with?("file://")` near the top.

**Comment by Iratu2** [comment]
> There's no option to change this because it's not feasible to have options for every behavior someone might want to change. Danbooru does this because we always want the original source, and the filename often contains clues towards the original source.
> 
> This is a better place to change it:
> 
> https://github.com/danbooru/danbooru/blob/ef2287382c53de98a78d161be8d5e28e550caccd/app/models/post.rb#L95-L126
> 
> Add something like `source = "" if source.to_s.starts_with?("file://")` near the top.

This seems to work perfectly, thank you
