### ISSUE TITLE
Unable to view images remotely

### ISSUE THREAD

**Issue by yoannfelix** [danbooru/danbooru#5443]
Hi,

I installed danbooru using docker and I was able to access it on localhost:3000. I was also able to create an account, upload images and add tags. However when I access the website remotely using the ip address:3000, I am unable to view any images. 

I am however able to view the website, login and even upload new images (the new images do not load once they have been successfully uploaded. 

Where should be the image is the list of tags instead. I would appreciate some help fixing this. At the moment I can rdp into the server where docker is running but it is inconvenient. 

![image](https://user-images.githubusercontent.com/67986128/219902463-8a177e92-e064-47ee-8b51-e716283470e3.png)

**Comment by nottalulah** [comment]
You have to set the environmental variable DANBOORU_CANONICAL_URL to the URL you access it on. If your IP address is 192.168.0.5, for example, you would set it to http://192.168.0.5:3000 (or https, if you're using TLS). It defaults to localhost:3000 if you're using Docker Compose.

**Comment by yoannfelix** [comment]
DANBOORU_CANONICAL_URL: http://localhost:3000 is already set in the yaml that I used for docker compose.

**Comment by nottalulah** [comment]
Yes, I know. That means images will use http://localhost:3000 as a base URL which is incorrect if you are viewing them remotely. Change it to the machine's IP address or domain name.

**Comment by yoannfelix** [comment]
I see. Thank for clarifying it. That fixed it.

**Comment by Manaball123** [comment]
Is it possible to have canonical url change depending on what url you are accessing it on(e.g. canonical url = 127.0.0.1:3000 when accessing it on http://127.0.0.1:3000, and 192.168.1.1:3000 when accessing on http://192.168.1.1:3000)? I would assume it isn't on plain html, but maybe it can be done with js?
