### ISSUE TITLE
Email verifying returns a Access Denied page

### ISSUE THREAD

**Issue by Iratu2** [danbooru/danbooru#5444]
On my self hosted instance it keeps giving this error when trying to verify an email address

```

Access Denied

You do not have permission to visit this page. 
```
URL received in email, domain cut out since git doesn't like the site. `-snip-/users/1/email/verify?email_verification_key=eyJfcmFpbHMiOnsibWVzc2FnZSI6Ik1qWTBOemc9IiwiZXhwIjpudWxsLCJwdXIiOiJlbWFpbF9hZGRyZXNzL3ZlcmlmeSJ9fQ%3D%3D--7c361e35cfd3e1017442708a7e62fb18f812b4e53fcf66ab34fe6942ea9f60fd`

**Comment by nottalulah** [comment]
Just to be sure, you are logged in as user #​1?

**Comment by Iratu2** [comment]
Yes, I am. 
![image](https://user-images.githubusercontent.com/117584298/219907173-d212ae30-e863-4291-999c-1a18d0530fb9.png)

**Comment by evazion** [comment]
Make sure `secret_key_base` in your Danbooru config is set, otherwise things like email verification keys will be invalidated after every server load.

This is how to decode the key:

```
> Base64.decode64("eyJfcmFpbHMiOnsibWVzc2FnZSI6Ik1qWTBOemc9IiwiZXhwIjpudWxsLCJwdXIiOiJlbWFpbF9hZGRyZXNzL3ZlcmlmeSJ9fQ%3D%3D--7c361e35cfd3e1017442708a7e62fb18f812b4e53fcf66ab34fe6942ea9f60fd")
=> "{\"_rails\":{\"message\":\"MjY0Nzg=\",\"exp\":null,\"pur\":\"email_address/verify\"}}\r\xC3\xDC>\xDC\xDF\xAD^\xDF\x97\x1Fww\xB5\xD3^\xF8\xE3n\xF4\xF1\xAE\xDE\xEBg\xDB\xD7\xC7\xFC\xD7f\xF8{\x9D\xDFq\xFE\xBAi\xBD\xF8}\xEE\xBD\xE3g\x9A\xF5\xFE\xB4}"
> Base64.decode64("MjY0Nzg=")
=> "26478"
```

Check `http://<site>/emails/26478.json` and make sure it looks right. That's the email the verification key is for.

You can also try `EmailAddress.find_signed!("eyJfcmFpbHMiOnsibWVzc2FnZSI6Ik1qWTBOemc9IiwiZXhwIjpudWxsLCJwdXIiOiJlbWFpbF9hZGRyZXNzL3ZlcmlmeSJ9fQ%3D%3D--7c361e35cfd3e1017442708a7e62fb18f812b4e53fcf66ab34fe6942ea9f60fd")` in `bin/rails console` and see what that does. It should return your email. If you get an invalid signature error, then your secret key base is wrong.

**Comment by Iratu2** [comment]
> Make sure `secret_key_base` in your Danbooru config is set, otherwise things like email verification keys will be invalidated after every server load.
> 
> This is how to decode the key:
> 
> ```
> > Base64.decode64("eyJfcmFpbHMiOnsibWVzc2FnZSI6Ik1qWTBOemc9IiwiZXhwIjpudWxsLCJwdXIiOiJlbWFpbF9hZGRyZXNzL3ZlcmlmeSJ9fQ%3D%3D--7c361e35cfd3e1017442708a7e62fb18f812b4e53fcf66ab34fe6942ea9f60fd")
> => "{\"_rails\":{\"message\":\"MjY0Nzg=\",\"exp\":null,\"pur\":\"email_address/verify\"}}\r\xC3\xDC>\xDC\xDF\xAD^\xDF\x97\x1Fww\xB5\xD3^\xF8\xE3n\xF4\xF1\xAE\xDE\xEBg\xDB\xD7\xC7\xFC\xD7f\xF8{\x9D\xDFq\xFE\xBAi\xBD\xF8}\xEE\xBD\xE3g\x9A\xF5\xFE\xB4}"
> > Base64.decode64("MjY0Nzg=")
> => "26478"
> ```
> 
> Check `http://<site>/emails/26478.json` and make sure it looks right. That's the email the verification key is for.
> 
> You can also try `EmailAddress.find_signed!("eyJfcmFpbHMiOnsibWVzc2FnZSI6Ik1qWTBOemc9IiwiZXhwIjpudWxsLCJwdXIiOiJlbWFpbF9hZGRyZXNzL3ZlcmlmeSJ9fQ%3D%3D--7c361e35cfd3e1017442708a7e62fb18f812b4e53fcf66ab34fe6942ea9f60fd")` in `bin/rails console` and see what that does. It should return your email. If you get an invalid signature error, then your secret key base is wrong.

Okay it seems the secret key base was not set in the local_config thus creating a difference in the GoodJob process and the normal rails process, thanks for pointing me in the right direction.
