### ISSUE TITLE
can't search precisely for artist URLs containing spaces or literal asterisks using search[url_matches]=

### ISSUE THREAD

**Issue by bipface** [danbooru/danbooru#5447]
Example: [artist 76275](https://danbooru.donmai.us/artists/76275) has a url `http://dic.nicovideo.jp/a/tetla%20pot`.

Using Betabooru with the latest url_matches logic:

* searching for `http://dic.nicovideo.jp/a/tetla pot` yields anything containing `pot`: <https://betabooru.donmai.us/artist_urls?search[url_matches]=http%3A%2F%2Fdic.nicovideo.jp%2Fa%2Ftetla+pot>
* searching for `http://dic.nicovideo.jp/a/tetla%20pot` yields nothing: <https://betabooru.donmai.us/artist_urls?search[url_matches]=http%3A%2F%2Fdic.nicovideo.jp%2Fa%2Ftetla%2520pot>
* searching for `http://dic.nicovideo.jp/a/tetla*pot` finds the artist: <https://betabooru.donmai.us/artist_urls?search[url_matches]=http%3A%2F%2Fdic.nicovideo.jp%2Fa%2Ftetla%2apot>, but would also match urls with any other characters in that wildcard position. An uninformed user searching on the artist_urls page may struggle to think of this workaround, considering the search page offers no indication that the URL field accepts wildcards.

Example: [artist 43499](https://danbooru.donmai.us/artists/43499) has a url `https://dic.nicovideo.jp/a/カオス*ラウンジ`.

* searching for `https://dic.nicovideo.jp/a/カオス*ラウンジ` would also match urls with any other characters in that wildcard position.
* searching for `https://dic.nicovideo.jp/a/カオス%2aラウンジ` yeilds nothing: <https://betabooru.donmai.us/artist_urls?search[url_matches]=https%3A%2F%2Fdic.nicovideo.jp%2Fa%2F%E3%82%AB%E3%82%AA%E3%82%B9%252a%E3%83%A9%E3%82%A6%E3%83%B3%E3%82%B8>

**Comment by evazion** [comment]
Fixed it so that whitespace in artist URLs is percent-encoded. To search for an URL containing spaces, use `%20`. To search for an URL containing `*`, use `\*`.
