### ISSUE TITLE
Add timeout to thumbnail fetching, rather than making wiki pages time out

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#5451]
Related to issue #4975, pretty much every single deprecated wiki times out now, because all posts are old. This issue has become a lot more noticeable recenly due to the general slowness of the site:

https://danbooru.donmai.us/wiki_pages/areolae
https://danbooru.donmai.us/wiki_pages/silver_hair
https://danbooru.donmai.us/wiki_pages/face

These are only a few of the examples. 
Wiki thumbnails should be fetched with a timeout, so that in case they fail to be fetched the site would still return a wiki page without thumbnails rather than showing a search timeout.

**Comment by BrokenEagle** [comment]
One addition to the above could be not fetching thumbnails at all on deprecated wikis.

**Comment by bipface** [comment]
it may be worth giving the same treatment to other pages containing thumbnail lists such as user profiles and artist entries.

**Comment by nottalulah** [comment]
> One addition to the above could be not fetching thumbnails at all on deprecated wikis.

This happened today on an [undeprecated tag](https://danbooru.donmai.us/wiki_pages/millipen_(medium)) so that solution would not be a complete fix.
