### ISSUE TITLE
Add a mobile upload page view similar to desktop pop-up window

### ISSUE THREAD

**Issue by kagayakushininggate** [danbooru/danbooru#5453]
Add an option to hide or lower at least some of the following: Parent, Commentary, Fetch Source Data, Similar Posts and Source sections of the mobile upload page. Currently, the pop-up window with just Rating and Tags is unusable on mobile as it cannot be moved or resized there, and to be fair likely wouldn't be comfortable to use even if it was.

Similarly to the pop-up window, the view should be retractable to the normal, full form at any time (to, say, check for duplicates or the commentary).

(Imo it would be nice if in that view the Ratings section was lowered below the Tags section, but it might not be a well-received idea as the site uses the opposite literally everywhere else)

(First is a normal screenshot, second is a screenshot of the page adjusted for the proposed idea)
![image](https://user-images.githubusercontent.com/116494113/221379711-85d940b5-5750-4b23-9bfa-87809e544dcc.png)
![image](https://user-images.githubusercontent.com/116494113/221379716-1bf6d639-efbf-4a49-b523-fd4e5f96ed47.png)

**Comment by evazion** [comment]
This is what it looks like now:

![](https://cdn.discordapp.com/attachments/710192137878241372/1081865701045837885/image.png)

I think the original goal has been met. There's still a lot of scrolling back and forth between the image and the related tags, but it should be better than it was before.
