### ISSUE TITLE
Cloudflare interrupting API calls

### ISSUE THREAD

**Issue by Coder-Tavi** [danbooru/danbooru#5455]
As the title states, Cloudflare's protection is interrupting my calls to the API. I have noticed that this is frequently occurring with my Discord bot to the point that it fails to parse the response properly (It expects JSON but gets an HTML file). Is my User Agent header wrong or needs to be amended? Discord notes in [their documentation](https://discord.com/developers/docs/reference#user-agent) that the User Agent header may trigger Cloudflare protections. Does Danbooru work the same way?

I use the following:
* [`Node.js v19.6.0`](https://nodejs.org)
* [`NPM 8.19.2`](https://npmjs.com/package/npm)

My packages that relate to this issue are:
* [`discord.js v13.8.1`](https://npmjs.com/package/discord.js)
* [`node-fetch v2.6.7`](https://npmjs.com/package/node-fetch) (v3 is ESM, which I can't use)

My API call is as follows:
```js
const { default: fetch } = require("node-fetch");

// ...

/*
 * interaction = CommandInteraction
 * options = CommandInteractionOptionResolver (interaction.options)
 */
let tags = options.getString("tag").replace(/\(/g, "%28").replace(/\)/g, "%29");

const safe = !interaction.channel.nsfw || options.getBoolean("safe_search") ? true : false;
const limit = options.getNumber("limit") ?? 10;
if(safe) tags += "+rating:g";
tags += "+random:" + limit;
const params = new URLSearchParams();
params.append("login", config.danbooru["username"]);
params.append("api_key", config.danbooru["api_key"]);

fetch(`https://danbooru.donmai.us/posts.json?tags=${tags}&${params.toString()}`, { timeout: 5000 })
  .then(r => r.json());
  // And it fails here, because the response is an HTML page
```

As an interesting side note, I did a request in my browser to a `.json` endpoint without the token parameters (Since I was logged in) and experienced a Cloudflare challenge.

**Comment by nonamethanks** [comment]
You need to set a valid user-agent to do API calls.

**Comment by Coder-Tavi** [comment]
What could a valid User-Agent look like? I assume just the default node-fetch one doesn't work (`node-fetch/1.0 (+https://github.com/node-fetch/node-fetch)`)?

**Comment by nottalulah** [comment]
Anything custom. Normally you'd make it similar to that one: `BotName/Version (+Contact URL)`.

**Comment by Coder-Tavi** [comment]
I'll test this out and see what happens.

**Comment by Coder-Tavi** [comment]
Encountered a similar bug with Discord using curl. Applied a valid User Agent and it allowed my request. This is resolved now.
