### ISSUE TITLE
Twitter: add support for quote tweets

### ISSUE THREAD

**Issue by NamelessContributor** [danbooru/danbooru#5456]
Example: https://twitter.com/mowa_yururi/status/1631298400132952065 (fails with "doesn't contain any images")

**Comment by BrokenEagle** [comment]
Can't you just click the quote tweet and upload from there?

**Comment by evazion** [comment]
Wontfix, for the same reason we don't do this for Tumblr (#3619). The quote tweet itself can contain an image. That means that if the quote tweet doesn't contain an image, then presumably we would grab the original tweet instead, but if it does contain an image, then presumably we would grab only the image from the quote tweet. That would be confusing behavior.

As a matter of general principle, when you upload a post from a different site, it should only grab the post you give it. If you upload tweet A, it shouldn't grab tweet B instead. Those are two different posts that can possibly contain two different images by two different artists.
