### ISSUE TITLE
Allow access to own media assets when out of upload slots.

### ISSUE THREAD

**Issue by hdk5** [danbooru/danbooru#5478]
Not being able to post at the moment should not completely block access to the posting form itself. Error should be given on clicking "Post" on aforementioned form instead.

**Comment by evazion** [comment]
This will let you pretag your uploads while you wait for your posts to be approved, but I'm afraid it will lead to frustration when people try to post before realizing they're at their upload limit.

**Comment by hdk5** [comment]
Well, the upload slots counter is still there near "Post" button, so you could notice it right away, and filled fields don't reset after you try to post and get an error anyway - similarly to when you, for example, forget to select rating.

More clear indication would probably be a bit more helpful, but I personally don't need it.

Thank you.
