### ISSUE TITLE
Error after updating to latest  master

### ISSUE THREAD

**Issue by Iratu2** [danbooru/danbooru#5483]
Running into the following error after merging to the current master on git,

```
-- execute("ALTER TABLE media_assets VALIDATE CONSTRAINT media_assets_pixel_hash_check_not_null;")
   (3.6ms)  ALTER TABLE media_assets VALIDATE CONSTRAINT media_assets_pixel_hash_check_not_null;
  ↳ app/logical/migration_helpers.rb:15:in `block (2 levels) in add_not_null_constraint'
   (0.8ms)  SELECT pg_advisory_unlock(7191674008296795990)
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

PG::CheckViolation: ERROR:  check constraint "media_assets_pixel_hash_check_not_null" of relation "media_assets" is violated by some row
/home/danbooru/atfbooru/app/logical/migration_helpers.rb:15:in `block (2 levels) in add_not_null_constraint'
/home/danbooru/atfbooru/app/logical/migration_helpers.rb:13:in `block in add_not_null_constraint'
/home/danbooru/atfbooru/app/logical/migration_helpers.rb:12:in `add_not_null_constraint'
/home/danbooru/atfbooru/db/migrate/20230325143851_add_pixel_hash_index_to_media_assets.rb:7:in `change'

Caused by:
ActiveRecord::StatementInvalid: PG::CheckViolation: ERROR:  check constraint "media_assets_pixel_hash_check_not_null" of relation "media_assets" is violated by some row
/home/danbooru/atfbooru/app/logical/migration_helpers.rb:15:in `block (2 levels) in add_not_null_constraint'
/home/danbooru/atfbooru/app/logical/migration_helpers.rb:13:in `block in add_not_null_constraint'
/home/danbooru/atfbooru/app/logical/migration_helpers.rb:12:in `add_not_null_constraint'
/home/danbooru/atfbooru/db/migrate/20230325143851_add_pixel_hash_index_to_media_assets.rb:7:in `change'

Caused by:
PG::CheckViolation: ERROR:  check constraint "media_assets_pixel_hash_check_not_null" of relation "media_assets" is violated by some row
/home/danbooru/atfbooru/app/logical/migration_helpers.rb:15:in `block (2 levels) in add_not_null_constraint'
/home/danbooru/atfbooru/app/logical/migration_helpers.rb:13:in `block in add_not_null_constraint'
/home/danbooru/atfbooru/app/logical/migration_helpers.rb:12:in `add_not_null_constraint'
/home/danbooru/atfbooru/db/migrate/20230325143851_add_pixel_hash_index_to_media_assets.rb:7:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```
I have checked my DB and it seems all the 'pixel_hash' colums are set to NULL and I don't see a new fix in the fixes folder for this, would I need to run one of the previous fixes?

**Comment by evazion** [comment]
This wasn't really documented but you need to run `FIX=true COND="pixel_hash IS NULL" ./script/fixes/123_refresh_media_metadata.rb` to generate the pixel hashes.

**Comment by Iratu2** [comment]
Ah I see, thank you for explaining, I'm running that now

**Comment by GlassedSilver** [comment]
I'm experiencing the same issue, really odd.

I hoped running the fix script would help, but to be fair I'm not sure I even executed it properly since my danbooru container keeps restarting over the constant error loop. That's by I edited my stack's danbooru image to run the fix script as entrypoint command with the two variables passed as env vars, but it didn't seem to help.

I'm a bit lost here. I guess something else I can try to do is manipulate my image in some way so it doesn't keep loop-restarting and then running the fix script manually by ssh-ing into the container, but then it doesn't seem to help necessarily?

**Comment by telinit** [comment]
So, my "solution" was:
1. Changed the container's starting command to something like `sleep 111111111`
2. Launched `docker compose up`
3. Ran the fix script 
> This wasn't really documented but you need to run `FIX=true COND="pixel_hash IS NULL" ./script/fixes/123_refresh_media_metadata.rb` to generate the pixel hashes.

4. Having zero experience in ruby, changed `./app/logical/migration_helpers.rb`:
added this code before `add_check_constraint`
```
begin
  remove_check_constraint(table, name: constraint_name)
rescue Exception
end
```
5. Ran this DB query for entries which were not 'fixed' in the step 3: 
`UPDATE media_assets SET pixel_hash=gen_random_uuid() WHERE pixel_hash IS NULL;`

6. Changed the container's starting command back to its default value.
7. ???
8. Profit

I don't recommend this way of 'fixing' the problem. If you wanna do it anyway, don't forget to make a backup.

**Comment by GlassedSilver** [comment]
> So, my "solution" was:
> 
>     1. Changed the container's starting command to something like `sleep 111111111`
> 
>     2. Launched `docker compose up`
> 
>     3. Ran the fix script
> 
> 
> > This wasn't really documented but you need to run `FIX=true COND="pixel_hash IS NULL" ./script/fixes/123_refresh_media_metadata.rb` to generate the pixel hashes.
> 
>     4. Having zero experience in ruby, changed `./app/logical/migration_helpers.rb`:
>        added this code before `add_check_constraint`
> 
> 
> ```
> begin
>   remove_check_constraint(table, name: constraint_name)
> rescue Exception
> end
> ```
> 
>     5. Ran this DB query for entries which were not 'fixed' in the step 3:
>        `UPDATE media_assets SET pixel_hash=gen_random_uuid() WHERE pixel_hash IS NULL;`
> 
>     6. Changed the container's starting command back to its default value.
> 
>     7. ???
> 
>     8. Profit
> 
> 
> I don't recommend this way of 'fixing' the problem. If you wanna do it anyway, don't forget to make a backup.

Not sure what I feel about generating a random UUID for when a pixel hash isn't generated otherwise.

Is this default behavior as a fallback? (I assume for stuff like zip files and such this is considered, but I haven't checked to verify the garbled output I got when I ran the fix script I gotta be honest)

**Comment by nottalulah** [comment]
You really should not fill random columns with junk data just to pass some null check. The fallback behavior is the MD5 of the file (rather than the pixels) in cases where Danbooru can't calculate a pixel hash. That is what happens for ugoiras (zips) for example. I'm not sure what cases the fix script would leave NULLs as it didn't happen to me with ugoiras and videos.

Anyway the issue was an oversight in the migration helper which was fixed in c72ee9edd2e71d10885f2e2e277599c48c8c15df.

**Comment by evazion** [comment]
Setting the pixel hash to a random value currently won't break anything, but it's better to set it to the file's MD5 if you have to set it to something and can't use the fix script for some reason. The way to do that is like this:

1. Run `docker compose up` to start Danbooru.
2. Run `docker ps` to find Danbooru's container name or ID. With Docker compose, it should be `danbooru-danbooru-1`.
3. Run `docker exec -it <container_name> bin/rails dbconsole -p` to get a database console inside the container.
5. Run `UPDATE media_assets SET pixel_hash = md5::uuid WHERE pixel_hash IS NULL;` to set the pixel hash to the image's MD5. Protip: Run `SELECT * FROM media_assets WHERE pixel_hash IS NULL;` first to check what it's going to update.

**Comment by GlassedSilver** [comment]
I'm gonna try it it this afternoon, thanks so much! :)
