### ISSUE TITLE
Newgrounds: Support posts with multiple artists

### ISSUE THREAD

**Issue by NamelessContributor** [danbooru/danbooru#5499]
Example: https://www.newgrounds.com/portal/view/874316 (NSFW)
Currently the names are concatenated, leading to an invalid URL in the source data field or when creating an artist entry for an existing post.
In the source data field it could instead show both artists, when creating an entry it could show separate URLs and names so you can easily delete the wrong ones.

**Comment by evazion** [comment]
The fix here is to assume the first artist listed is the main artist and to ignore the other artists. We have a deep assumption that sources only have a single artist and changing that would be a lot of work and not very worthwhile at the moment.
