### ISSUE TITLE
Tumblr: get PNG instead of JPEG (PNJ) samples

### ISSUE THREAD

**Issue by NamelessContributor** [danbooru/danbooru#5503]
This can be accomplished by replacing `pnj` extension with `png`:
https://64.media.tumblr.com/3da3970775ba820dbc80ef3c5dae479e/dcc12b025632aa86-5f/s21000x21000/05f92acb893af4b0f738f1518b49d624038c9c5e.pnj
https://64.media.tumblr.com/3da3970775ba820dbc80ef3c5dae479e/dcc12b025632aa86-5f/s21000x21000/05f92acb893af4b0f738f1518b49d624038c9c5e.png

**Comment by etoubleh** [comment]
Sometimes it pulls a JPG even if the URL says .png. For example: https://voodoothur.tumblr.com/post/183018590012

**Comment by evazion** [comment]
>Sometimes it pulls a JPG even if the URL says .png. For example: https://voodoothur.tumblr.com/post/183018590012

And sometimes the .pnj is actually a .png, and sometimes even the .jpg is actually a .png. So basically the file extension is meaningless.

It might be possible for the .pnj to be the best version if the .png is actually a .jpg and the .pnj is actually a .png, but I haven't found any examples of this.
