### ISSUE TITLE
Mihuashi image URLs are unparseable

### ISSUE THREAD

**Issue by 9suika** [danbooru/danbooru#5507]
Steps to reproduce:
1. Try to upload <https://image-assets.mihuashi.com/permanent/121765|-2022/05/17/09/Fl-Wj_aSluDB0Aa9wXN_KtUlQHJl.jpg> from URL

Expected outcome:
image is uploaded

Actual outcome:
> Upload failed: bad URI(is not URI?): "https://image-assets.mihuashi.com/permanent/121765|-2022/05/17/09/Fl-Wj_aSluDB0Aa9wXN_KtUlQHJl.jpg".

**Comment by bipface** [comment]
it's suspected that the vertical bar (`|`) is the culprit, however escaping it as `%7C` still yields the same error.

**Comment by 9suika** [comment]
[Workaround](https://danbooru.donmai.us/forum_posts/243927)
