### ISSUE TITLE
booru source errors (NoMethodError, URI::InvalidURIError)

### ISSUE THREAD

**Issue by red-tails** [danbooru/danbooru#5510]
I suspect that the handler for gelbooru and moebooru tries to read their source field, to extract artist info from there. There's multiple bugs related to this, which may be caused by the same, so I am combining them here for further investigation.

Source: https://gelbooru.com/index.php?page=post&s=view&id=7868427 (NSFW)
Source as listed there: `https://www.pixiv.net/artworks/99176572 [Direct link in description]`
Danbo: https://danbooru.donmai.us/uploads/10724032.json
```json
  "success": false,
  "error": "URI::InvalidURIError",
  "message": "",
  "backtrace": [
    "app/logical/danbooru/http/session.rb:27:in `each'",
    "app/logical/danbooru/http/session.rb:27:in `map'",
    "app/logical/danbooru/http/session.rb:27:in `cookies_for_request'",
    "app/logical/danbooru/http/session.rb:22:in `add_cookies'",
    "app/logical/danbooru/http/session.rb:15:in `perform'",
    "app/logical/danbooru/http/application_client.rb:20:in `block (2 levels) in perform'",
    "app/logical/danbooru/http/redirector.rb:18:in `perform'",
    "app/logical/danbooru/http/application_client.rb:20:in `block (2 levels) in perform'",
    "app/logical/danbooru/http/application_client.rb:23:in `perform'",
    "app/logical/danbooru/http.rb:209:in `request'",
    "app/logical/danbooru/http.rb:80:in `get'",
    "app/logical/pixiv_ajax_client.rb:399:in `get'",
    "app/logical/pixiv_ajax_client.rb:376:in `illust'",
    "app/logical/source/extractor/pixiv.rb:161:in `api_illust'",
    "app/logical/source/extractor/pixiv.rb:68:in `profile_url'",
    "app/logical/source/extractor/gelbooru.rb:15:in `profile_url'",
    "app/logical/source/extractor.rb:220:in `artists'",
    "app/models/post.rb:109:in `new_from_upload'",
    "app/controllers/uploads_controller.rb:44:in `show'"
```

Source: https://yande.re/post/show/918935 (NSFW)
Source as listed there: `https://www.pixiv.net/fanbox/creator/273185/post/1179371`
Danbo: https://danbooru.donmai.us/uploads/10724544.json (note: this isn't listed under status=completed, which I assume is also a bug)
```json
  "success": false,
  "error": "NoMethodError",
  "message": "",
  "backtrace": [
    "app/logical/source/extractor/fanbox.rb:117:in `api_response'",
    "app/logical/source/extractor/fanbox.rb:58:in `artist_name'",
    "app/logical/source/extractor/fanbox.rb:50:in `profile_url'",
    "app/logical/source/extractor/moebooru.rb:7:in `profile_url'",
    "app/logical/source/extractor.rb:220:in `artists'",
    "app/models/post.rb:109:in `new_from_upload'",
    "app/controllers/uploads_controller.rb:44:in `show'"
```
Thank you for investigating these bugs

Extra info: the above may also be linked to what you have previously bug-fixed in https://github.com/danbooru/danbooru/commit/2b9639e68ae7fce4a4265e0b01410584d2a12117

Source: https://gelbooru.com/index.php?page=post&s=view&id=6642778
Source as listed there: `https://www.reddit.com/r/ArknightsHQ/comments/qoy11i/utages_beauty/`
Danbo: https://danbooru.donmai.us/uploads/10725392.json
```json
  "success": false,
  "error": "NoMethodError",
  "message": "",
  "backtrace": [
    "app/logical/source/extractor/reddit.rb:50:in `artist_name'",
    "app/logical/source/extractor/reddit.rb:33:in `profile_url'",
    "app/logical/source/extractor/gelbooru.rb:15:in `profile_url'",
    "app/logical/source/extractor.rb:220:in `artists'",
    "app/models/post.rb:109:in `new_from_upload'",
    "app/controllers/uploads_controller.rb:44:in `show'"
```

**Comment by evazion** [comment]
The first bug is fixed in 31ea68368. The second bug was fixed in bdb08b7804b230b68bf2d982256f99e11c50e431. The third bug was fixed in 2b9639e68ae7fce4a4265e0b01410584d2a12117.
