### ISSUE TITLE
Add bookmarklet support for YouTube community posts

### ISSUE THREAD

**Issue by HeeroWingZero** [danbooru/danbooru#5517]
Becoming more common for artists to post images there, as well as vtubers posting their commissions. Worth noting that as far as I can tell, there's currently no way to copy the link from the mobile app.

Example link: https://www.youtube.com/channel/UCykMWf8B8I7c_jA8FTy2tGw/community?lb=UgkxRUblu0gHHXUZiOm3ZtjhWZXbsco1BKQy

Example sample: https://yt3.ggpht.com/SNOhIapK62CSYMEnO6rY6C99vYh-CAtCp-rye3E40Acg7JI5dOE7hyeLu7-2XdoqQExjfRutp98z1w=s1024-c-fcrop64=1,00000f64fffff09b-nd-v1

Example direct: https://yt3.ggpht.com/SNOhIapK62CSYMEnO6rY6C99vYh-CAtCp-rye3E40Acg7JI5dOE7hyeLu7-2XdoqQExjfRutp98z1w=s0?imgmax=0

**Comment by etoubleh** [comment]
The HTML links should be formatted like this: https://www.youtube.com/post/UgkxRUblu0gHHXUZiOm3ZtjhWZXbsco1BKQy

And the proper fullres image links use `=d` at the end, not `=s0?imgmax=0`.
