### ISSUE TITLE
How to run on arm

### ISSUE THREAD

**Issue by TimyIsCool** [danbooru/danbooru#5535]
Hi, Im wanting to run my own version to toy around with but it wont install on docker, any help?

**Comment by nottalulah** [comment]
ARM builds were disabled in CI because they took too much time to complete, IIRC. You can just build the image locally.

**Comment by TimyIsCool** [comment]
how would I build the image locally for docker?

**Comment by nottalulah** [comment]
Clone the git repo and run the build command in it:

https://github.com/danbooru/danbooru/blob/f955718672a31e9c19afc5381eceeb0c2e7653d6/lib/tasks/danbooru.rake#L123

You'll need docker buildx installed, might not be included by default on certain platforms.
