### ISSUE TITLE
Respecting tls_verify for SMTP

### ISSUE THREAD

**Issue by tuxpizza** [danbooru/danbooru#5537]
I've been trying to get email to work properly on my instance.

Currently under my danbooru_local_config.rb I have something that looks a like this:

`def mail_settings
  {
    address: "192.168.1.99",
    port: "25",
    user_name: "no-reply@example.com",
    password: "pass",
    authentication: :plain,
    tls_verify: false
  }
end
`
I'm using a self-signed cert for specific reasons.  I understand the risks but it is a local server so it doesn't matter.

The only issue is that when an email is attempting to send, I get this error
`danbooru-jobs-1      | [ActiveJob] [MailDeliveryJob] [d65dea2a-78d5-468c-bdb3-7cb8e8327343] Error performing MailDeliveryJob (Job ID: d65dea2a-78d5-468c-bdb3-7cb8e8327343) from GoodJob(default) in 113.83ms: OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 peeraddr=192.168.1.99:25 state=error: certificate verify failed (self-signed certificate)):
danbooru-jobs-1      | /usr/local/lib/ruby/3.2.0/net/protocol.rb:46:in `connect_nonblock'
danbooru-jobs-1      | /usr/local/lib/ruby/3.2.0/net/protocol.rb:46:in `ssl_socket_connect'
danbooru-jobs-1      | /usr/local/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:690:in `tlsconnect'
danbooru-jobs-1      | /usr/local/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:666:in `do_start'
danbooru-jobs-1      | /usr/local/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:611:in `start'
`
It fails to send because of a self-signed certificate.

I found that net-smtp added a tls_verify argument (https://github.com/ruby/net-smtp/blob/9e44412d0da2dc7697bc45973e9ed12f5b4acfb5/lib/net/smtp.rb#L229)
However, when passing the `tls_verify: false` as I have above, it does not change it.

I tried to take a look at why this would be the case but I am not familiar with ruby or these packages.
Not sure if sendmail would be an alternative around this problem.

**Comment by evazion** [comment]
The correct option is `openssl_verify_mode: :none` instead of `tls_verify: false`. This is documented here: https://guides.rubyonrails.org/configuring.html#config-action-mailer-smtp-settings.

Email configuration was recently changed in 10b754d715d53e46efcc8bc062b9d76543003966, so now it would be done like this:

```
DANBOORU_MAIL_DELIVERY_URL=smtp://no-reply@example.com:pass@192.168.1.99:25?authentication=plain&openssl_verify_mode=none
```
