### ISSUE TITLE
Replace all space characters in text segments during postprocessing with EN SPACE (0x2002)

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#5543]
Just a quick cursory glance through the items with text fields shows that the standard practice in English of following-up sentence endings with 2 spaces is often observed.  This helps English flow better, which is why it is always done in formal writing.  It is apparent from the frequency of use that many users expect this convention to be honored.  They may even see the final rendered version and believe that the double spaces are actually there, but a quick selection of text easily confirms that they are not, being only a single space.

https://danbooru.donmai.us/comments.json?search%5Bbody_matches%5D=%2A++%2A&limit=100
https://danbooru.donmai.us/wiki_pages.json?search%5Bbody_matches%5D=%2A++%2A&limit=20
https://danbooru.donmai.us/forum_posts.json?search%5Bbody_matches%5D=%2A++%2A&limit=100
https://danbooru.donmai.us/artist_commentaries.json?search%5Btext_matches%5D=%2A++%2A&limit=100

An alternative could be to set the CSS style to use `white-space: nowrap;` , however I'm not sure how that would cause conflicts with any of the other CSS effects in the text sections.

<hr>

**Side note:**  I actually had to use EN SPACES for the above text, since GitHub doesn't honor sequential spaces either.  You can look at it and see if you think it looks better or not.

**Comment by nottalulah** [comment]
Two spaces after a period isn't the "standard practice in English", it's a relic from the time when people wrote on typewriters that required it. Nobody in the digital era writes like that unless they're very old or have been lied to and told it's the standard. Two spaces actually recommended *against* nowadays†, and the assertion that it's "always used in formal writing" is just bogus. You yourself never wrote like that in past issues either, so not sure where this is coming from. 

Anyway, that's all to say it's wrong, it looks wrong, and the way we do things at present is the correct way to format text.

† According to [CMoS](https://www.chicagomanualofstyle.org/qanda/data/faq/topics/OneSpaceorTwo.html), [APA](https://apastyle.apa.org/style-grammar-guidelines/punctuation/space-after-period) (as of 2019), [AP Stylebook](https://twitter.com/APStylebook/status/1254786139539427329), [Microsoft](https://www.cnn.com/2020/04/27/tech/microsoft-word-two-spaces-trnd/index.html), [the EU](http://publications.europa.eu/code/en/en-360400.htm), and many others...
