### ISSUE TITLE
Uploads do not complete when using local development

### ISSUE THREAD

**Issue by OhGodItsBroken** [danbooru/danbooru#5555]
If I run docker-config.yaml as is, everything seems to work just fine, but if I try to use the local development options, uploads do not complete. User registration seems fine, and the sites can be browsed, but something times out while trying to upload.

> Upload failed: Request ran for longer than 65000ms

Uploading the exact same file had no problem when running the default settings.

Checking my apache error log show the following

>  AH01114: HTTP: failed to make connection to backend: 127.0.0.1
>  AH00957: http: attempt to connect to 127.0.0.1:3000

So I'm guessing I have something wrong in my apache conf but I'm not sure what could be missing. The proxy pass resolves the URL correctly, and the site is accessible otherwise aside from this upload issue.

Here is what the key part of my apache conf looks like.
```
<VirtualHost *:443>
    ServerName booru.example.com
    ServerAlias booru.example.com

    SSLEngine on
    SSLProxyEngine on
    ProxyPreserveHost on
    ProxyAddHeaders on
    ProxyPass /             http://127.0.0.1:3000/
    ProxyPassReverse /      http://127.0.0.1:3000/
    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
    RequestHeader set "X-Forwarded-SSL" expr=%{HTTPS}

```

**Comment by evazion** [comment]
There's not enough information to determine the cause of this. Probably what happened is that you were uploading a large file from disk, and it took more than 65 seconds to process the file. Uploading a very large video would be the most likely way of triggering this.

This timeout is set in `config/initializers/rack_timeout.rb` and can be increased by setting `RACK_REQUEST_TIMEOUT=9999` in `.env.local`.
