### ISSUE TITLE
The bookmarklet is very inconsistent for Nicoseiga manga posts

### ISSUE THREAD

**Issue by etoubleh** [danbooru/danbooru#5556]
Some posts, such as [mg463714](https://seiga.nicovideo.jp/watch/mg463714), work fine.
Others, such as [mg485611](https://seiga.nicovideo.jp/watch/mg485611), import the wrong images somehow.

**Comment by etoubleh** [comment]
Now the bookmarklet doesn't work at all for Nicoseiga posts.

**Comment by evazion** [comment]
Should be working now. It works for me on all examples I've tested.
