### ISSUE TITLE
DeviantArt strategy marks post URLs without slugs as bad_source

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5559]
https://www.deviantart.com/flurrysnowgirl/art/973817718 links to the post but is marked as bad_source.

https://danbooru.donmai.us/post_versions?search%5Bpost_id%5D=6528078

**Comment by evazion** [comment]
Fixed in 5fcd95b8c7790787b6d5dc86dd7b77d6dc388801.
