### ISSUE TITLE
tumblr "sensitive" videos cause NoMethodError

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5597]
https://github.com/danbooru/danbooru/blob/0ec753c5148011bba5763cdef66abaaee9aef086/app/logical/source/extractor/tumblr.rb#L92
Here `image_url` is nil because 

https://github.com/danbooru/danbooru/blob/0ec753c5148011bba5763cdef66abaaee9aef086/app/logical/source/extractor/tumblr.rb#L27-L29

`post[:video_url]` is nil.

Seems to not be an issue (presently) for non-video posts because `post[:type]` returns nil...

**Comment by evazion** [comment]
I can't find any videos to test this with.

**Comment by nottalulah** [comment]
https://ebith1969.tumblr.com/post/48214164804 is the post that I reported this for.
