### ISSUE TITLE
anonymous settings?

### ISSUE THREAD

**Issue by pokeball99** [danbooru/danbooru#5603]
Currently, it is not possible to do anything as an anonymous viewer other than show the scores of image and their preview size. being forced to create an account to have dark mode and other features that don't need to be locked behind accounts is something that should be rectified.

**Comment by nonamethanks** [comment]
It's on purpose so that people are encouraged to sign up. We don't need to give anons more privileges, because they can just register for free and participate in the site (unless they're banned of course, in which case they're not welcome anymore).
