### ISSUE TITLE
Cloudflare challenge when attempting to download a image from cdn

### ISSUE THREAD

**Issue by istir** [danbooru/danbooru#5610]
Some time ago I created a simple app using `reqwest` library in rust for myself that lets me download a image to a specific folder on a disk. Everything worked fine, but today I started to get cloudflare challenges while attempting to do so. 

I am specifying a user agent `Mozilla/5.0 (compatible; app-name/1.0; +https://app-name.com/)` (with app-name being a placeholder for here) and also tried to authenticate using Basic Authentication header.

I think this doesn't happen in browser because it passes `_danbooru2_session` cookie, but getting a http only cookie would require some tinkering. 

Is there any way to get either whitelisted, or maybe I'm forgetting to pass something?

**Comment by red-tails** [comment]
See this forum post: https://danbooru.donmai.us/forum_posts/263556

**Comment by istir** [comment]
Thank you, my first thought was going on github instead of forums. 
Sad that we can't have nice things because of AI bros as usual. 
Just for clarity - I don't think I'm a part of the problem for how much stuff I download, which is maybe few images a day.
