### ISSUE TITLE
Error response from daemon: invalid mount config ... .danbooru_local_config.rb does not exist

### ISSUE THREAD

**Issue by cirnoscodingclass** [danbooru/danbooru#5627]
**Describe the bug**
Running a new instillation of danbooru [7b77d08](https://github.com/danbooru/danbooru/commit/7b77d08e44eae3b061b2462a54eae030350d2ecb) and encountering this error. Very similar to this [issue](https://github.com/danbooru/danbooru/issues/5626#issue-2080574519) 

`Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/user/Container/danbooru/config/danbooru_local_config.rb

**To Reproduce**
1. `git clone` the [7b77d08](https://github.com/danbooru/danbooru/commit/7b77d08e44eae3b061b2462a54eae030350d2ecb) version of danbooru
2. `sudo docker compose up`
3. See error

**Expected behavior**
For the image to build and run at localhost

**Desktop:**
 - OS: Fedora Linux 39 (Workstation)

**Additional context**
This can be fixed if the user creates the danbooru_local_config.rb to the config directory. But for those who do not need to make any local changes have no need to create a local config. Wondering if this change is now intentional or a bug?

**Comment by cirnoscodingclass** [comment]
Too add to this issue the image takes on any changes done in the danbooru_local_config ignoring if line 118 ` # - "$PWD:/danbooru"` is commented or not. Changes in files stored in /app does not seem to change. Have not tried to edit other directories.

Changing the path in line 118 to my local directory `- "$HOME/user/Container/danbooru:/danbooru"` causes an issue when `sudo docker compose up` :

```
danbooru-danbooru-1  | bash: line 1: bin/rails: No such file or directory
danbooru-nginx-1     | 2024/01/14 18:34:28 [notice] 8#8: using the "epoll" event method
danbooru-nginx-1     | 2024/01/14 18:34:28 [notice] 8#8: openresty/1.25.3.1
danbooru-nginx-1     | 2024/01/14 18:34:28 [notice] 8#8: built by gcc 13.2.0 (Ubuntu 13.2.0-9ubuntu1) 
danbooru-nginx-1     | 2024/01/14 18:34:28 [notice] 8#8: OS: Linux 6.6.9-200.fc39.x86_64
danbooru-nginx-1     | 2024/01/14 18:34:28 [notice] 8#8: getrlimit(RLIMIT_NOFILE): 1073741816:1073741816
danbooru-nginx-1     | 2024/01/14 18:34:28 [notice] 8#8: start worker processes
danbooru-nginx-1     | 2024/01/14 18:34:28 [notice] 8#8: start worker process 10
danbooru-danbooru-1 exited with code 0
danbooru-danbooru-1 exited with code 127
danbooru-danbooru-1 exited with code 127
dependency failed to start: container danbooru-danbooru-1 is unhealthy
```

Could be an issue on my part, so please let me know. Also let me know if this should be opened as a new issue.

**Comment by evazion** [comment]
Right now the Docker Compose setup is under development and it has some bugs. For now, if you just want to get a working install, you'd be better off doing `git clone https://github.com/danbooru/danbooru -b production` and `docker compose up` to use the latest stable version of Danbooru. You may need to do `docker volume rm danbooru-data` to get rid your data from the newest version before you go back to the old version.

Be aware that if you do this and then later upgrade to a newer version, there will be some manual steps you will need to follow to keep your data:

https://github.com/danbooru/danbooru/commit/69ad1e0899946908ea293433aeac22f709bff9ce
https://github.com/danbooru/danbooru/commit/93a13017e04353ca538e21791e408e4648a77f46

**Comment by evazion** [comment]
>This can be fixed if the user creates the danbooru_local_config.rb to the config directory. But for those who do not need to make any local changes have no need to create a local config. Wondering if this change is now intentional or a bug?

It's a bug. The bug is that we want to include the config file in the container if it exists, and ignore it if it doesn't exist, but it seems Docker Compose doesn't have an easy way to do that.

**Comment by cirnoscodingclass** [comment]
> Right now the Docker Compose setup is under development and it has some bugs. For now, if you just want to get a working install, you'd be better off doing `git clone https://github.com/danbooru/danbooru -b production` and `docker compose up` to use the latest stable version of Danbooru. You may need to do `docker volume rm danbooru-data` to get rid your data from the newer version before you go back to the old version.
> 
> Be aware that if you do this and then later upgrade to a newer version, there will be some manual steps you will need to follow to keep your data: [69ad1e0](https://github.com/danbooru/danbooru/commit/69ad1e0899946908ea293433aeac22f709bff9ce), [93a1301](https://github.com/danbooru/danbooru/commit/93a13017e04353ca538e21791e408e4648a77f46).

Thanks for the notice, I'll work in the production branch.
