### ISSUE TITLE
Feature Request for Private Community Boards

### ISSUE THREAD

**Issue by ThesiiNCey** [danbooru/danbooru#5675]
A way to make a private Booru that is invitation-based or with a register token without allowing users who are not logged in to see posts

Describe the solution you'd like

1. When registering, enter a token that can be set in the admin settings
2. That guests without an account cannot see posts

**Comment by evazion** [comment]
fde15d9799f2bc17f5e073af3d4e62d6ab75cbf8 closed the wrong issue.

**Comment by ThesiiNCey** [comment]
What ? Sry i dont Unterstand

**Comment by nottalulah** [comment]
He linked to this issue instead of #5676 which caused this to be closed by accident.

**Comment by ThesiiNCey** [comment]
I was scared because me and my community are just waiting for a positive answer

😅

**Comment by nonamethanks** [comment]
One way to quickly enable this in your local instance may be to edit [this line](https://github.com/danbooru/danbooru/blob/fde15d9799f2bc17f5e073af3d4e62d6ab75cbf8/app/models/post.rb#L1928)
to something like 


```ruby

  def levelblocked?(user = CurrentUser.user)
    !user.is_gold? 
  end

```

And then manually promoting to gold whoever you want. Note: I haven't tested this.

**Comment by ThesiiNCey** [comment]
Good Idea but a Normal Solution would be better for us

**Comment by RealBeyondMaster** [comment]
Second that, been looking also for such a solution. Maybe tier rankings, or verifications? Something like that would be dope. Thanks.

**Comment by nottalulah** [comment]
I'll be honest, it doesn't seem likely such a thing would be integrated into Danbooru itself since it would never be used on the main site. If you know a bit of Ruby it shouldn't be terribly difficult to add it yourself, though.

**Comment by ThesiiNCey** [comment]
A Login token should be Not the Problem i think its Only a extra permissions in Registration Form but i dont Unterstand Ruby so i ask here

**Comment by ThesiiNCey** [comment]
nvm chatgtp to all what i want with it xD not its Invite Only without error message :D

**Comment by ThesiiNCey** [comment]
> One way to quickly enable this in your local instance may be to edit [this line](https://github.com/danbooru/danbooru/blob/fde15d9799f2bc17f5e073af3d4e62d6ab75cbf8/app/models/post.rb#L1928) to something like
> 
> ```ruby
>   def levelblocked?(user = CurrentUser.user)
>     !user.is_gold? 
>   end
> ```
> 
> And then manually promoting to gold whoever you want. Note: I haven't tested this.

Guests can see Forum and tags can i disable this to ?
