### ISSUE TITLE
[Feature Request] Image Uploads

### ISSUE THREAD

**Issue by ThesiiNCey** [danbooru/danbooru#5680]
It would be great to have an option to automatically convert images to JPG or JPEG because they are smaller on the server than PNG images, which can save a lot of storage space

**Comment by nottalulah** [comment]
That would completely go our goal of keeping the original version of images intact; I can't ever see this being added to Danbooru.

**Comment by nonamethanks** [comment]
Danbooru is an archival website, our purpose is to archive art. Any recompression or modification of the original files is never going to be implemented.
