### ISSUE TITLE
Specific Tags for Platin Users Only

### ISSUE THREAD

**Issue by ThesiiNCey** [danbooru/danbooru#5688]
Can i set Tag Permissions like the Tag ( Gaming ) is only visable for Platin User ?

If that's possible then I'm sorry for the issue but it's quite confusing

**Comment by ErikHumphrey** [comment]
Most code for restricted tags uses `is_gold`, so you'd have to change relevant lines and build your own version that uses `is_platinum` instead.

https://github.com/danbooru/danbooru/blob/c1a3b991e7b6f796b6d69a01e059dd7b7333bf8f/app/models/user.rb#L466C1-L468
