### ISSUE TITLE
Yet more icons for artist pages

### ISSUE THREAD

**Issue by HeeroWingZero** [danbooru/danbooru#5692]
Vgen
https://vgen.co/img/favicon-32x32.png

Threads.net
https://static.cdninstagram.com/rsrc.php/ye/r/lEu8iVizmNW.ico

Final Fantasy XIV
https://lds-img.finalfantasyxiv.com/pc/global/images/favicon.ico?1707879950

Taittsuu
https://taittsuu.com/image/kari_apple_touch_icon.png

Onaco
https://onaco.jp/favicon.ico

Crepu.net
https://crepu.net/images/kuma_icon/icon-192x192.png

Roblox
https://images.rbxcdn.com/7bba321f4d8328683d6e59487ce514eb

Afdian.net
https://static.afdiancdn.com/static/img/icons/apple-touch-icon-152x152.png

iwara.tv
https://www.iwara.tv/logo.png

ouxiangxiezhen
http://www.ouxiangxiezhen.com/favicon_xz.png

comicvine.gamespot
https://comicvine.gamespot.com/a/bundles/comicvinesite/images/favicon.ico

gamefaqs.gamespot (couldn't find a URL, had to rip this one myself)
![download](https://github.com/danbooru/danbooru/assets/117999306/25af8327-8433-4fac-835c-30a86073b444)

mobygames
https://www.mobygames.com/static/img/favicon.ico

PlanetMinecraft
https://www.planetminecraft.com/images/layout/favicon-64.png

Venmo.com
https://venmo.s3.amazonaws.com/favicon.ico

theshop.jp / thebase.com
https://static.thebase.in/apple-touch-icon.png

square.site / squareup.com
https://metalstone-art.square.site/square.ico
https://xms-production-f.squarecdn.com/xms/assets/public-web-styles/favicon-770e0889aefd823056c7cdbb066a445be0f0754c1b4d4cba877e120fdbcb63e6.ico

artfol.co
https://www.artfol.co/favicon.ico

threadless.com
https://www.threadless.com/favicon.ico

taplink.cc
https://taplink.cc/favicon.ico

aibooru.online
https://aibooru.online/favicon.ico

solo.to
https://cdn.solo.to/images/favicon.png

tensor.art
https://tensor.art/tensorart.ico

Civitai
https://i0.wp.com/education.civitai.com/wp-content/uploads/2023/07/5000x5000_faviconC.png?fit=5000%2C5000&ssl=1

Marvel.com
https://www.marvel.com/static/favicon/favicon.ico

DC.com / dccomics.com
https://www.dc.com/favicon.ico

League of Comic Geeks
https://leagueofcomicgeeks.com/favicon.ico

Image Comics
https://cdn.imagecomics.com/apple-touch-icon.png

Booklive
https://booklive.jp/favicon.ico?date=0930

manba.co
https://manba.co.jp/favicon.ico

atwiki.jp
https://w.atwiki.jp/common/_img/atwiki_logo_small.svg?t=741a51e81c8c8d5fe9627b874ecad193

goo.ne.jp
https://www.xgoo.jp/top2018/public/img/favicon.ico

Mangaz
https://www.mangaz.com/android-chrome-192x192.png

Ganknow
https://ganknow.com/favicon.ico?v=2

dmm.co
https://p.dmm.co.jp/p/common/pinned/favicon.ico

manga-no.com
https://manga-no.com/icon.svg

rookie.shonenjump
https://cdn.rookie.shonenjump.com/images/core/favicon.ico?sAqQleVISvnc

Makersplace
https://makersplace.com/static/frontend/apple-touch-icon.dd7176cf.png

eth.co
https://assets.ethcocdn.com/favicon-228-ad7c26984722a56c5b14ae3ce556b962.png?vsn=d

Lynkfire
https://lynkfire.com/favicon.ico

Cubebrush.co
https://djm6btoj9k6cu.cloudfront.net/assets/favicon/favicon-32x32-e5ecd284e7fb2371a18514490b56cde8ece0e991bd5bd872872af6370e3ed3ca.png

direct.me
https://direct.me/static/favicons/apple-touch-icon.png

linkbio.co
https://bio.linkcdn.cc/instabio.cc/favicon.ico

marpple.shop
https://marpple.shop/ico/creator/favicon-192.png?v=2024021601

msha.ke
https://looks.msha.ke/site-generator/assets/d7ac02eea45e49763771f8e6b8ca3a35.ico

itaku.ee
https://itaku.ee/assets/favicon-light.ico

Charasuji
https://www.charasuji.com/favicon.ico

m-pe.tv
https://m-pe.tv/favicon.ico

cash.app
https://cash-f.squarecdn.com/static/favicon.svg

Carbonmade
https://carbonmadeassets.b-cdn.net/wp-content/uploads/2019/04/favico2.png

Fansly
https://fansly.com/assets/images/icons/favicon.ico?v=12

Throne.com
https://assets-global.website-files.com/647dfd182460b45da7ca7613/648ae40384ca07f777f6079f_Throne_Icon_Square_White_on_Gradient.svg

Tellonym
https://www2.tellonym.me/assets/img/icon180x180.png

pronouns.page
https://pronouns.page/logo/logo-primary.svg

pronouny.xyz
https://pronouny.xyz/modules/core/client/img/brand/favicon.ico

rentry.co
https://rentry.co/static/icons/512.png

retrospring
https://retrospring.net/images/favicon/favicon-32.png

share-on.me
https://drawme.share-on.me/static/favicon/android-icon-192x192.png

drum.io
https://assets-global.website-files.com/5f20a675032da6815c9799c5/5f5137f2c4ef42039c25894a_App%20Store%20Logo%20-%20256x256.png

Famiport
https://famistore.famiport.com.tw/favicon.ico

doujin.com.tw
https://www.doujin.com.tw/favicon.ico

cli-bo.com / clibo.tw
https://clibo.tw/images/apple-touch-icon.png

gamer.com.tw
https://i2.bahamut.com.tw/favicon.svg?v=1689129528

myship.7-11.com.tw (no URL, auto downloaded when I tried to access it)
<img width="24" alt="favicon" src="https://github.com/danbooru/danbooru/assets/117999306/4d5fc253-f31a-4c7f-aa1d-f0aa00c14138">

Notion.site / notion.so
https://www.notion.so/images/favicon.ico

Nizima
https://nizima.com/favicon.38e96075.ico

Baidu
https://tb3.bdstatic.com/public/icon/favicon-v2.ico

Miyoushe
![download (1)](https://github.com/danbooru/danbooru/assets/117999306/d45c65eb-b336-42cf-8f29-757c3c515bcd)

huaban.com
https://st0.dancf.com/static/02/202306090204-51f4.png

Chongya.com
https://static.chongyacdn.com/favicon.ico

Spinspin.net
https://spinspin.net/icons/android-icon-192x192.png

scratch.mit.edu
https://scratch.mit.edu/favicon.ico

sheezy.art
https://sheezy.art/favicon.ico

Neocities.org
https://neocities.org/img/favicon.png

**Comment by evazion** [comment]
Here's a test artist page showing all the icons: https://testbooru.donmai.us/artists/8.
