### ISSUE TITLE
DText: Emdedded images aren't hidden by [spoiler] tags.

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#5700]
The image isn't hidden here:

```
[spoiler]
!post #1
[/spoiler]
```

**Comment by DCrow** [comment]
Also noticed(not sure if this is intended) that these return different previews.
```
[spoiler]
!post #1
[/spoiler]
```
```
[spoiler]!post #1[/spoiler]
```
First one will show an image in the preview, second one will show an exclamation mark and a link to the post.

**Comment by nottalulah** [comment]
From 5c173330a323115c81e16ac6e11c492d0508abf5:

> The `!post #1` syntax has to go on a line by itself. It can't go in the middle of a paragraph,
inside a header, inside a table, etc.

**Comment by DCrow** [comment]
I see. Maybe add something about this? In `wiki_pages/help:dtext` or `formatting help`, since its not mentioned anywhere.
