### ISSUE TITLE
Xiaohongshu short url support

### ISSUE THREAD

**Issue by kagayakushininggate** [danbooru/danbooru#5738]
Xiaohongshu uses shortened URLs when copying links to posts from the mobile app. For instance, here's a message that gets copied to clipboard:
42 霓秋nikiyo发布了一篇小红书笔记，快来看吧！ 😆 64RX6TcOnlL5Rb3 😆 http://xhslink.com/ErpbmK，复制本条信息，打开【小红书】App查看精彩内容！
Where the so-called "shortened" URL is:
http://xhslink.com/ErpbmK%EF%BC%8C%E5%A4%8D%E5%88%B6%E6%9C%AC%E6%9D%A1%E4%BF%A1%E6%81%AF%EF%BC%8C%E6%89%93%E5%BC%80%E3%80%90%E5%B0%8F%E7%BA%A2%E4%B9%A6%E3%80%91App%E6%9F%A5%E7%9C%8B%E7%B2%BE%E5%BD%A9%E5%86%85%E5%AE%B9%EF%BC%81
However, all characters after the code can be ignored, and http://xhslink.com/ErpbmK is also a valid shortened URL. Both versions lead to:
https://www.xiaohongshu.com/explore/663c6669000000001e037ad9?app_platform=android&app_version=8.11.9&author_share=1&ignoreEngage=true&share_from_user_hidden=true&type=normal&xhsshare=CopyLink&appuid=6651d57c00000000030307c4&apptime=1716639206

**Comment by Wanbansui** [comment]
The short link support is now broken again.
The full comma and the following information are never part of the link.

**Comment by nonamethanks** [comment]
@Wanbansui do you have an example of a link that doesn't work?

**Comment by Wanbansui** [comment]
> @Wanbansui do you have an example of a link that doesn't work?

https://danbooru.donmai.us/posts?tags=source%3A*xhslink*

Currently, posts sourced from xhslink.com are automatically tagged with “bad_source”, and uploading using these links returns the message “Doesn’t contain any images”.

**Comment by nonamethanks** [comment]
Looks like the extractor is broken for some posts.
