### ISSUE TITLE
Partial Banciyuan support

### ISSUE THREAD

**Issue by kagayakushininggate** [danbooru/danbooru#5742]
The site is gone, so I have 0 hope for full support with commentaries and artists and whatnot, but at least for now all the images can still be accessed. What I'm asking for is automatically converting sample URLs to fullsize URLs. The URL below notes relevant sample URLs and corresponding full-size URLs.
https://wiki.archiveteam.org/index.php/%E5%8D%8A%E6%AC%A1%E5%85%83

**Comment by nottalulah** [comment]
That was added in e26d321707d77ce08f4c72bb9b35b1ba70dda6bd, wasn't it?
