### ISSUE TITLE
IQDB: hash lookup with invalid hash raises a CookieOverflow exception

### ISSUE THREAD

**Issue by Charsy89** [danbooru/danbooru#5752]
When performing a hash lookup using the [Reverse Image Search](https://danbooru.donmai.us/iqdb_queries) feature, Danbooru responds with the following error:
```
An unexpected error has occurred.

Details: ActionDispatch::Cookies::CookieOverflow exception raised.

app/logical/rack_server_timing.rb:19:in `call'
```
This seems to occur with any input entered into the "Hash" field, except spaces or no input.

**Comment by nottalulah** [comment]
This seems to only happen when you pass an invalid hash, because the IQDB service returns an error ~2kb long, which is stored as a flash, which is stored in the session cookie.

**Comment by Charsy89** [comment]
What constitutes an invalid hash? In my experience, this happens with any input, including valid hashes (32-character long hexadecimal string).

### Examples
*Note: all examples listed here are SFW*
Hash of a file that **is** on Danbooru: b0117dc251174ceccbd044cd8389a949
Hash of a file that **is not** on Danbooru: 62536837147be2af1e93a8b5ebdc7e74
Invalid input: ijfeoIFJOeghg90ru4oihEJFG83r

All of these lead to the same error page.
I don't understand what you mean by "invalid hash", so if you could clarify, that would be great. Sorry if that sounded rude, that wasn't my intention.

**Comment by 9suika** [comment]
> Hash of a file that **is** on Danbooru: b0117dc251174ceccbd044cd8389a949

That's the post's MD5 checksum. IQDB hashes look like this:
```
iqdb_3fe868732c3ca6e33fb67a777d1399ea3fa444c4c3f379b8e400f200f280f97df980fb00fbfefcfdfe71fe79fe80fef4fefafefeff72ff7cfff1fff2fff9fffd000200040006000a0014008000820094010001820184018802000280028f04000506050a05800880f9fdfafafafffd7afd7ffd80fe7cfe7eff00ff7aff7fff80fff6fffcfffe000100030006000b000c008401020106018001810183018602820283028e0402048605000507050e060f0680068206830686f500f77afa72fa75fa80fafafafefdf4fdfafdfffe7afe7cfe7efef9fefdff00ff72ff79ff80fffcfffe0001000c000f00810084008c01010102010601800187018f02000207021d04860500050e0680
```

**Comment by nottalulah** [comment]
MD5 isn't suitable for image similarity, so IQDB has its own custom hash function. Passing anything that isn't a valid IQDB hash spits out a giant error that causes that cookie overflow. It's not that surprising that people would get confused given the only "hashes" people normally see are MD5 (and now there's also the pixel hash), and IQDB hashes are only exposed through the IQDB search API, not anywhere on the site regularly. You can try something like https://danbooru.donmai.us/iqdb_queries.json?post_id=7560760 to see the hashes.

The error should probably be fixed, but if you just want MD5 lookup you can do what 9suika said (commas work, so you can do searches like [this](https://danbooru.donmai.us/posts?tags=md5%3Ab6d778cdf26d597dc8fef8ecbebf608d%2C85030f7cd14187a8c4781a24d55d29c1&z=5)), or use the MD5 redirect like this https://danbooru.donmai.us/posts?md5=b6d778cdf26d597dc8fef8ecbebf608d. If you do want similar image lookup, you either have to upload the file or compute the IQDB hash yourself, not use the MD5.

**Comment by Charsy89** [comment]
I see. Thank you for clarifying that. I'll do that from now on.

Shall I close the issue, then? Or, since you say the error should be fixed, should it stay open?

**Comment by nottalulah** [comment]
Leave it open, the error should be improved regardless.
