### ISSUE TITLE
Prevent voting on own comments

### ISSUE THREAD

**Issue by ErikHumphrey** [danbooru/danbooru#5775]
Prevent comment authors from voting on their own comments, or automatically upvote author's own comment when posted. It can be hard to tell how many people have voted on a comment of a score with 0 or 1, and any other score might be influenced by the author's own vote.

**Comment by nonamethanks** [comment]
https://github.com/danbooru/danbooru/commit/9f313c94d18e8b2e62c49f7152b05a4182250499 contains the reasoning for allowing people to vote on their own comments.
