### ISSUE TITLE
[Support/Assist Request] Change system user name (defaults to DanbooruBot) after initial startup?

### ISSUE THREAD

**Issue by teward** [danbooru/danbooru#5779]
I have a Docker deployment of a danbooru environment, and I want to change the default system user.  Unfortunately, I didn't set it in the environment data before I spun up the Docker environment, so I'm not 100% sure how to change it after the fact.

Is it as simple as editing the DNS or making a change in the config, entering the environment, and then rebaking all the posts/data?

**Comment by hdk5** [comment]
The only method that retrieves the system user is `User.system`, which is defined as
```rb
User.find_by!(name: Danbooru.config.system_user)
```
That means that changing the `system_user` configuration setting (either via env vars or `danbooru_local_config.rb`) and renaming the user in the database (via db console) should be enough for this matter.

**Comment by teward** [comment]
> The only method that retrieves the system user is `User.system`, which is defined as
> ```rb
> User.find_by!(name: Danbooru.config.system_user)
> ```
> That means that changing the `system_user` configuration setting (either via env vars or `danbooru_local_config.rb`) and renaming the user in the database (via db console) should be enough for this matter.

After trying to change it just from the env vars I noticed some DB breakage when trying to upload.  Wiping and rebuilding it fixed things.  Odd that this was behaving weird though in my first rollout and then nuking it and starting over started working. *shrugs*
