### ISSUE TITLE
Artist entries for youtube; youtube.com/c/johndoe vs youtube.com/@johndoe

### ISSUE THREAD

**Issue by baconmeh** [danbooru/danbooru#5815]
![image](https://github.com/user-attachments/assets/036c09b8-79fa-4095-8d6c-f02e88188d2f)
Like the [last issue](https://github.com/danbooru/danbooru/issues/5812), YouTube links support both /c/ and /@. I'm unsure which of these should be prioritized, but we only need one.

**Comment by etoubleh** [comment]
Both of those channel URL formats should go unused in favor of static channel URLs.
For the example you used, that would be https://www.youtube.com/channel/UCE3ZOOuS8qEqaExFrcqh28w.

**Comment by nonamethanks** [comment]
Right now /c/ and /@ urls are separated in the code. One is considered "channel_name", the other "handle". I'm not sure if evazion found some weird edge cases when he implemented it that way, but I recall finding some similar quirks for other youtube urls. Before this can be fixed, it would be useful to use a script to verify with a few hundreds urls if this redirect is always valid.

**Comment by GHVirus** [comment]
“Custom URL” (/c/) are distinct identifiers from “handles” ( @ ) and are not necessarily the same for the same channel.

**Comment by nonamethanks** [comment]
Well, that's one negative. Both https://www.youtube.com/@GHSGHS and  https://www.youtube.com/c/GH.S return 404. Guess we can close this.
