### ISSUE TITLE
Suggest adding reverse page numbering to the settings

### ISSUE THREAD

**Issue by y1031950048** [danbooru/danbooru#5820]
Suggest adding reverse page number function in settings, (e.g. 100→99→98→97→...), the new content is updated to page 101, so that later browsing to the halfway point, for example, browsing to page 50, Edge favorites this web page, the next time you open it, then the content of the last browsing to page 50 will not be pushed to page 51, 52 to go.
(translate tool:Deepl)

![PixPin_2024-09-23_01-31-38](https://github.com/user-attachments/assets/feca2b1e-73b0-41ff-b32c-c2de92f963d6)

**Comment by hdk5** [comment]
Can't you just use the proper `order:` search metatag for this, e.g. `order:id` or whatever fits?

**Comment by nonamethanks** [comment]
If you want to keep track of new posts like that you should use the before/after page method.

Let's say you want to keep track of the "cat" tag and always be able to check out new results. You open "cat" and notice that the last uploaded post was post #8305751.

You replace the page in the url with "a8305751" ("after post 8305751"). Now you have this url:
https://danbooru.donmai.us/posts?tags=cat&page=a8313683
You bookmark this url, and next time you visit it you'll be able to resume from where you left. If you navigate through the page arrows, the new urls you get will still use this system, so you can use it as a permanent way to keep track of the posts you saw.
