### ISSUE TITLE
(API) Discord bot gets Error 403 upon fetching images.

### ISSUE THREAD

**Issue by Lumiflag** [danbooru/danbooru#5838]
I've been trying to code a simple Discord bot who fetches a random image of a specified character upon entering the command. However, each time I've been meaning to run the bot, I get a 403 Forbidden error from Danbooru. 

I've switched to betabooru, no success. I even made a call with Postman (which worked btw), but it just doesn't work with my bot.
The bot is written in C#, by the way. I can send the code if needed.

**Comment by nottalulah** [comment]
The code would help, but make sure you are not sending fake User-Agents as those are blocked. Devs would generally prefer if you send a user-agent header including your bot name and some form of contact. That's one thing that a lot of people seem to have issues with.

**Comment by Lumiflag** [comment]
Here's the code that fetches an image.



`        // Fetch image from Danbooru API
        private async Task<string> FetchDanbooruImage(string character)
        {
            try
            {
                // Username and API KEY
                string username = "Lumiflag";
                string apiKey = "LCEn9XSS5x2NLfQM426KGhTU";

                // Build the request URL to search for the character and exclude NSFW images
                string url = $"https://danbooru.donmai.us/posts.json?tags={character}+rating:safe&limit=5";

                // Add basic authentication to the request
                var byteArray = new System.Text.ASCIIEncoding().GetBytes($"{username}:{apiKey}");
                _httpClient.DefaultRequestHeaders.Authorization =
                    new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", Convert.ToBase64String(byteArray));

                // Log the request URL for debugging
                Console.WriteLine($"Fetching from URL: {url}");

                // Make the request to Danbooru
                var response = await _httpClient.GetStringAsync(url);

                // Log the raw response for debugging
                Console.WriteLine($"Danbooru API response: {response}");

                // Parse the JSON response
                JArray posts = JArray.Parse(response);

                // Log the number of posts found
                Console.WriteLine($"Found {posts.Count} posts.");

                // If no posts are found, return null
                if (posts.Count == 0)
                {
                    return null;
                }

                // Choose a random post from the safe results
                var random = new Random();
                JObject selectedPost = (JObject)posts[random.Next(posts.Count)];

                // Log the selected post for debugging
                Console.WriteLine($"Selected post: {selectedPost}");

                // Return the URL of the selected image
                string imageUrl = selectedPost["file_url"].ToString();
                Console.WriteLine($"Image URL: {imageUrl}");

                return imageUrl;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error fetching image: {ex.Message}");
                return null;
            }
        }
    }
}`

**Comment by nottalulah** [comment]
You should probably delete that API key from your account. But since you didn't send the full class I will assume you forgot to set a User-Agent; the default .NET HTTP client sends a blank User-Agent unless you explicitly set it, which is blocked by Danbooru. Something like this worked for me (though I don't have an API key to use):

```csharp
using System.Text.Json.Nodes;

await new Program().GetPosts("provence_(arknights)");

partial class Program {
  HttpClient httpClient = new();

  public Program() {
    httpClient.DefaultRequestHeaders.Add("User-Agent", "Lumiflagbot/1.0");
  }

  async Task<string?> GetPosts(string charName) {
    try {
      // Username and API KEY
      string username = "Lumiflag";
      string apiKey = "<valid api key>";

      // Build the request URL to search for the character and exclude NSFW images
      string url = $"https://danbooru.donmai.us/posts.json?tags={charName}+rating:safe&limit=5";

      // Add basic authentication to the request
      var byteArray = new System.Text.ASCIIEncoding().GetBytes($"{username}:{apiKey}");
      httpClient.DefaultRequestHeaders.Authorization =
          new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", Convert.ToBase64String(byteArray));

      // Log the request URL for debugging
      Console.WriteLine($"Fetching from URL: {url}");

      // Make the request to Danbooru
      var response = await httpClient.GetStringAsync(url);

      // Log the raw response for debugging
      Console.WriteLine($"Danbooru API response: {response}");

      // Parse the JSON response
      JsonArray posts = (JsonArray)JsonArray.Parse(response);

      // Log the number of posts found
      Console.WriteLine($"Found {posts.Count} posts.");

      // If no posts are found, return null
      if (posts.Count == 0) {
        return null;
      }

      // Choose a random post from the safe results
      var random = new Random();
      JsonObject selectedPost = (JsonObject)posts[random.Next(posts.Count)];

      // Log the selected post for debugging
      Console.WriteLine($"Selected post: {selectedPost}");

      // Return the URL of the selected image
      string imageUrl = selectedPost["file_url"].ToString();
      Console.WriteLine($"Image URL: {imageUrl}");

      return imageUrl;
    } catch (Exception ex) {
      Console.WriteLine($"Error fetching image: {ex.Message}");
      return null;
    }
  }
}
```

prints
```
Image URL: https://cdn.donmai.us/original/07/6d/076d82b72bc8ea05cf4dcae96416ae81.jpg
```

(p.s. some posts won't have a file_url if you can't see them, be sure to add a condition for that or your bot will crash with a NullReferenceException)

**Comment by Lumiflag** [comment]
I don't really have time to fix this, right now, so could you fix it for me, please ? I'll send a zip containing the Program.cs file.
[Program.zip](https://github.com/user-attachments/files/17304137/Program.zip)

**Comment by Lumiflag** [comment]
So, I did it myself in the meantime. Now I get both a 401 Unauthorized and a 403 Forbidden error.
![image](https://github.com/user-attachments/assets/6a3d5a4e-0e31-4d02-84b5-5d86093df28a)

**Comment by nonamethanks** [comment]
To access the danbooru api a client needs to send a valid user agent string (and not spoof a browser user agent), and send api key & username as authentication. If you're getting 403 then one of those two things is not configured corretly.
