### ISSUE TITLE
API Bug:  My uploads -> JSON export not using filter

### ISSUE THREAD

**Issue by Joebugg** [danbooru/danbooru#5840]
[API Bug:  My uploads -> JSON export not using filter](https://booru.allthefallen.moe/forum_topics/1972)

> https://booru.allthefallen.moe/users/########/uploads.json?search[is_posted]=false
> This should only list unposted uploads, but instead includes all of them.  I guess this can be filed under API bugs?  Does it need to get added to the Github issues tracker, instead?
> 
> It does list if they're completed or have an error or whatever, so they are easy to filter with JSON parsers.  This allows the workaround of just looking for ones where status has the right value?

Put it here, for devs to see.

**Comment by nottalulah** [comment]
Seems to work as expected for me.

**Comment by Joebugg** [comment]
Alternative question:  How do I know which are unposted, from the JSON data?

**Comment by nottalulah** [comment]
You can try something like https://danbooru.donmai.us/media_assets.json?only=id,post[id]. If the post field is not present, it's unposted. You'll have to include every field you want manually, though.

**Comment by Joebugg** [comment]
Here's a list of the critical paths in the JSON tree's [hierarchy](https://booru.allthefallen.moe/users/*userID*/uploads.json).  Note that you can only see your own uploads list, unless you have the administrative permission.
0/id:  XXXXXX
0/upload_media_assets/0/id:  YYYYYY
0/upload_media_assets/0/upload_id:  XXXXXX
0/upload_media_assets/0/media_asset_id:  ZZZZZZ
0/upload_media_assets/0/media_asset/id:  ZZZZZZ

'0' can obviously be replaced with another number if there's multiple objects to enumerate at that level.
'XXXXXX' is the upload number that appears in [my uploads](https://booru.allthefallen.moe/users/*userID*/uploads) page.
'YYYYYY' is ?  It seems really low compared to both the number of published posts and the media asset ID.
'ZZZZZZ' is the media asset number that you'd use in https://booru.allthefallen.moe/media_assets/ZZZZZZ to see the metadata.
It's frustrating that it doesn't list the post ID if it exists, but you can get this from https://booru.allthefallen.moe/media_assets/ZZZZZZ but oddly, **not** from the [JSON](https://booru.allthefallen.moe/media_assets/719650.json) version.

**Comment by nottalulah** [comment]
YYYYYY is the upload media asset ID, it's part of a join table for uploads<->media assets. See https://danbooru.donmai.us/upload_media_assets. Post ID is not included because uploads don't contain a post ID or vice-versa. You can just make a separate request to get them after collecting media asset IDs.
