### ISSUE TITLE
How to request the group name corresponding to a tag?

### ISSUE THREAD

**Issue by kyjsj** [danbooru/danbooru#5841]
Hello,
Is there a simple way (script or others) to request the group name of a specified tag? For example, see [tag_group:hair color](https://safebooru.donmai.us/wiki_pages/tag_group%3Ahair_color), I want to get the group name 'hair color' of the tag name 'brown hair'.

**Comment by nonamethanks** [comment]
Danbooru does not have wiki grouping. That's not a "real" group, it's just a wiki page called "tag_group:hair color" with an arbitrary list of tags created by an user. 

Anyone can create this kind of page, they're manually mantained, and they have no difference in the database from any other wiki page.
