### ISSUE TITLE
Allow for deletion of unposted media assets

### ISSUE THREAD

**Issue by Missingno2024** [danbooru/danbooru#5855]
As per the title, media assets that have not yet been posted should have the option of being deleted by the uploader.

In particular are uploads that end up being duplicates/pixel-perfect duplicates, which do nothing but take up unnecessary disk space, as well as promotional images for other reward sites that simply dragged along from uploading from a given page.

**Comment by nottalulah** [comment]
#5070, #5827, #5127 etc
